# Auto-generated by codegen.py - do not edit manually
# Generated: 2026-04-22

# TABLE OF CONTENTS
# [SECTION 1] Mission Metadata
# [SECTION 2] Item Effect Definitions

########################################################################################################################
############################################# [SECTION 1] Mission Metadata #############################################
########################################################################################################################

MISSIONS = [

    ################################################### [MISSION 01] Dam ###################################################

    {
        "name": "Dam",
        "mission_id": 1,
        "map_id": 1,
        "unlock_byte_offset": 0,
        "unlock_item_name": "Dam",
        "unlock_item_id": 73037001,
        "starting_option_value": 1,
        "clear_location_ids": {
            1: 70110001,
            2: 70120001,
            3: 70130001,
        },
        "shared_clear_location_id": 70100001,
        "shared_objective_checks": [
            {
                "location_id": 70101001,
                "location_name": "Dam - Neutralize All Alarms",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 70101002,
                "location_name": "Dam - Install Covert Modem",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 70101003,
                "location_name": "Dam - Intercept Data Backup",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 70101004,
                "location_name": "Dam - Bungee Jump From Platform",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 70111001,
                    "location_name": "Dam - Bungee Jump From Platform (Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 70121001,
                    "location_name": "Dam - Neutralize All Alarms (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70121002,
                    "location_name": "Dam - Bungee Jump From Platform (Secret Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 70131001,
                    "location_name": "Dam - Neutralize All Alarms (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70131002,
                    "location_name": "Dam - Install Covert Modem (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70131003,
                    "location_name": "Dam - Intercept Data Backup (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70131004,
                    "location_name": "Dam - Bungee Jump From Platform (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################ [MISSION 02] Facility #################################################

    {
        "name": "Facility",
        "mission_id": 2,
        "map_id": 2,
        "unlock_byte_offset": 1,
        "unlock_item_name": "Facility",
        "unlock_item_id": 73037002,
        "starting_option_value": 2,
        "clear_location_ids": {
            1: 70210001,
            2: 70220001,
            3: 70230001,
        },
        "shared_clear_location_id": 70200001,
        "shared_objective_checks": [
            {
                "location_id": 70201001,
                "location_name": "Facility - Gain Entry To Laboratory Area",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 70201002,
                "location_name": "Facility - Contact Double Agent",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 70201003,
                "location_name": "Facility - Rendezvous With 006",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 70201004,
                "location_name": "Facility - Destroy All Tanks In Bottling Room",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
            {
                "location_id": 70201005,
                "location_name": "Facility - Minimize Facility Scientist Casualties",
                "flag_address": 0x75D68,
                "flag_offset": 4,
                "requires_success": True,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 70211001,
                    "location_name": "Facility - Gain Entry To Laboratory Area (Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70211002,
                    "location_name": "Facility - Rendezvous With 006 (Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70211003,
                    "location_name": "Facility - Destroy All Tanks In Bottling Room (Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 70211004,
                    "location_name": "Facility - Minimize Facility Scientist Casualties (Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": True,
                },
            ],
            2: [
                {
                    "location_id": 70221001,
                    "location_name": "Facility - Gain Entry To Laboratory Area (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70221002,
                    "location_name": "Facility - Contact Double Agent (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70221003,
                    "location_name": "Facility - Rendezvous With 006 (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70221004,
                    "location_name": "Facility - Destroy All Tanks In Bottling Room (Secret Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 70221005,
                    "location_name": "Facility - Minimize Facility Scientist Casualties (Secret Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": True,
                },
            ],
            3: [
                {
                    "location_id": 70231001,
                    "location_name": "Facility - Gain Entry To Laboratory Area (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70231002,
                    "location_name": "Facility - Contact Double Agent (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70231003,
                    "location_name": "Facility - Rendezvous With 006 (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70231004,
                    "location_name": "Facility - Destroy All Tanks In Bottling Room (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 70231005,
                    "location_name": "Facility - Minimize Facility Scientist Casualties (Double Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": True,
                },
            ],
        },
    },

    ################################################# [MISSION 03] Runway ##################################################

    {
        "name": "Runway",
        "mission_id": 3,
        "map_id": 3,
        "unlock_byte_offset": 2,
        "unlock_item_name": "Runway",
        "unlock_item_id": 73037003,
        "starting_option_value": 3,
        "clear_location_ids": {
            1: 70310001,
            2: 70320001,
            3: 70330001,
        },
        "shared_clear_location_id": 70300001,
        "shared_objective_checks": [
            {
                "location_id": 70301001,
                "location_name": "Runway - Find Plane Ignition Key",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 70301002,
                "location_name": "Runway - Destroy Heavy Gun Emplacements",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 70301003,
                "location_name": "Runway - Destroy Missile Battery",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 70301004,
                "location_name": "Runway - Escape In Plane",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 70311001,
                    "location_name": "Runway - Find Plane Ignition Key (Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70311002,
                    "location_name": "Runway - Escape In Plane (Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 70321001,
                    "location_name": "Runway - Find Plane Ignition Key (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70321002,
                    "location_name": "Runway - Destroy Missile Battery (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70321003,
                    "location_name": "Runway - Escape In Plane (Secret Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 70331001,
                    "location_name": "Runway - Find Plane Ignition Key (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70331002,
                    "location_name": "Runway - Destroy Heavy Gun Emplacements (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70331003,
                    "location_name": "Runway - Destroy Missile Battery (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70331004,
                    "location_name": "Runway - Escape In Plane (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################ [MISSION 04] Surface 1 ################################################

    {
        "name": "Surface 1",
        "mission_id": 5,
        "map_id": 4,
        "unlock_byte_offset": 3,
        "unlock_item_name": "Surface 1",
        "unlock_item_id": 73037004,
        "starting_option_value": 4,
        "clear_location_ids": {
            1: 70410001,
            2: 70420001,
            3: 70430001,
        },
        "shared_clear_location_id": 70400001,
        "shared_objective_checks": [
            {
                "location_id": 70401001,
                "location_name": "Surface 1 - Power Down Communications Dish",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 70401002,
                "location_name": "Surface 1 - Obtain Surface Safe Key",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 70401003,
                "location_name": "Surface 1 - Steal Building Plans",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 70401004,
                "location_name": "Surface 1 - Enter Base Via Ventilation Tower",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 70411001,
                    "location_name": "Surface 1 - Enter Base Via Ventilation Tower (Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 70411002,
                    "location_name": "Surface 1 - Power Down Communications Dish (Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 70421001,
                    "location_name": "Surface 1 - Enter Base Via Ventilation Tower (Secret Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 70421002,
                    "location_name": "Surface 1 - Obtain Surface Safe Key (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70421003,
                    "location_name": "Surface 1 - Power Down Communications Dish (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70421004,
                    "location_name": "Surface 1 - Steal Building Plans (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 70431001,
                    "location_name": "Surface 1 - Power Down Communications Dish (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70431002,
                    "location_name": "Surface 1 - Obtain Surface Safe Key (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70431003,
                    "location_name": "Surface 1 - Steal Building Plans (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70431004,
                    "location_name": "Surface 1 - Enter Base Via Ventilation Tower (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################ [MISSION 05] Bunker 1 #################################################

    {
        "name": "Bunker 1",
        "mission_id": 6,
        "map_id": 5,
        "unlock_byte_offset": 4,
        "unlock_item_name": "Bunker 1",
        "unlock_item_id": 73037005,
        "starting_option_value": 5,
        "clear_location_ids": {
            1: 70510001,
            2: 70520001,
            3: 70530001,
        },
        "shared_clear_location_id": 70500001,
        "shared_objective_checks": [
            {
                "location_id": 70501001,
                "location_name": "Bunker 1 - Disrupt All Surveillance Equipment",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 70501002,
                "location_name": "Bunker 1 - Copy Goldeneye Key And Leave Original",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 70501003,
                "location_name": "Bunker 1 - Get Personnel To Activate Computer",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 70501004,
                "location_name": "Bunker 1 - Download Data From Computer",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
            {
                "location_id": 70501005,
                "location_name": "Bunker 1 - Photograph Main Video Screen",
                "flag_address": 0x75D68,
                "flag_offset": 4,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 70511001,
                    "location_name": "Bunker 1 - Copy Goldeneye Key And Leave Original (Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70511002,
                    "location_name": "Bunker 1 - Photograph Main Video Screen (Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 70521001,
                    "location_name": "Bunker 1 - Disrupt All Surveillance Equipment (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70521002,
                    "location_name": "Bunker 1 - Copy Goldeneye Key And Leave Original (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70521003,
                    "location_name": "Bunker 1 - Photograph Main Video Screen (Secret Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 70531001,
                    "location_name": "Bunker 1 - Disrupt All Surveillance Equipment (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70531002,
                    "location_name": "Bunker 1 - Copy Goldeneye Key And Leave Original (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70531003,
                    "location_name": "Bunker 1 - Get Personnel To Activate Computer (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70531004,
                    "location_name": "Bunker 1 - Download Data From Computer (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 70531005,
                    "location_name": "Bunker 1 - Photograph Main Video Screen (Double Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################## [MISSION 06] Silo ###################################################

    {
        "name": "Silo",
        "mission_id": 8,
        "map_id": 6,
        "unlock_byte_offset": 5,
        "unlock_item_name": "Silo",
        "unlock_item_id": 73037006,
        "starting_option_value": 6,
        "clear_location_ids": {
            1: 70610001,
            2: 70620001,
            3: 70630001,
        },
        "shared_clear_location_id": 70600001,
        "shared_objective_checks": [
            {
                "location_id": 70601001,
                "location_name": "Silo - Plant Bombs In Fuel Rooms",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 70601002,
                "location_name": "Silo - Photograph Satellite",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 70601003,
                "location_name": "Silo - Obtain Telemetric Data",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 70601004,
                "location_name": "Silo - Retrieve Satellite Circuitry",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
            {
                "location_id": 70601005,
                "location_name": "Silo - Minimize Silo Scientist Casualties",
                "flag_address": 0x75D68,
                "flag_offset": 4,
                "requires_success": True,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 70611001,
                    "location_name": "Silo - Photograph Satellite (Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70611002,
                    "location_name": "Silo - Minimize Silo Scientist Casualties (Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": True,
                },
            ],
            2: [
                {
                    "location_id": 70621001,
                    "location_name": "Silo - Photograph Satellite (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70621002,
                    "location_name": "Silo - Obtain Telemetric Data (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70621003,
                    "location_name": "Silo - Retrieve Satellite Circuitry (Secret Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 70621004,
                    "location_name": "Silo - Minimize Silo Scientist Casualties (Secret Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": True,
                },
            ],
            3: [
                {
                    "location_id": 70631001,
                    "location_name": "Silo - Plant Bombs In Fuel Rooms (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70631002,
                    "location_name": "Silo - Photograph Satellite (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70631003,
                    "location_name": "Silo - Obtain Telemetric Data (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70631004,
                    "location_name": "Silo - Retrieve Satellite Circuitry (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 70631005,
                    "location_name": "Silo - Minimize Silo Scientist Casualties (Double Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": True,
                },
            ],
        },
    },

    ################################################# [MISSION 07] Frigate #################################################

    {
        "name": "Frigate",
        "mission_id": 10,
        "map_id": 7,
        "unlock_byte_offset": 6,
        "unlock_item_name": "Frigate",
        "unlock_item_id": 73037007,
        "starting_option_value": 7,
        "clear_location_ids": {
            1: 70710001,
            2: 70720001,
            3: 70730001,
        },
        "shared_clear_location_id": 70700001,
        "shared_objective_checks": [
            {
                "location_id": 70701001,
                "location_name": "Frigate - Rescue Hostages",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 70701002,
                "location_name": "Frigate - Disarm Bridge Bomb",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 70701003,
                "location_name": "Frigate - Disarm Engine Room Bomb",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 70701004,
                "location_name": "Frigate - Plant Tracking Bug On Helicopter",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 70711001,
                    "location_name": "Frigate - Rescue Hostages (Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70711002,
                    "location_name": "Frigate - Plant Tracking Bug On Helicopter (Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 70721001,
                    "location_name": "Frigate - Rescue Hostages (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70721002,
                    "location_name": "Frigate - Disarm Bridge Bomb (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70721003,
                    "location_name": "Frigate - Disarm Engine Room Bomb (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70721004,
                    "location_name": "Frigate - Plant Tracking Bug On Helicopter (Secret Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 70731001,
                    "location_name": "Frigate - Rescue Hostages (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70731002,
                    "location_name": "Frigate - Disarm Bridge Bomb (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70731003,
                    "location_name": "Frigate - Disarm Engine Room Bomb (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70731004,
                    "location_name": "Frigate - Plant Tracking Bug On Helicopter (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################ [MISSION 08] Surface 2 ################################################

    {
        "name": "Surface 2",
        "mission_id": 12,
        "map_id": 8,
        "unlock_byte_offset": 7,
        "unlock_item_name": "Surface 2",
        "unlock_item_id": 73037008,
        "starting_option_value": 8,
        "clear_location_ids": {
            1: 70810001,
            2: 70820001,
            3: 70830001,
        },
        "shared_clear_location_id": 70800001,
        "shared_objective_checks": [
            {
                "location_id": 70801001,
                "location_name": "Surface 2 - Disrupt All surveillance Equipment",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 70801002,
                "location_name": "Surface 2 - Break Communications Link To Bunker",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 70801003,
                "location_name": "Surface 2 - Disable Spetznaz Support Aircraft",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 70801004,
                "location_name": "Surface 2 - Gain Entry To Bunker",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 70811001,
                    "location_name": "Surface 2 - Break Communications Link To Bunker (Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70811002,
                    "location_name": "Surface 2 - Gain Entry To Bunker (Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 70821001,
                    "location_name": "Surface 2 - Break Communications Link To Bunker (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70821002,
                    "location_name": "Surface 2 - Disable Spetznaz Support Aircraft (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70821003,
                    "location_name": "Surface 2 - Gain Entry To Bunker (Secret Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 70831001,
                    "location_name": "Surface 2 - Disrupt All surveillance Equipment (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70831002,
                    "location_name": "Surface 2 - Break Communications Link To Bunker (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70831003,
                    "location_name": "Surface 2 - Disable Spetznaz Support Aircraft (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70831004,
                    "location_name": "Surface 2 - Gain Entry To Bunker (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################ [MISSION 09] Bunker 2 #################################################

    {
        "name": "Bunker 2",
        "mission_id": 13,
        "map_id": 9,
        "unlock_byte_offset": 8,
        "unlock_item_name": "Bunker 2",
        "unlock_item_id": 73037009,
        "starting_option_value": 9,
        "clear_location_ids": {
            1: 70910001,
            2: 70920001,
            3: 70930001,
        },
        "shared_clear_location_id": 70900001,
        "shared_objective_checks": [
            {
                "location_id": 70901001,
                "location_name": "Bunker 2 - Compare Staff/Casualty Lists",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 70901002,
                "location_name": "Bunker 2 - Recover CCTV Tape",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 70901003,
                "location_name": "Bunker 2 - Disable All Security Cameras",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 70901004,
                "location_name": "Bunker 2 - Recover Goldeneye Operations Manual",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
            {
                "location_id": 70901005,
                "location_name": "Bunker 2 - Escape With Natalya",
                "flag_address": 0x75D68,
                "flag_offset": 4,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 70911001,
                    "location_name": "Bunker 2 - Recover CCTV Tape (Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70911002,
                    "location_name": "Bunker 2 - Escape With Natalya (Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 70921001,
                    "location_name": "Bunker 2 - Recover CCTV Tape (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70921002,
                    "location_name": "Bunker 2 - Compare Staff/Casualty Lists (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70921003,
                    "location_name": "Bunker 2 - Disable All Security Cameras (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70921004,
                    "location_name": "Bunker 2 - Escape With Natalya (Secret Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 70931001,
                    "location_name": "Bunker 2 - Compare Staff/Casualty Lists (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 70931002,
                    "location_name": "Bunker 2 - Recover CCTV Tape (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 70931003,
                    "location_name": "Bunker 2 - Disable All Security Cameras (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 70931004,
                    "location_name": "Bunker 2 - Recover Goldeneye Operations Manual (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 70931005,
                    "location_name": "Bunker 2 - Escape With Natalya (Double Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################# [MISSION 10] Statue ##################################################

    {
        "name": "Statue",
        "mission_id": 15,
        "map_id": 10,
        "unlock_byte_offset": 9,
        "unlock_item_name": "Statue",
        "unlock_item_id": 73037010,
        "starting_option_value": 10,
        "clear_location_ids": {
            1: 71010001,
            2: 71020001,
            3: 71030001,
        },
        "shared_clear_location_id": 71000001,
        "shared_objective_checks": [
            {
                "location_id": 71001001,
                "location_name": "Statue - Contact Valentin",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 71001002,
                "location_name": "Statue - Confront And Unmask Janus",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 71001003,
                "location_name": "Statue - Locate Helicopter",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 71001004,
                "location_name": "Statue - Rescue Natalya",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
            {
                "location_id": 71001005,
                "location_name": "Statue - Find Flight Recorder",
                "flag_address": 0x75D68,
                "flag_offset": 4,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 71011001,
                    "location_name": "Statue - Contact Valentin (Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71011002,
                    "location_name": "Statue - Confront And Unmask Janus (Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71011003,
                    "location_name": "Statue - Find Flight Recorder (Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
                {
                    "location_id": 71011004,
                    "location_name": "Statue - Locate Helicopter (Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 71011005,
                    "location_name": "Statue - Rescue Natalya (Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 71021001,
                    "location_name": "Statue - Contact Valentin (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71021002,
                    "location_name": "Statue - Confront And Unmask Janus (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71021003,
                    "location_name": "Statue - Find Flight Recorder (Secret Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
                {
                    "location_id": 71021004,
                    "location_name": "Statue - Locate Helicopter (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 71021005,
                    "location_name": "Statue - Rescue Natalya (Secret Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 71031001,
                    "location_name": "Statue - Contact Valentin (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71031002,
                    "location_name": "Statue - Confront And Unmask Janus (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71031003,
                    "location_name": "Statue - Locate Helicopter (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 71031004,
                    "location_name": "Statue - Rescue Natalya (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 71031005,
                    "location_name": "Statue - Find Flight Recorder (Double Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################ [MISSION 11] Archives #################################################

    {
        "name": "Archives",
        "mission_id": 16,
        "map_id": 11,
        "unlock_byte_offset": 10,
        "unlock_item_name": "Archives",
        "unlock_item_id": 73037011,
        "starting_option_value": 11,
        "clear_location_ids": {
            1: 71110001,
            2: 71120001,
            3: 71130001,
        },
        "shared_clear_location_id": 71100001,
        "shared_objective_checks": [
            {
                "location_id": 71101001,
                "location_name": "Archives - Escape From Interrogation Room",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 71101002,
                "location_name": "Archives - Find Natalya",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 71101003,
                "location_name": "Archives - Recover Helicopter Black Box",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 71101004,
                "location_name": "Archives - Escape With Natalya Again",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 71111001,
                    "location_name": "Archives - Escape From Interrogation Room (Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71111002,
                    "location_name": "Archives - Escape With Natalya Again (Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 71111003,
                    "location_name": "Archives - Find Natalya (Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 71121001,
                    "location_name": "Archives - Escape With Natalya Again (Secret Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 71121002,
                    "location_name": "Archives - Find Natalya (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71121003,
                    "location_name": "Archives - Recover Helicopter Black Box (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 71121004,
                    "location_name": "Archives - Escape From Interrogation Room (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 71131001,
                    "location_name": "Archives - Escape From Interrogation Room (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71131002,
                    "location_name": "Archives - Find Natalya (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71131003,
                    "location_name": "Archives - Recover Helicopter Black Box (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 71131004,
                    "location_name": "Archives - Escape With Natalya Again (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################# [MISSION 12] Streets #################################################

    {
        "name": "Streets",
        "mission_id": 17,
        "map_id": 12,
        "unlock_byte_offset": 11,
        "unlock_item_name": "Streets",
        "unlock_item_id": 73037012,
        "starting_option_value": 12,
        "clear_location_ids": {
            1: 71210001,
            2: 71220001,
            3: 71230001,
        },
        "shared_clear_location_id": 71200001,
        "shared_objective_checks": [
            {
                "location_id": 71201001,
                "location_name": "Streets - Contact Valentin Again",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 71201002,
                "location_name": "Streets - Pursue Ouromov And Natalya",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 71201003,
                "location_name": "Streets - Minimize Civilian Casualties",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": True,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 71211001,
                    "location_name": "Streets - Pursue Ouromov And Natalya (Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71211002,
                    "location_name": "Streets - Minimize Civilian Casualties (Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": True,
                },
            ],
            2: [
                {
                    "location_id": 71221001,
                    "location_name": "Streets - Contact Valentin Again (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71221002,
                    "location_name": "Streets - Pursue Ouromov And Natalya (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71221003,
                    "location_name": "Streets - Minimize Civilian Casualties (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": True,
                },
            ],
            3: [
                {
                    "location_id": 71231001,
                    "location_name": "Streets - Contact Valentin Again (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71231002,
                    "location_name": "Streets - Pursue Ouromov And Natalya (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71231003,
                    "location_name": "Streets - Minimize Civilian Casualties (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": True,
                },
            ],
        },
    },

    ################################################## [MISSION 13] Depot ##################################################

    {
        "name": "Depot",
        "mission_id": 18,
        "map_id": 13,
        "unlock_byte_offset": 12,
        "unlock_item_name": "Depot",
        "unlock_item_id": 73037013,
        "starting_option_value": 13,
        "clear_location_ids": {
            1: 71310001,
            2: 71320001,
            3: 71330001,
        },
        "shared_clear_location_id": 71300001,
        "shared_objective_checks": [
            {
                "location_id": 71301001,
                "location_name": "Depot - Destroy Illegal Arms Cache",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 71301002,
                "location_name": "Depot - Destroy Computer Network",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 71301003,
                "location_name": "Depot - Obtain Depot Safe Key",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 71301004,
                "location_name": "Depot - Recover Helicopter Blueprints",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
            {
                "location_id": 71301005,
                "location_name": "Depot - Locate Trevelyn's Train",
                "flag_address": 0x75D68,
                "flag_offset": 4,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 71311001,
                    "location_name": "Depot - Locate Trevelyn's Train (Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 71321001,
                    "location_name": "Depot - Destroy Computer Network (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71321002,
                    "location_name": "Depot - Obtain Depot Safe Key (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 71321003,
                    "location_name": "Depot - Recover Helicopter Blueprints (Secret Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 71321004,
                    "location_name": "Depot - Locate Trevelyn's Train (Secret Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 71331001,
                    "location_name": "Depot - Destroy Illegal Arms Cache (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71331002,
                    "location_name": "Depot - Destroy Computer Network (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71331003,
                    "location_name": "Depot - Obtain Depot Safe Key (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 71331004,
                    "location_name": "Depot - Recover Helicopter Blueprints (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 71331005,
                    "location_name": "Depot - Locate Trevelyn's Train (Double Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################## [MISSION 14] Train ##################################################

    {
        "name": "Train",
        "mission_id": 19,
        "map_id": 14,
        "unlock_byte_offset": 13,
        "unlock_item_name": "Train",
        "unlock_item_id": 73037014,
        "starting_option_value": 14,
        "clear_location_ids": {
            1: 71410001,
            2: 71420001,
            3: 71430001,
        },
        "shared_clear_location_id": 71400001,
        "shared_objective_checks": [
            {
                "location_id": 71401001,
                "location_name": "Train - Destroy Brake Units",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 71401002,
                "location_name": "Train - Rescue Natalya Again",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 71401003,
                "location_name": "Train - Locate Janus Secret Base",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 71401004,
                "location_name": "Train - Crack Boris' Password",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
            {
                "location_id": 71401005,
                "location_name": "Train - Escape To Safety",
                "flag_address": 0x75D68,
                "flag_offset": 4,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 71411001,
                    "location_name": "Train - Destroy Brake Units (Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71411002,
                    "location_name": "Train - Rescue Natalya Again (Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71411003,
                    "location_name": "Train - Escape To Safety (Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 71421001,
                    "location_name": "Train - Destroy Brake Units (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71421002,
                    "location_name": "Train - Rescue Natalya Again (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71421003,
                    "location_name": "Train - Locate Janus Secret Base (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 71421004,
                    "location_name": "Train - Escape To Safety (Secret Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 71431001,
                    "location_name": "Train - Destroy Brake Units (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71431002,
                    "location_name": "Train - Rescue Natalya Again (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71431003,
                    "location_name": "Train - Locate Janus Secret Base (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 71431004,
                    "location_name": "Train - Crack Boris' Password (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 71431005,
                    "location_name": "Train - Escape To Safety (Double Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################# [MISSION 15] Jungle ##################################################

    {
        "name": "Jungle",
        "mission_id": 21,
        "map_id": 15,
        "unlock_byte_offset": 14,
        "unlock_item_name": "Jungle",
        "unlock_item_id": 73037015,
        "starting_option_value": 15,
        "clear_location_ids": {
            1: 71510001,
            2: 71520001,
            3: 71530001,
        },
        "shared_clear_location_id": 71500001,
        "shared_objective_checks": [
            {
                "location_id": 71501001,
                "location_name": "Jungle - Destroy Drone Guns",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 71501002,
                "location_name": "Jungle - Eliminate Xenia",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 71501003,
                "location_name": "Jungle - Blow Up Ammo Dump",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 71501004,
                "location_name": "Jungle - Escort Natalya To Janus Base",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 71511001,
                    "location_name": "Jungle - Destroy Drone Guns (Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71511002,
                    "location_name": "Jungle - Eliminate Xenia (Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71511003,
                    "location_name": "Jungle - Escort Natalya To Janus Base (Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 71521001,
                    "location_name": "Jungle - Destroy Drone Guns (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71521002,
                    "location_name": "Jungle - Eliminate Xenia (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71521003,
                    "location_name": "Jungle - Blow Up Ammo Dump (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 71521004,
                    "location_name": "Jungle - Escort Natalya To Janus Base (Secret Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 71531001,
                    "location_name": "Jungle - Destroy Drone Guns (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71531002,
                    "location_name": "Jungle - Eliminate Xenia (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71531003,
                    "location_name": "Jungle - Blow Up Ammo Dump (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 71531004,
                    "location_name": "Jungle - Escort Natalya To Janus Base (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################# [MISSION 16] Control #################################################

    {
        "name": "Control",
        "mission_id": 22,
        "map_id": 16,
        "unlock_byte_offset": 15,
        "unlock_item_name": "Control",
        "unlock_item_id": 73037016,
        "starting_option_value": 16,
        "clear_location_ids": {
            1: 71610001,
            2: 71620001,
            3: 71630001,
        },
        "shared_clear_location_id": 71600001,
        "shared_objective_checks": [
            {
                "location_id": 71601001,
                "location_name": "Control - Protect Natalya",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 71601002,
                "location_name": "Control - Disable Goldeneye Satellite",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 71601003,
                "location_name": "Control - Destroy Armored Mainframes",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 71611001,
                    "location_name": "Control - Protect Natalya (Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71611002,
                    "location_name": "Control - Disable Goldeneye Satellite (Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71611003,
                    "location_name": "Control - Destroy Armored Mainframes (Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 71621001,
                    "location_name": "Control - Protect Natalya (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71621002,
                    "location_name": "Control - Disable Goldeneye Satellite (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71621003,
                    "location_name": "Control - Destroy Armored Mainframes (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 71631001,
                    "location_name": "Control - Protect Natalya (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71631002,
                    "location_name": "Control - Disable Goldeneye Satellite (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71631003,
                    "location_name": "Control - Destroy Armored Mainframes (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################# [MISSION 17] Caverns #################################################

    {
        "name": "Caverns",
        "mission_id": 23,
        "map_id": 17,
        "unlock_byte_offset": 16,
        "unlock_item_name": "Caverns",
        "unlock_item_id": 73037017,
        "starting_option_value": 17,
        "clear_location_ids": {
            1: 71710001,
            2: 71720001,
            3: 71730001,
        },
        "shared_clear_location_id": 71700001,
        "shared_objective_checks": [
            {
                "location_id": 71701001,
                "location_name": "Caverns - Destroy Inlet Pump Controls",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 71701002,
                "location_name": "Caverns - Destroy Outlet Pump controls",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
            {
                "location_id": 71701003,
                "location_name": "Caverns - Destroy Master Control Console",
                "flag_address": 0x75D60,
                "flag_offset": 2,
                "requires_success": False,
            },
            {
                "location_id": 71701004,
                "location_name": "Caverns - Use Radio To Contact Jack Wade",
                "flag_address": 0x75D64,
                "flag_offset": 3,
                "requires_success": False,
            },
            {
                "location_id": 71701005,
                "location_name": "Caverns - Minimize Caverns Scientist Casualties",
                "flag_address": 0x75D68,
                "flag_offset": 4,
                "requires_success": True,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 71711001,
                    "location_name": "Caverns - Minimize Caverns Scientist Casualties (Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": True,
                },
            ],
            2: [
                {
                    "location_id": 71721001,
                    "location_name": "Caverns - Destroy Inlet Pump Controls (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71721002,
                    "location_name": "Caverns - Destroy Outlet Pump controls (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71721003,
                    "location_name": "Caverns - Destroy Master Control Console (Secret Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 71721004,
                    "location_name": "Caverns - Minimize Caverns Scientist Casualties (Secret Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": True,
                },
            ],
            3: [
                {
                    "location_id": 71731001,
                    "location_name": "Caverns - Destroy Inlet Pump Controls (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71731002,
                    "location_name": "Caverns - Destroy Outlet Pump controls (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
                {
                    "location_id": 71731003,
                    "location_name": "Caverns - Destroy Master Control Console (Double Agent)",
                    "flag_address": 0x75D60,
                    "flag_offset": 2,
                    "requires_success": False,
                },
                {
                    "location_id": 71731004,
                    "location_name": "Caverns - Use Radio To Contact Jack Wade (Double Agent)",
                    "flag_address": 0x75D64,
                    "flag_offset": 3,
                    "requires_success": False,
                },
                {
                    "location_id": 71731005,
                    "location_name": "Caverns - Minimize Caverns Scientist Casualties (Double Agent)",
                    "flag_address": 0x75D68,
                    "flag_offset": 4,
                    "requires_success": True,
                },
            ],
        },
    },

    ################################################# [MISSION 18] Cradle ##################################################

    {
        "name": "Cradle",
        "mission_id": 24,
        "map_id": 18,
        "unlock_byte_offset": 17,
        "unlock_item_name": "Cradle",
        "unlock_item_id": 73037018,
        "starting_option_value": 18,
        "clear_location_ids": {
            1: 71810001,
            2: 71820001,
            3: 71830001,
        },
        "shared_clear_location_id": 71800001,
        "shared_objective_checks": [
            {
                "location_id": 71801001,
                "location_name": "Cradle - Destroy Control Console",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 71801002,
                "location_name": "Cradle - Settle The Score With Trevelyan",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 71811001,
                    "location_name": "Cradle - Destroy Control Console (Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71811002,
                    "location_name": "Cradle - Settle The Score With Trevelyan (Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 71821001,
                    "location_name": "Cradle - Destroy Control Console (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71821002,
                    "location_name": "Cradle - Settle The Score With Trevelyan (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 71831001,
                    "location_name": "Cradle - Destroy Control Console (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71831002,
                    "location_name": "Cradle - Settle The Score With Trevelyan (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################## [MISSION 19] Aztec ##################################################

    {
        "name": "Aztec",
        "mission_id": 26,
        "map_id": 19,
        "unlock_byte_offset": 18,
        "unlock_item_name": "Aztec",
        "unlock_item_id": 73037019,
        "starting_option_value": 19,
        "clear_location_ids": {
            1: 71910001,
            2: 71920001,
            3: 71930001,
        },
        "shared_clear_location_id": 71900001,
        "shared_objective_checks": [
            {
                "location_id": 71901001,
                "location_name": "Aztec - Reprogram Shuttle Guidance",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 71901002,
                "location_name": "Aztec - Launch Shuttle",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 71911001,
                    "location_name": "Aztec - Reprogram Shuttle Guidance (Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71911002,
                    "location_name": "Aztec - Launch Shuttle (Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 71921001,
                    "location_name": "Aztec - Reprogram Shuttle Guidance (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71921002,
                    "location_name": "Aztec - Launch Shuttle (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 71931001,
                    "location_name": "Aztec - Reprogram Shuttle Guidance (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 71931002,
                    "location_name": "Aztec - Launch Shuttle (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
            ],
        },
    },

    ################################################ [MISSION 20] Egyptian #################################################

    {
        "name": "Egyptian",
        "mission_id": 28,
        "map_id": 20,
        "unlock_byte_offset": 19,
        "unlock_item_name": "Egyptian",
        "unlock_item_id": 73037020,
        "starting_option_value": 20,
        "clear_location_ids": {
            1: 72010001,
            2: 72020001,
            3: 72030001,
        },
        "shared_clear_location_id": 72000001,
        "shared_objective_checks": [
            {
                "location_id": 72001001,
                "location_name": "Egyptian - Recover the Golden Gun",
                "flag_address": 0x75D58,
                "flag_offset": 0,
                "requires_success": False,
            },
            {
                "location_id": 72001002,
                "location_name": "Egyptian - Defeat Baron Samedi?",
                "flag_address": 0x75D5C,
                "flag_offset": 1,
                "requires_success": False,
            },
        ],
        "objective_checks_per_difficulty": {
            1: [
                {
                    "location_id": 72011001,
                    "location_name": "Egyptian - Recover the Golden Gun (Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 72011002,
                    "location_name": "Egyptian - Defeat Baron Samedi? (Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
            ],
            2: [
                {
                    "location_id": 72021001,
                    "location_name": "Egyptian - Recover the Golden Gun (Secret Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 72021002,
                    "location_name": "Egyptian - Defeat Baron Samedi? (Secret Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
            ],
            3: [
                {
                    "location_id": 72031001,
                    "location_name": "Egyptian - Recover the Golden Gun (Double Agent)",
                    "flag_address": 0x75D58,
                    "flag_offset": 0,
                    "requires_success": False,
                },
                {
                    "location_id": 72031002,
                    "location_name": "Egyptian - Defeat Baron Samedi? (Double Agent)",
                    "flag_address": 0x75D5C,
                    "flag_offset": 1,
                    "requires_success": False,
                },
            ],
        },
    },
]

#----------------------------------------------------------------------------------------------------------------------#
################################################## [MISSION LOOKUPS] ###################################################
#----------------------------------------------------------------------------------------------------------------------#

MISSION_BY_NAME = {}
MISSION_BY_MAP_ID = {}
MISSION_BY_ID = {}
MISSION_BY_UNLOCK_ITEM_ID = {}
MISSION_BY_STARTING_OPTION_VALUE = {}

for mission in MISSIONS:
    MISSION_BY_NAME[mission["name"]] = mission
    MISSION_BY_MAP_ID[mission["map_id"]] = mission
    MISSION_BY_ID[mission["mission_id"]] = mission
    MISSION_BY_UNLOCK_ITEM_ID[mission["unlock_item_id"]] = mission
    MISSION_BY_STARTING_OPTION_VALUE[mission["starting_option_value"]] = mission

########################################################################################################################
######################################### [SECTION 2] Item Effect Definitions ##########################################
########################################################################################################################

ITEM_EFFECT_DEFS = {
}

