# Auto-generated by codegen.py — do not edit manually
# Generated: 2026-04-24 21:28:32
# Generated file exception:
# This file is machine-written from sheet data, so it may use compact Python.
# We keep the sheet-driven structure here because codegen.py rebuilds it.
# This is safe because codegen.py rebuilds this file from the same source data.

from typing import TYPE_CHECKING, Dict, List
from BaseClasses import Item, ItemClassification
from .Locations import EXTRA_MISSION_NAMES, get_enabled_extra_missions, get_total_locations
from .Types import GoldeneyeItem, ItemData

if TYPE_CHECKING:
    from . import GoldeneyeWorld


PROGRESSIVE_GUN_ITEM_NAMES = [
    'Klobb',
    'Hunting Knife',
    'Throwing Knife',
    'Taser',
    'PP7 Special Issue',
    'PP7 (Silenced)',
    'DD44 Dostovei',
    'KF7 Soviet',
    'ZMG (9 mm)',
    'D5K Deutsche',
    'D5K (Silenced)',
    'Sniper Rifle',
    'Grenade',
    'Phantom',
    'Timed Mine',
    'AR33 Assault Rifle',
    'Proximity Mine',
    'RC-P90',
    'Remote Mine',
    'Watch Laser',
    'Shotgun',
    'Cougar Magnum',
    'Silver PP7',
    'Automatic Shotgun',
    'Military Laser',
    'Grenade Launcher',
    'Rocket Launcher',
    'Tank (Missiles)',
    'Golden Gun',
    'Gold PP7',
]
PROGRESSIVE_GUN_ITEM_NAME = 'Progressive Weapon'


def create_itempool(world: "GoldeneyeWorld") -> List[Item]:
    itempool: List[Item] = []

    enabled_extra_missions = get_enabled_extra_missions(world)
    progressive_guns = world.options.progressive_weapons.value == 1
    starting_unlock = MISSION_UNLOCK_NAMES[world.options.starting_mission.value - 1]
    for name in goldeneye_unlocks:
        if name == starting_unlock:
            continue
        if name in EXTRA_MISSION_NAMES and name not in enabled_extra_missions:
            continue
        itempool.append(create_item(world, name))

    for name, data in goldeneye_pool_items.items():
        if name == PROGRESSIVE_GUN_ITEM_NAME:
            continue
        if progressive_guns and name in PROGRESSIVE_GUN_ITEM_NAMES:
            continue
        if data.count > 0:
            itempool.extend(create_multiple_items(world, name, data.count, data.classification))

    if progressive_guns:
        itempool.extend(create_multiple_items(
            world,
            PROGRESSIVE_GUN_ITEM_NAME,
            len(PROGRESSIVE_GUN_ITEM_NAMES),
            ItemClassification.progression,
        ))

    victory = create_item(world, "Victory")
    world.multiworld.get_location("Stopped Goldeneye", world.player).place_locked_item(victory)

    itempool.extend(create_junk_items(world, get_total_locations(world) - len(itempool) - 1))

    return itempool


def create_item(world: "GoldeneyeWorld", name: str) -> Item:
    data = item_table[name]
    return GoldeneyeItem(name, data.classification, data.ap_code, world.player)


def create_multiple_items(
    world: "GoldeneyeWorld",
    name: str,
    count: int,
    item_type: ItemClassification = ItemClassification.progression,
) -> List[Item]:
    data = item_table[name]
    return [GoldeneyeItem(name, item_type, data.ap_code, world.player) for _ in range(count)]


def create_junk_items(world: "GoldeneyeWorld", count: int) -> List[Item]:
    trap_chance = world.options.trap_chance.value
    junk_pool: List[Item] = []
    junk_list: Dict[str, int] = {}
    trap_list: Dict[str, int] = {}

    for name, data in item_table.items():
        if data.classification == ItemClassification.filler:
            junk_list[name] = junk_weights.get(name, 1)
        elif trap_chance > 0 and data.classification == ItemClassification.trap:
            if name == "Goldeneye Trap":
                option = getattr(world.options, "goldeneye_trap", None)
                trap_weight = option.value if option is not None else 0
            elif name == "Enemy Rockets Trap":
                option = getattr(world.options, "enemy_rockets_trap", None)
                trap_weight = option.value if option is not None else 0
            elif name == "Holster Gun Trap":
                option = getattr(world.options, "holster_gun_trap", None)
                trap_weight = option.value if option is not None else 0
            else:
                trap_weight = 0
            if trap_weight > 0:
                trap_list[name] = trap_weight

    for _ in range(count):
        pool = (
            trap_list
            if trap_list and sum(trap_list.values()) > 0 and trap_chance > 0 and world.random.randint(1, 100) <= trap_chance
            else junk_list
        )
        junk_pool.append(
            world.create_item(
                world.random.choices(list(pool), weights=list(pool.values()), k=1)[0]
            )
        )

    return junk_pool


MISSION_UNLOCK_NAMES = [
    "Dam", "Facility", "Runway", "Surface 1", "Bunker 1",
    "Silo", "Frigate", "Surface 2", "Bunker 2", "Statue",
    "Archives", "Streets", "Depot", "Train", "Jungle",
    "Control", "Caverns", "Cradle", "Aztec", "Egyptian",
]

goldeneye_unlocks = {
    "Dam":                     ItemData(73037001, ItemClassification.progression),
    "Facility":                ItemData(73037002, ItemClassification.progression),
    "Runway":                  ItemData(73037003, ItemClassification.progression),
    "Surface 1":               ItemData(73037004, ItemClassification.progression),
    "Bunker 1":                ItemData(73037005, ItemClassification.progression),
    "Silo":                    ItemData(73037006, ItemClassification.progression),
    "Frigate":                 ItemData(73037007, ItemClassification.progression),
    "Surface 2":               ItemData(73037008, ItemClassification.progression),
    "Bunker 2":                ItemData(73037009, ItemClassification.progression),
    "Statue":                  ItemData(73037010, ItemClassification.progression),
    "Archives":                ItemData(73037011, ItemClassification.progression),
    "Streets":                 ItemData(73037012, ItemClassification.progression),
    "Depot":                   ItemData(73037013, ItemClassification.progression),
    "Train":                   ItemData(73037014, ItemClassification.progression),
    "Jungle":                  ItemData(73037015, ItemClassification.progression),
    "Control":                 ItemData(73037016, ItemClassification.progression),
    "Caverns":                 ItemData(73037017, ItemClassification.progression),
    "Cradle":                  ItemData(73037018, ItemClassification.progression),
    "Aztec":                   ItemData(73037019, ItemClassification.progression),
    "Egyptian":                ItemData(73037020, ItemClassification.progression),
}

goldeneye_pool_items = {
    "Progressive Weapon":      ItemData(17310000, ItemClassification.progression, 1),
    "Klobb":                   ItemData(17310001, ItemClassification.useful, 1),
    "Hunting Knife":           ItemData(17310002, ItemClassification.useful, 1),
    "Throwing Knife":          ItemData(17310003, ItemClassification.useful, 1),
    "Taser":                   ItemData(17310004, ItemClassification.useful, 1),
    "PP7 Special Issue":       ItemData(17310005, ItemClassification.useful, 1),
    "PP7 (Silenced)":          ItemData(17310006, ItemClassification.progression, 1),
    "DD44 Dostovei":           ItemData(17310007, ItemClassification.useful, 1),
    "KF7 Soviet":              ItemData(17310008, ItemClassification.useful, 1),
    "ZMG (9 mm)":              ItemData(17310009, ItemClassification.useful, 1),
    "D5K Deutsche":            ItemData(17310010, ItemClassification.useful, 1),
    "D5K (Silenced)":          ItemData(17310011, ItemClassification.useful, 1),
    "Sniper Rifle":            ItemData(17310012, ItemClassification.useful, 1),
    "Grenade":                 ItemData(17310013, ItemClassification.useful, 1),
    "Phantom":                 ItemData(17310014, ItemClassification.useful, 1),
    "Timed Mine":              ItemData(17310015, ItemClassification.progression, 1),
    "AR33 Assault Rifle":      ItemData(17310016, ItemClassification.useful, 1),
    "Proximity Mine":          ItemData(17310017, ItemClassification.progression, 1),
    "RC-P90":                  ItemData(17310018, ItemClassification.useful, 1),
    "Remote Mine":             ItemData(17310019, ItemClassification.progression, 1),
    "Watch Laser":             ItemData(17310020, ItemClassification.progression, 1),
    "Shotgun":                 ItemData(17310021, ItemClassification.useful, 1),
    "Cougar Magnum":           ItemData(17310022, ItemClassification.useful, 1),
    "Silver PP7":              ItemData(17310023, ItemClassification.useful, 1),
    "Automatic Shotgun":       ItemData(17310024, ItemClassification.useful, 1),
    "Military Laser":          ItemData(17310025, ItemClassification.useful, 1),
    "Grenade Launcher":        ItemData(17310026, ItemClassification.progression, 1),
    "Rocket Launcher":         ItemData(17310027, ItemClassification.progression, 1),
    "Tank (Missiles)":         ItemData(17310028, ItemClassification.progression, 1),
    "Golden Gun":              ItemData(17310029, ItemClassification.progression, 1),
    "Gold PP7":                ItemData(17310030, ItemClassification.useful, 1),
    "Health Pack":             ItemData(17320000, ItemClassification.filler, 0),
    "Body Armor":              ItemData(17320001, ItemClassification.filler, 0),
    "9mm Ammo":                ItemData(17320002, ItemClassification.filler, 0),
    "Rifle Ammo":              ItemData(17320003, ItemClassification.filler, 0),
    "Shotgun Shells":          ItemData(17320004, ItemClassification.filler, 0),
    "Magnum Rounds":           ItemData(17320005, ItemClassification.filler, 0),
    "Golden Bullets":          ItemData(17320006, ItemClassification.filler, 0),
    "Grenade Rounds":          ItemData(17320007, ItemClassification.filler, 0),
    "Rockets":                 ItemData(17320008, ItemClassification.filler, 0),
    "Covert Modem (Dam Loadout)": ItemData(17330000, ItemClassification.progression, 1),
    "Door Decoder (Facility Item)": ItemData(17330001, ItemClassification.progression, 1),
    "Key Analyzer Case (Bunker 1 Loadout)": ItemData(17330002, ItemClassification.progression, 1),
    "Datathief (Bunker 1 Loadout)": ItemData(17330003, ItemClassification.progression, 1),
    "Camera (Bunker 1 / Silo Loadout)": ItemData(17330004, ItemClassification.progression, 1),
    "Plastique (Silo Loadout)": ItemData(17330005, ItemClassification.progression, 1),
    "Tracker Bug (Frigate Loadout)": ItemData(17330006, ItemClassification.progression, 1),
    "Bomb Defuser (Frigate Loadout)": ItemData(17330007, ItemClassification.progression, 1),
    "Special Timed Mine (Surface 2 Loadout)": ItemData(17330008, ItemClassification.progression, 1),
    "Watch Magnet (Bunker 2 / Archives Loadout)": ItemData(17330009, ItemClassification.progression, 1),
    "Keycard A (Facility Item)": ItemData(17330011, ItemClassification.progression, 1),
    "Keycard B (Facility Item)": ItemData(17330012, ItemClassification.progression, 1),
    "Ignition Key (Runway Item)": ItemData(17330013, ItemClassification.progression, 1),
    "Hut Door Key (Surface 1 Item)": ItemData(17330014, ItemClassification.progression, 1),
    "Safe Key (Surface 1 Item)": ItemData(17330015, ItemClassification.progression, 1),
    "Building Plans (Surface 1 Item)": ItemData(17330016, ItemClassification.progression, 1),
    "Computer Room Keycard (Bunker 1 Item)": ItemData(17330017, ItemClassification.progression, 1),
    "Security Room Keycard (Bunker 1 Item)": ItemData(17330018, ItemClassification.progression, 1),
    "Goldeneye Key (Bunker 1 Item)": ItemData(17330019, ItemClassification.progression, 1),
    "I/O Circuit Board (Silo Item)": ItemData(17330020, ItemClassification.progression, 1),
    "CPU Circuit Board (Silo Item)": ItemData(17330021, ItemClassification.progression, 1),
    "RSP Circuit Board (Silo Item)": ItemData(17330022, ItemClassification.progression, 1),
    "RDP Circuit Board (Silo Item)": ItemData(17330023, ItemClassification.progression, 1),
    "Keycard Level 1 (Silo Item)": ItemData(17330024, ItemClassification.progression, 1),
    "Keycard Level 2 (Silo Item)": ItemData(17330025, ItemClassification.progression, 1),
    "Keycard Level 3 (Silo Item)": ItemData(17330026, ItemClassification.progression, 1),
    "DAT (Silo Item)":         ItemData(17330027, ItemClassification.progression, 1),
    "Comms Room Key (Surface 2 Item)": ItemData(17330028, ItemClassification.progression, 1),
    "Cell Key 1 (Bunker 2 Item)": ItemData(17330029, ItemClassification.progression, 1),
    "Cell Key 2 (Bunker 2 Item)": ItemData(17330030, ItemClassification.progression, 1),
    "CCTV Tape (Bunker 2 Item)": ItemData(17330031, ItemClassification.progression, 1),
    "Staff List (Bunker 2 Item)": ItemData(17330032, ItemClassification.progression, 1),
    "Casualty List (Bunker 2 Item)": ItemData(17330033, ItemClassification.progression, 1),
    "Goldeneye Operations Manual (Bunker 2 Item)": ItemData(17330034, ItemClassification.progression, 1),
    "Keycard A (Bunker 2 Item)": ItemData(17330035, ItemClassification.progression, 1),
    "Keycard B (Bunker 2 Item)": ItemData(17330036, ItemClassification.progression, 1),
    "Safe Key 1 (Bunker 2 Item)": ItemData(17330037, ItemClassification.progression, 1),
    "Safe Key 2 (Bunker 2 Item)": ItemData(17330038, ItemClassification.progression, 1),
    "Flight Recorder (Archives Item)": ItemData(17330039, ItemClassification.progression, 1),
    "Interrogation Room Key (Archives Item)": ItemData(17330040, ItemClassification.progression, 1),
    "Archives Safe Key (Archives Item)": ItemData(17330041, ItemClassification.progression, 1),
    "Depot Safe Key (Depot Item)": ItemData(17330042, ItemClassification.progression, 1),
    "Blueprints (Depot Item)": ItemData(17330043, ItemClassification.progression, 1),
    "Train Door Key (Depot Item)": ItemData(17330044, ItemClassification.progression, 1),
    "Code Card 1 (Caverns Item)": ItemData(17330045, ItemClassification.progression, 1),
    "Code Card 2 (Caverns Item)": ItemData(17330046, ItemClassification.progression, 1),
    "Code Card 3 (Caverns Item)": ItemData(17330047, ItemClassification.progression, 1),
    "Guidance Data (Aztec Item)": ItemData(17330048, ItemClassification.progression, 1),
    "Security Smart Card (Aztec Item)": ItemData(17330049, ItemClassification.progression, 1),
    "Launch Protocol Data (Aztec Item)": ItemData(17330050, ItemClassification.progression, 1),
    "Goldeneye Trap":          ItemData(17350000, ItemClassification.trap, 0),
}

junk_weights = {
    "Health Pack": 60,
    "Body Armor": 60,
    "9mm Ammo": 60,
    "Rifle Ammo": 60,
    "Shotgun Shells": 60,
    "Magnum Rounds": 60,
    "Golden Bullets": 60,
    "Grenade Rounds": 60,
    "Rockets": 60,
}

goldeneye_events = {
    "Victory": ItemData(17390000, ItemClassification.progression),
}

item_table = {
    **goldeneye_unlocks,
    **goldeneye_pool_items,
    **goldeneye_events,
}
