from typing import Dict, TYPE_CHECKING
from .Types import LocData
from .client_data import MISSIONS

CHEAT_LOCATION_IDS = {mission["cheat_unlock_check"]["location_id"] for mission in MISSIONS
                      if "cheat_unlock_check" in mission}

if TYPE_CHECKING:
    from . import GoldeneyeWorld

MISSION_CLEAR_MODE_PER_MAP = 2
MISSION_CLEAR_MODE_PER_DIFFICULTY = 1
OBJECTIVE_MODE_PER_DIFFICULTY = 1
OBJECTIVE_MODE_SHARED = 2
ITEM_SHUFFLE_MODE_SHARED = 2
ITEM_SHUFFLE_MODE_PER_DIFFICULTY = 1
EXTRA_MISSION_NAMES = ('Aztec', 'Egyptian')
EXTRA_MISSION_REGIONS = EXTRA_MISSION_NAMES
EXTRA_MISSION_SELECTIONS = {
    1: {"Aztec"},
    2: {"Egyptian"},
    3: {"Aztec", "Egyptian"},
    4: {},
}


def get_enabled_extra_missions(world: "GoldeneyeWorld") -> set[str]:
    return EXTRA_MISSION_SELECTIONS[world.options.extra_locations.value]


def is_enabled_extra_region(world: "GoldeneyeWorld", region_name: str) -> bool:
    return (
        region_name not in EXTRA_MISSION_REGIONS
        or region_name in get_enabled_extra_missions(world)
    )


def get_item_shuffle_mode(world: "GoldeneyeWorld") -> int:
    item_shuffle = getattr(world.options, "item_shuffle", None)
    if item_shuffle is None:
        return ITEM_SHUFFLE_MODE_SHARED
    return item_shuffle.value


def get_total_locations(world: "GoldeneyeWorld") -> int:
    return sum(
        1
        for name, data in location_table.items()
        if name not in event_locations
        and is_enabled_extra_region(world, data.region)
        and is_valid_location(world, name)
    )


def get_location_names() -> Dict[str, int]:
    return {name: data.ap_code for name, data in location_table.items() if data.ap_code is not None}


def is_valid_location(world: "GoldeneyeWorld", name: str) -> bool:
    if not is_enabled_extra_region(world, location_table[name].region):
        return False
    if location_table[name].ap_code in CHEAT_LOCATION_IDS and not world.options.cheat_shuffler.value:
        return False
    if name in ('Archives - Body Armor (Bottom Floor On Crate)', 'Archives - Body Armor (Bottom Floor On Crate) (Agent)', 'Archives - Body Armor (Room Across From Start)', 'Archives - Body Armor (Room Across From Start) (Agent)', 'Archives - Body Armor (Room Across From Start) (Secret Agent)', 'Aztec - Body Armor (Inside Turret Tunnels)', 'Aztec - Body Armor (Inside Turret Tunnels) (Agent)', 'Aztec - Body Armor (Inside Turret Tunnels) (Double Agent)', 'Aztec - Body Armor (Inside Turret Tunnels) (Secret Agent)', 'Bunker 1 - Body Armor (Kitchen)', 'Bunker 1 - Body Armor (Kitchen) (Agent)', 'Bunker 1 - Body Armor (Rear Tunnel)', 'Bunker 1 - Body Armor (Rear Tunnel) (Agent)', 'Bunker 1 - Body Armor (Rear Tunnel) (Secret Agent)', 'Bunker 2 - Body Armor (Auto Turret Tunnel)', 'Bunker 2 - Body Armor (Auto Turret Tunnel) (Agent)', 'Bunker 2 - Body Armor (Shooting Range)', 'Bunker 2 - Body Armor (Shooting Range) (Agent)', 'Bunker 2 - Body Armor (Shooting Range) (Secret Agent)', 'Caverns - Body Armor (Comms Room)', 'Caverns - Body Armor (Comms Room) (Agent)', 'Caverns - Body Armor (Comms Room) (Secret Agent)', 'Caverns - Body Armor (Under Walkway On Crate)', 'Caverns - Body Armor (Under Walkway On Crate) (Agent)', 'Control - Body Armor (Locker Room Corner)', 'Control - Body Armor (Locker Room Corner) (Agent)', 'Control - Body Armor (Locker Room Corner) (Double Agent)', 'Control - Body Armor (Locker Room Corner) (Secret Agent)', 'Control - Body Armor (Top Floor Behind Grate)', 'Control - Body Armor (Top Floor Behind Grate) (Agent)', 'Control - Body Armor (Top Floor Behind Grate) (Double Agent)', 'Control - Body Armor (Top Floor Behind Grate) (Secret Agent)', 'Cradle - Body Armor (Behind Antenna Control)', 'Cradle - Body Armor (Behind Antenna Control) (Agent)', 'Cradle - Body Armor (Behind Antenna Control) (Double Agent)', 'Cradle - Body Armor (Behind Antenna Control) (Secret Agent)', 'Cradle - Body Armor (Left Tower)', 'Cradle - Body Armor (Left Tower) (Agent)', 'Cradle - Body Armor (Left Tower) (Double Agent)', 'Cradle - Body Armor (Left Tower) (Secret Agent)', 'Cradle - Body Armor (Right Tower)', 'Cradle - Body Armor (Right Tower) (Agent)', 'Cradle - Body Armor (Right Tower) (Double Agent)', 'Cradle - Body Armor (Right Tower) (Secret Agent)', 'Cradle - Body Armor (Start Tower)', 'Cradle - Body Armor (Start Tower) (Agent)', 'Cradle - Body Armor (Start Tower) (Double Agent)', 'Cradle - Body Armor (Start Tower) (Secret Agent)', 'Dam - Body Armor (Guard Tower 2)', 'Dam - Body Armor (Guard Tower 2) (Agent)', 'Dam - Body Armor (Last Dam Tower)', 'Dam - Body Armor (Last Dam Tower) (Agent)', 'Dam - Body Armor (Last Dam Tower) (Secret Agent)', 'Depot - Body Armor (Back Corner Behind Crates Just Before Train Station Gate)', 'Depot - Body Armor (Back Corner Behind Crates Just Before Train Station Gate) (Agent)', 'Depot - Body Armor (Back Left Corner Three Door Hangar)', 'Depot - Body Armor (Back Left Corner Three Door Hangar) (Agent)', 'Depot - Body Armor (Back Left Corner Three Door Hangar) (Secret Agent)', 'Depot - Body Armor (Back of Blue Hangar Near Start)', 'Depot - Body Armor (Back of Blue Hangar Near Start) (Agent)', 'Depot - Body Armor (Back of Blue Hangar Near Start) (Secret Agent)', 'Depot - Body Armor (Back of Grey Hangar Near Start)', 'Depot - Body Armor (Back of Grey Hangar Near Start) (Agent)', 'Depot - Body Armor (Back of Grey Hangar Near Start) (Secret Agent)', 'Depot - Body Armor (Back of Hangar Across from Ammo Cache)', 'Depot - Body Armor (Back of Hangar Across from Ammo Cache) (Agent)', 'Depot - Body Armor (Back of Last Hangar On Middle Road)', 'Depot - Body Armor (Back of Last Hangar On Middle Road) (Agent)', 'Depot - Body Armor (Back of Last Hangar On Middle Road) (Secret Agent)', 'Depot - Body Armor (Back of Last Hangar)', 'Depot - Body Armor (Back of Last Hangar) (Agent)', 'Depot - Body Armor (Back of Last Hangar) (Secret Agent)', 'Depot - Body Armor (Behind Crate In Front of Start)', 'Depot - Body Armor (Behind Crate In Front of Start) (Agent)', 'Depot - Body Armor (Inside Train Station)', 'Depot - Body Armor (Inside Train Station) (Agent)', 'Depot - Body Armor (Outside Behind Crate Under Orange Pipe)', 'Depot - Body Armor (Outside Behind Crate Under Orange Pipe) (Agent)', 'Depot - Body Armor (Outside Behind Crate Under Orange Pipe) (Secret Agent)', 'Depot - Body Armor (Outside Behind House Left of Blue Hangar Near Start)', 'Depot - Body Armor (Outside Behind House Left of Blue Hangar Near Start) (Agent)', 'Depot - Body Armor (Outside Behind Stacked Crates Right of Start)', 'Depot - Body Armor (Outside Behind Stacked Crates Right of Start) (Agent)', 'Egyptian - Body Armor (After Golden Gun)', 'Egyptian - Body Armor (After Golden Gun) (Agent)', 'Egyptian - Body Armor (After Golden Gun) (Double Agent)', 'Egyptian - Body Armor (After Golden Gun) (Secret Agent)', 'Egyptian - Body Armor (Corridor North West of Start)', 'Egyptian - Body Armor (Corridor North West of Start) (Agent)', 'Egyptian - Body Armor (Corridor North West of Start) (Double Agent)', 'Egyptian - Body Armor (Corridor North West of Start) (Secret Agent)', 'Egyptian - Body Armor (Left of Secret Corridor)', 'Egyptian - Body Armor (Left of Secret Corridor) (Agent)', 'Egyptian - Body Armor (Left of Secret Corridor) (Double Agent)', 'Egyptian - Body Armor (Left of Secret Corridor) (Secret Agent)', 'Facility - Body Armor (Inside Security Room 2)', 'Facility - Body Armor (Inside Security Room 2) (Agent)', 'Facility - Body Armor (On Hallway Crate)', 'Facility - Body Armor (On Hallway Crate) (Agent)', 'Facility - Body Armor (On Hallway Crate) (Secret Agent)', 'Frigate - Body Armor (Invisable on Crate in Cargo Hold)', 'Frigate - Body Armor (Invisable on Crate in Cargo Hold) (Agent)', 'Frigate - Body Armor (Radio Room)', 'Frigate - Body Armor (Radio Room) (Agent)', 'Frigate - Body Armor (Radio Room) (Secret Agent)', 'Jungle - Body Armor (Behind Guard Tower)', 'Jungle - Body Armor (Behind Guard Tower) (Agent)', 'Jungle - Body Armor (Behind Guard Tower) (Secret Agent)', 'Jungle - Body Armor (Behind Second Turret)', 'Jungle - Body Armor (Behind Second Turret) (Agent)', 'Jungle - Body Armor (Behind Second Turret) (Double Agent)', 'Jungle - Body Armor (Behind Second Turret) (Secret Agent)', 'Jungle - Body Armor (First Area Back Corner)', 'Jungle - Body Armor (First Area Back Corner) (Agent)', 'Jungle - Body Armor (First Area Back Corner) (Double Agent)', 'Jungle - Body Armor (First Area Back Corner) (Secret Agent)', 'Silo - Body Armor (Fourth Fuel Room)', 'Silo - Body Armor (Fourth Fuel Room) (Agent)', 'Silo - Body Armor (Fourth Fuel Room) (Secret Agent)', 'Silo - Body Armor (Second Fuel Room)', 'Silo - Body Armor (Second Fuel Room) (Agent)', 'Silo - Body Armor (Walkway After Third Fuel Room)', 'Silo - Body Armor (Walkway After Third Fuel Room) (Agent)', 'Silo - Body Armor (Walkway After Third Fuel Room) (Double Agent)', 'Silo - Body Armor (Walkway After Third Fuel Room) (Secret Agent)', 'Statue - Body Armor (Near Hand)', 'Statue - Body Armor (Near Hand) (Agent)', 'Statue - Body Armor (Near Hand) (Double Agent)', 'Statue - Body Armor (Near Hand) (Secret Agent)', 'Streets - Body Armor (Ending Left Side Checkpoint)', 'Streets - Body Armor (Ending Left Side Checkpoint) (Agent)', 'Streets - Body Armor (Ending Left Side Checkpoint) (Double Agent)', 'Streets - Body Armor (Ending Left Side Checkpoint) (Secret Agent)', 'Streets - Body Armor (Ending Right Side Checkpoint)', 'Streets - Body Armor (Ending Right Side Checkpoint) (Agent)', 'Streets - Body Armor (Ending Right Side Checkpoint) (Double Agent)', 'Streets - Body Armor (Ending Right Side Checkpoint) (Secret Agent)', 'Streets - Body Armor (Mid Level Checkpoint)', 'Streets - Body Armor (Mid Level Checkpoint) (Agent)', 'Streets - Body Armor (Mid Level Checkpoint) (Double Agent)', 'Streets - Body Armor (Mid Level Checkpoint) (Secret Agent)', 'Streets - Body Armor (Through Window Past Valentin)', 'Streets - Body Armor (Through Window Past Valentin) (Agent)', 'Streets - Body Armor (Through Window Past Valentin) (Double Agent)', 'Streets - Body Armor (Through Window Past Valentin) (Secret Agent)', 'Surface 2 - Body Armor (Cabin With Camera)', 'Surface 2 - Body Armor (Cabin With Camera) (Agent)', 'Surface 2 - Body Armor (Fenced Area Cabin)', 'Surface 2 - Body Armor (Fenced Area Cabin) (Agent)'):
        mode = world.options.body_armor_sanity.value
        if name in per_difficulty_item_locations:
            return mode == ITEM_SHUFFLE_MODE_PER_DIFFICULTY
        return mode == ITEM_SHUFFLE_MODE_SHARED
    if name in ('Bunker 1 - Ammo Container - Rifle Ammo - Room In Front of Start', 'Bunker 1 - Ammo Container - Rifle Ammo - Room In Front of Start (Agent)', 'Bunker 1 - Ammo Container - Rifle Ammo - Room In Front of Start (Double Agent)', 'Bunker 1 - Ammo Container - Rifle Ammo - Room In Front of Start (Secret Agent)', 'Control - Ammo Container - Remote Mines - After First Blast Door', 'Control - Ammo Container - Remote Mines - After First Blast Door (Agent)', 'Control - Ammo Container - Remote Mines - After First Blast Door (Double Agent)', 'Control - Ammo Container - Remote Mines - After First Blast Door (Secret Agent)', 'Depot - Proximity Mines', 'Depot - Proximity Mines (Agent)', 'Depot - Proximity Mines (Double Agent)', 'Depot - Proximity Mines (Secret Agent)', 'Depot - Rockets 1', 'Depot - Rockets 1 (Agent)', 'Depot - Rockets 1 (Double Agent)', 'Depot - Rockets 1 (Secret Agent)', 'Depot - Rockets 2', 'Depot - Rockets 2 (Agent)', 'Depot - Rockets 2 (Double Agent)', 'Depot - Rockets 2 (Secret Agent)', 'Depot - Rockets 3', 'Depot - Rockets 3 (Agent)', 'Depot - Rockets 3 (Double Agent)', 'Depot - Rockets 3 (Secret Agent)', 'Egyptian - Golden Gun Ammo', 'Egyptian - Golden Gun Ammo (Agent)', 'Egyptian - Golden Gun Ammo (Double Agent)', 'Egyptian - Golden Gun Ammo (Secret Agent)', 'Runway - Ammo Container - Hand Grenades - Next To Player Start', 'Runway - Ammo Container - Hand Grenades - Next To Player Start (Agent)', 'Runway - Ammo Container - Hand Grenades - Next To Player Start (Double Agent)', 'Runway - Ammo Container - Hand Grenades - Next To Player Start (Secret Agent)', 'Runway - Ammo Container - Hand Grenades - Outside Ignition Key Building', 'Runway - Ammo Container - Hand Grenades - Outside Ignition Key Building (Agent)', 'Runway - Ammo Container - Hand Grenades - Outside Ignition Key Building (Double Agent)', 'Runway - Ammo Container - Hand Grenades - Outside Ignition Key Building (Secret Agent)', 'Runway - Ammo Container - Timed Mines - Room Behind Start', 'Runway - Ammo Container - Timed Mines - Room Behind Start (Agent)', 'Runway - Ammo Container - Timed Mines - Room Behind Start (Double Agent)', 'Runway - Ammo Container - Timed Mines - Room Behind Start (Secret Agent)', 'Streets - Ammo Container - Grenade Rounds - (Through Window Past Valentin)', 'Streets - Ammo Container - Grenade Rounds - (Through Window Past Valentin) (Agent)', 'Streets - Ammo Container - Grenade Rounds - (Through Window Past Valentin) (Double Agent)', 'Streets - Ammo Container - Grenade Rounds - (Through Window Past Valentin) (Secret Agent)', 'Surface 1 - Ammo Container - Grenade Rounds - Grenade Launcher Hut', 'Surface 1 - Ammo Container - Grenade Rounds - Grenade Launcher Hut (Agent)', 'Surface 1 - Ammo Container - Grenade Rounds - Grenade Launcher Hut (Double Agent)', 'Surface 1 - Ammo Container - Grenade Rounds - Grenade Launcher Hut (Secret Agent)', 'Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 1', 'Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 1 (Agent)', 'Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 1 (Double Agent)', 'Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 1 (Secret Agent)', 'Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 2', 'Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 2 (Agent)', 'Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 2 (Double Agent)', 'Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 2 (Secret Agent)', 'Surface 1 - Ammo Container - Grenade Rounds - Surveillance Camera Hut', 'Surface 1 - Ammo Container - Grenade Rounds - Surveillance Camera Hut (Agent)', 'Surface 1 - Ammo Container - Grenade Rounds - Surveillance Camera Hut (Double Agent)', 'Surface 1 - Ammo Container - Grenade Rounds - Surveillance Camera Hut (Secret Agent)'):
        mode = world.options.ammo_crate_sanity.value
        if name in per_difficulty_item_locations:
            return mode == ITEM_SHUFFLE_MODE_PER_DIFFICULTY
        return mode == ITEM_SHUFFLE_MODE_SHARED
    if name in per_difficulty_item_locations:
        return get_item_shuffle_mode(world) == ITEM_SHUFFLE_MODE_PER_DIFFICULTY
    if name in shared_item_locations:
        return get_item_shuffle_mode(world) == ITEM_SHUFFLE_MODE_SHARED
    if name in per_difficulty_keypickup_locations:
        return get_item_shuffle_mode(world) == ITEM_SHUFFLE_MODE_PER_DIFFICULTY
    if name in shared_keypickup_locations:
        return get_item_shuffle_mode(world) == ITEM_SHUFFLE_MODE_SHARED
    if name in per_difficulty_clear_locations:
        return world.options.mission_clear_mode.value == MISSION_CLEAR_MODE_PER_DIFFICULTY
    if name in shared_clear_locations:
        return world.options.mission_clear_mode.value == MISSION_CLEAR_MODE_PER_MAP
    if name in per_difficulty_objective_locations:
        return world.options.objective_mode.value == OBJECTIVE_MODE_PER_DIFFICULTY
    if name in shared_objective_locations:
        return world.options.objective_mode.value == OBJECTIVE_MODE_SHARED
    return True


goldeneye_locations = {
    "Dam - Sniper Rifle":      LocData(70104001, "Dam"),
    "Dam - Sniper Rifle (Agent)": LocData(70114001, "Dam"),
    "Dam - Sniper Rifle (Secret Agent)": LocData(70124001, "Dam"),
    "Dam - Sniper Rifle (Double Agent)": LocData(70134001, "Dam"),
    "Dam - Body Armor (Last Dam Tower)": LocData(70105002, "Dam"),
    "Dam - Body Armor (Last Dam Tower) (Agent)": LocData(70115002, "Dam"),
    "Dam - Body Armor (Guard Tower 2)": LocData(70105001, "Dam"),
    "Dam - Body Armor (Guard Tower 2) (Agent)": LocData(70115001, "Dam"),
    "Dam - Body Armor (Last Dam Tower) (Secret Agent)": LocData(70125002, "Dam"),
    "Dam - Cheat - Paintball Mode": LocData(70103001, "Dam"),
    "Facility - Keycard A":    LocData(70202001, "Facility"),
    "Facility - Keycard B":    LocData(70202002, "Facility"),
    "Facility - Door Decoder": LocData(70202003, "Facility"),
    "Facility - Keycard A (Agent)": LocData(70212001, "Facility"),
    "Facility - Keycard B (Agent)": LocData(70212002, "Facility"),
    "Facility - Door Decoder (Agent)": LocData(70212003, "Facility"),
    "Facility - Keycard A (Secret Agent)": LocData(70222001, "Facility"),
    "Facility - Keycard B (Secret Agent)": LocData(70222002, "Facility"),
    "Facility - Door Decoder (Secret Agent)": LocData(70222003, "Facility"),
    "Facility - Keycard A (Double Agent)": LocData(70232001, "Facility"),
    "Facility - Keycard B (Double Agent)": LocData(70232002, "Facility"),
    "Facility - Door Decoder (Double Agent)": LocData(70232003, "Facility"),
    "Facility - Body Armor (Inside Security Room 2)": LocData(70205002, "Facility"),
    "Facility - Body Armor (Inside Security Room 2) (Agent)": LocData(70215002, "Facility"),
    "Facility - Body Armor (On Hallway Crate)": LocData(70205001, "Facility"),
    "Facility - Body Armor (On Hallway Crate) (Agent)": LocData(70215001, "Facility"),
    "Facility - Body Armor (On Hallway Crate) (Secret Agent)": LocData(70225001, "Facility"),
    "Facility - Cheat - Invincibility": LocData(70203001, "Facility"),
    "Runway - Ammo Container - Timed Mines - Room Behind Start": LocData(70306001, "Runway"),
    "Runway - Ammo Container - Timed Mines - Room Behind Start (Agent)": LocData(70316001, "Runway"),
    "Runway - Ammo Container - Timed Mines - Room Behind Start (Secret Agent)": LocData(70326001, "Runway"),
    "Runway - Ammo Container - Timed Mines - Room Behind Start (Double Agent)": LocData(70336001, "Runway"),
    "Runway - Ammo Container - Hand Grenades - Next To Player Start": LocData(70306002, "Runway"),
    "Runway - Ammo Container - Hand Grenades - Next To Player Start (Agent)": LocData(70316002, "Runway"),
    "Runway - Ammo Container - Hand Grenades - Next To Player Start (Secret Agent)": LocData(70326002, "Runway"),
    "Runway - Ammo Container - Hand Grenades - Next To Player Start (Double Agent)": LocData(70336002, "Runway"),
    "Runway - Ammo Container - Hand Grenades - Outside Ignition Key Building": LocData(70306003, "Runway"),
    "Runway - Ammo Container - Hand Grenades - Outside Ignition Key Building (Agent)": LocData(70316003, "Runway"),
    "Runway - Ammo Container - Hand Grenades - Outside Ignition Key Building (Secret Agent)": LocData(70326003, "Runway"),
    "Runway - Ammo Container - Hand Grenades - Outside Ignition Key Building (Double Agent)": LocData(70336003, "Runway"),
    "Runway - Cheat - DK Mode": LocData(70303001, "Runway"),
    "Surface 1 - Safe Key":    LocData(70402003, "Surface 1"),
    "Surface 1 - Safe Key (Agent)": LocData(70412003, "Surface 1"),
    "Surface 1 - Safe Key (Double Agent)": LocData(70432003, "Surface 1"),
    "Surface 1 - Safe Key (Secret Agent)": LocData(70422003, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 1": LocData(70406001, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 2": LocData(70406002, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Grenade Launcher Hut": LocData(70406003, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Surveillance Camera Hut": LocData(70406004, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 1 (Agent)": LocData(70416001, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 2 (Agent)": LocData(70416002, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Grenade Launcher Hut (Agent)": LocData(70416003, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Surveillance Camera Hut (Agent)": LocData(70416004, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 1 (Secret Agent)": LocData(70426001, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 2 (Secret Agent)": LocData(70426002, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Grenade Launcher Hut (Secret Agent)": LocData(70426003, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Surveillance Camera Hut (Secret Agent)": LocData(70426004, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 1 (Double Agent)": LocData(70436001, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Right Hut Near Start 2 (Double Agent)": LocData(70436002, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Grenade Launcher Hut (Double Agent)": LocData(70436003, "Surface 1"),
    "Surface 1 - Ammo Container - Grenade Rounds - Surveillance Camera Hut (Double Agent)": LocData(70436004, "Surface 1"),
    "Surface 1 - Grenade Launcher": LocData(70404001, "Surface 1"),
    "Surface 1 - Grenade Launcher (Agent)": LocData(70414001, "Surface 1"),
    "Surface 1 - Grenade Launcher (Secret Agent)": LocData(70424001, "Surface 1"),
    "Surface 1 - Grenade Launcher (Double Agent)": LocData(70434001, "Surface 1"),
    "Surface 1 - Cheat - 2x Grenade Launcher": LocData(70403001, "Surface 1"),
    "Bunker 1 - Computer Room Keycard": LocData(70502002, "Bunker 1"),
    "Bunker 1 - Security Keycard": LocData(70502003, "Bunker 1"),
    "Bunker 1 - Computer Room Keycard (Agent)": LocData(70512002, "Bunker 1"),
    "Bunker 1 - Security Keycard (Agent)": LocData(70512003, "Bunker 1"),
    "Bunker 1 - Computer Room Keycard (Secret Agent)": LocData(70522002, "Bunker 1"),
    "Bunker 1 - Security Keycard (Secret Agent)": LocData(70522003, "Bunker 1"),
    "Bunker 1 - Computer Room Keycard (Double Agent)": LocData(70532002, "Bunker 1"),
    "Bunker 1 - Security Keycard (Double Agent)": LocData(70532003, "Bunker 1"),
    "Bunker 1 - Ammo Container - Rifle Ammo - Room In Front of Start": LocData(70506001, "Bunker 1"),
    "Bunker 1 - Ammo Container - Rifle Ammo - Room In Front of Start (Agent)": LocData(70516001, "Bunker 1"),
    "Bunker 1 - Ammo Container - Rifle Ammo - Room In Front of Start (Secret Agent)": LocData(70526001, "Bunker 1"),
    "Bunker 1 - Ammo Container - Rifle Ammo - Room In Front of Start (Double Agent)": LocData(70536001, "Bunker 1"),
    "Bunker 1 - Body Armor (Kitchen)": LocData(70505003, "Bunker 1"),
    "Bunker 1 - Body Armor (Kitchen) (Agent)": LocData(70515003, "Bunker 1"),
    "Bunker 1 - Body Armor (Rear Tunnel)": LocData(70505005, "Bunker 1"),
    "Bunker 1 - Body Armor (Rear Tunnel) (Agent)": LocData(70515005, "Bunker 1"),
    "Bunker 1 - Body Armor (Rear Tunnel) (Secret Agent)": LocData(70525005, "Bunker 1"),
    "Bunker 1 - Cheat - 2x Rocket Launcher": LocData(70503001, "Bunker 1"),
    "Silo - DAT":              LocData(70602002, "Silo"),
    "Silo - Keycard Silo Level 1": LocData(70602006, "Silo"),
    "Silo - Keycard Silo Level 2": LocData(70602007, "Silo"),
    "Silo - Keycard Silo Level 3": LocData(70602008, "Silo"),
    "Silo - DAT (Agent)":      LocData(70612002, "Silo"),
    "Silo - Keycard Silo Level 1 (Agent)": LocData(70612006, "Silo"),
    "Silo - Keycard Silo Level 2 (Agent)": LocData(70612007, "Silo"),
    "Silo - Keycard Silo Level 3 (Agent)": LocData(70612008, "Silo"),
    "Silo - DAT (Secret Agent)": LocData(70622002, "Silo"),
    "Silo - Keycard Silo Level 1 (Secret Agent)": LocData(70622006, "Silo"),
    "Silo - Keycard Silo Level 2 (Secret Agent)": LocData(70622007, "Silo"),
    "Silo - Keycard Silo Level 3 (Secret Agent)": LocData(70622008, "Silo"),
    "Silo - DAT (Double Agent)": LocData(70632002, "Silo"),
    "Silo - Keycard Silo Level 1 (Double Agent)": LocData(70632006, "Silo"),
    "Silo - Keycard Silo Level 2 (Double Agent)": LocData(70632007, "Silo"),
    "Silo - Keycard Silo Level 3 (Double Agent)": LocData(70632008, "Silo"),
    "Silo - Body Armor (Second Fuel Room)": LocData(70605001, "Silo"),
    "Silo - Body Armor (Second Fuel Room) (Agent)": LocData(70615001, "Silo"),
    "Silo - Body Armor (Fourth Fuel Room)": LocData(70605002, "Silo"),
    "Silo - Body Armor (Fourth Fuel Room) (Agent)": LocData(70615002, "Silo"),
    "Silo - Body Armor (Walkway After Third Fuel Room)": LocData(70605003, "Silo"),
    "Silo - Body Armor (Walkway After Third Fuel Room) (Agent)": LocData(70615003, "Silo"),
    "Silo - Body Armor (Fourth Fuel Room) (Secret Agent)": LocData(70625002, "Silo"),
    "Silo - Body Armor (Walkway After Third Fuel Room) (Secret Agent)": LocData(70625003, "Silo"),
    "Silo - Body Armor (Walkway After Third Fuel Room) (Double Agent)": LocData(70635003, "Silo"),
    "Silo - Cheat - Turbo Mode": LocData(70603001, "Silo"),
    "Frigate - Body Armor (Invisable on Crate in Cargo Hold)": LocData(70705001, "Frigate"),
    "Frigate - Body Armor (Invisable on Crate in Cargo Hold) (Agent)": LocData(70715001, "Frigate"),
    "Frigate - Body Armor (Radio Room)": LocData(70705002, "Frigate"),
    "Frigate - Body Armor (Radio Room) (Agent)": LocData(70715002, "Frigate"),
    "Frigate - Body Armor (Radio Room) (Secret Agent)": LocData(70725002, "Frigate"),
    "Frigate - Cheat - No Radar (Multi)": LocData(70703001, "Frigate"),
    "Surface 2 - Body Armor (Cabin With Camera)": LocData(70805001, "Surface 2"),
    "Surface 2 - Body Armor (Cabin With Camera) (Agent)": LocData(70815001, "Surface 2"),
    "Surface 2 - Body Armor (Fenced Area Cabin)": LocData(70805002, "Surface 2"),
    "Surface 2 - Body Armor (Fenced Area Cabin) (Agent)": LocData(70815002, "Surface 2"),
    "Surface 2 - Cheat - Tiny Bond": LocData(70803001, "Surface 2"),
    "Bunker 2 - Cell Key 2":   LocData(70902006, "Bunker 2"),
    "Bunker 2 - Keycard A":    LocData(70902007, "Bunker 2"),
    "Bunker 2 - Keycard B":    LocData(70902008, "Bunker 2"),
    "Bunker 2 - Cell Key 2 (Agent)": LocData(70912006, "Bunker 2"),
    "Bunker 2 - Keycard A (Agent)": LocData(70912007, "Bunker 2"),
    "Bunker 2 - Keycard B (Agent)": LocData(70912008, "Bunker 2"),
    "Bunker 2 - Cell Key 2 (Secret Agent)": LocData(70922006, "Bunker 2"),
    "Bunker 2 - Keycard A (Secret Agent)": LocData(70922007, "Bunker 2"),
    "Bunker 2 - Keycard B (Secret Agent)": LocData(70922008, "Bunker 2"),
    "Bunker 2 - Cell Key 2 (Double Agent)": LocData(70932006, "Bunker 2"),
    "Bunker 2 - Keycard A (Double Agent)": LocData(70932007, "Bunker 2"),
    "Bunker 2 - Keycard B (Double Agent)": LocData(70932008, "Bunker 2"),
    "Bunker 2 - Throwing Knives": LocData(70904001, "Bunker 2"),
    "Bunker 2 - Throwing Knives (Agent)": LocData(70914001, "Bunker 2"),
    "Bunker 2 - Throwing Knives (Secret Agent)": LocData(70924001, "Bunker 2"),
    "Bunker 2 - Throwing Knives (Double Agent)": LocData(70934001, "Bunker 2"),
    "Bunker 2 - Silenced PP7 1 - In Safe": LocData(70904002, "Bunker 2"),
    "Bunker 2 - Silenced PP7 2 - In Safe": LocData(70904003, "Bunker 2"),
    "Bunker 2 - Silenced PP7 1 - In Safe (Agent)": LocData(70914002, "Bunker 2"),
    "Bunker 2 - Silenced PP7 2 - In Safe (Agent)": LocData(70914003, "Bunker 2"),
    "Bunker 2 - Silenced PP7 1 - In Safe (Secret Agent)": LocData(70924002, "Bunker 2"),
    "Bunker 2 - Silenced PP7 2 - In Safe (Secret Agent)": LocData(70924003, "Bunker 2"),
    "Bunker 2 - Silenced PP7 1 - In Safe (Double Agent)": LocData(70934002, "Bunker 2"),
    "Bunker 2 - Silenced PP7 2 - In Safe (Double Agent)": LocData(70934003, "Bunker 2"),
    "Bunker 2 - Body Armor (Auto Turret Tunnel)": LocData(70905001, "Bunker 2"),
    "Bunker 2 - Body Armor (Auto Turret Tunnel) (Agent)": LocData(70915001, "Bunker 2"),
    "Bunker 2 - Body Armor (Shooting Range)": LocData(70905002, "Bunker 2"),
    "Bunker 2 - Body Armor (Shooting Range) (Agent)": LocData(70915002, "Bunker 2"),
    "Bunker 2 - Body Armor (Shooting Range) (Secret Agent)": LocData(70925002, "Bunker 2"),
    "Bunker 2 - Cheat - 2x Throwing Knives": LocData(70903001, "Bunker 2"),
    "Statue - Body Armor (Near Hand)": LocData(71005001, "Statue"),
    "Statue - Body Armor (Near Hand) (Agent)": LocData(71015001, "Statue"),
    "Statue - Body Armor (Near Hand) (Secret Agent)": LocData(71025001, "Statue"),
    "Statue - Body Armor (Near Hand) (Double Agent)": LocData(71035001, "Statue"),
    "Statue - Cheat - Fast Animation": LocData(71003001, "Statue"),
    "Archives - Safe Key":     LocData(71102003, "Archives"),
    "Archives - Safe Key (Agent)": LocData(71112003, "Archives"),
    "Archives - Safe Key (Secret Agent)": LocData(71122003, "Archives"),
    "Archives - Safe Key (Double Agent)": LocData(71132003, "Archives"),
    "Archives - PP7":          LocData(71104001, "Archives"),
    "Archives - PP7 (Agent)":  LocData(71114001, "Archives"),
    "Archives - PP7 (Secret Agent)": LocData(71124001, "Archives"),
    "Archives - PP7 (Double Agent)": LocData(71134001, "Archives"),
    "Archives - Body Armor (Bottom Floor On Crate)": LocData(71105001, "Archives"),
    "Archives - Body Armor (Bottom Floor On Crate) (Agent)": LocData(71115001, "Archives"),
    "Archives - Body Armor (Room Across From Start)": LocData(71105002, "Archives"),
    "Archives - Body Armor (Room Across From Start) (Agent)": LocData(71115002, "Archives"),
    "Archives - Body Armor (Room Across From Start) (Secret Agent)": LocData(71125002, "Archives"),
    "Archives - Cheat - Invisibility": LocData(71103001, "Archives"),
    "Streets - Ammo Container - Grenade Rounds - (Through Window Past Valentin)": LocData(71206001, "Streets"),
    "Streets - Ammo Container - Grenade Rounds - (Through Window Past Valentin) (Agent)": LocData(71216001, "Streets"),
    "Streets - Ammo Container - Grenade Rounds - (Through Window Past Valentin) (Secret Agent)": LocData(71226001, "Streets"),
    "Streets - Ammo Container - Grenade Rounds - (Through Window Past Valentin) (Double Agent)": LocData(71236001, "Streets"),
    "Streets - Grenade Launcher": LocData(71204001, "Streets"),
    "Streets - Grenade Launcher (Agent)": LocData(71214001, "Streets"),
    "Streets - Grenade Launcher (Secret Agent)": LocData(71224001, "Streets"),
    "Streets - Grenade Launcher (Double Agent)": LocData(71234001, "Streets"),
    "Streets - Body Armor (Through Window Past Valentin)": LocData(71205001, "Streets"),
    "Streets - Body Armor (Through Window Past Valentin) (Agent)": LocData(71215001, "Streets"),
    "Streets - Body Armor (Mid Level Checkpoint)": LocData(71205002, "Streets"),
    "Streets - Body Armor (Mid Level Checkpoint) (Agent)": LocData(71215002, "Streets"),
    "Streets - Body Armor (Ending Right Side Checkpoint)": LocData(71205003, "Streets"),
    "Streets - Body Armor (Ending Right Side Checkpoint) (Agent)": LocData(71215003, "Streets"),
    "Streets - Body Armor (Ending Left Side Checkpoint)": LocData(71205004, "Streets"),
    "Streets - Body Armor (Ending Left Side Checkpoint) (Agent)": LocData(71215004, "Streets"),
    "Streets - Body Armor (Through Window Past Valentin) (Secret Agent)": LocData(71225001, "Streets"),
    "Streets - Body Armor (Mid Level Checkpoint) (Secret Agent)": LocData(71225002, "Streets"),
    "Streets - Body Armor (Ending Right Side Checkpoint) (Secret Agent)": LocData(71225003, "Streets"),
    "Streets - Body Armor (Ending Left Side Checkpoint) (Secret Agent)": LocData(71225004, "Streets"),
    "Streets - Body Armor (Through Window Past Valentin) (Double Agent)": LocData(71235001, "Streets"),
    "Streets - Body Armor (Mid Level Checkpoint) (Double Agent)": LocData(71235002, "Streets"),
    "Streets - Body Armor (Ending Right Side Checkpoint) (Double Agent)": LocData(71235003, "Streets"),
    "Streets - Body Armor (Ending Left Side Checkpoint) (Double Agent)": LocData(71235004, "Streets"),
    "Streets - Cheat - Enemy Rockets": LocData(71203001, "Streets"),
    "Depot - KF7 Bottom Right Table": LocData(71304001, "Depot"),
    "Depot - KF7 Bottom Right Table (Agent)": LocData(71314001, "Depot"),
    "Depot - KF7 Bottom Right Table (Secret Agent)": LocData(71324001, "Depot"),
    "Depot - KF7 Bottom Right Table (Double Agent)": LocData(71334001, "Depot"),
    "Depot - D5K Bottom Right Table 1": LocData(71304002, "Depot"),
    "Depot - D5K Bottom Right Table 1 (Agent)": LocData(71314002, "Depot"),
    "Depot - D5K Bottom Right Table 1 (Secret Agent)": LocData(71324002, "Depot"),
    "Depot - D5K Bottom Right Table 1 (Double Agent)": LocData(71334002, "Depot"),
    "Depot - D5K Bottom Right Table 2": LocData(71304003, "Depot"),
    "Depot - D5K Bottom Right Table 2 (Agent)": LocData(71314003, "Depot"),
    "Depot - D5K Bottom Right Table 2 (Secret Agent)": LocData(71324003, "Depot"),
    "Depot - D5K Bottom Right Table 2 (Double Agent)": LocData(71334003, "Depot"),
    "Depot - D5K On Floor":    LocData(71304004, "Depot"),
    "Depot - D5K On Floor (Agent)": LocData(71314004, "Depot"),
    "Depot - D5K On Floor (Secret Agent)": LocData(71324004, "Depot"),
    "Depot - D5K On Floor (Double Agent)": LocData(71334004, "Depot"),
    "Depot - D5K Top Right Table 1": LocData(71304005, "Depot"),
    "Depot - D5K Top Right Table 1 (Agent)": LocData(71314005, "Depot"),
    "Depot - D5K Top Right Table 1 (Secret Agent)": LocData(71324005, "Depot"),
    "Depot - D5K Top Right Table 1 (Double Agent)": LocData(71334005, "Depot"),
    "Depot - D5K Top Right Table 2": LocData(71304006, "Depot"),
    "Depot - D5K Top Right Table 2 (Agent)": LocData(71314006, "Depot"),
    "Depot - D5K Top Right Table 2 (Secret Agent)": LocData(71324006, "Depot"),
    "Depot - D5K Top Right Table 2 (Double Agent)": LocData(71334006, "Depot"),
    "Depot - D5K Top Right Table 3": LocData(71304007, "Depot"),
    "Depot - D5K Top Right Table 3 (Agent)": LocData(71314007, "Depot"),
    "Depot - D5K Top Right Table 3 (Secret Agent)": LocData(71324007, "Depot"),
    "Depot - D5K Top Right Table 3 (Double Agent)": LocData(71334007, "Depot"),
    "Depot - Rockets 1":       LocData(71306001, "Depot"),
    "Depot - Rockets 1 (Agent)": LocData(71316001, "Depot"),
    "Depot - Rockets 1 (Secret Agent)": LocData(71326001, "Depot"),
    "Depot - Rockets 1 (Double Agent)": LocData(71336001, "Depot"),
    "Depot - Rockets 2":       LocData(71306002, "Depot"),
    "Depot - Rockets 2 (Agent)": LocData(71316002, "Depot"),
    "Depot - Rockets 2 (Secret Agent)": LocData(71326002, "Depot"),
    "Depot - Rockets 2 (Double Agent)": LocData(71336002, "Depot"),
    "Depot - Rockets 3":       LocData(71306003, "Depot"),
    "Depot - Rockets 3 (Agent)": LocData(71316003, "Depot"),
    "Depot - Rockets 3 (Secret Agent)": LocData(71326003, "Depot"),
    "Depot - Rockets 3 (Double Agent)": LocData(71336003, "Depot"),
    "Depot - Rocket Launcher": LocData(71304009, "Depot"),
    "Depot - Rocket Launcher (Agent)": LocData(71314009, "Depot"),
    "Depot - Rocket Launcher (Secret Agent)": LocData(71324009, "Depot"),
    "Depot - Rocket Launcher (Double Agent)": LocData(71334009, "Depot"),
    "Depot - KF7 Bottom Left Table 1": LocData(71304010, "Depot"),
    "Depot - KF7 Bottom Left Table 1 (Agent)": LocData(71314010, "Depot"),
    "Depot - KF7 Bottom Left Table 1 (Secret Agent)": LocData(71324010, "Depot"),
    "Depot - KF7 Bottom Left Table 1 (Double Agent)": LocData(71334010, "Depot"),
    "Depot - KF7 Bottom Left Table 2": LocData(71304011, "Depot"),
    "Depot - KF7 Bottom Left Table 2 (Agent)": LocData(71314011, "Depot"),
    "Depot - KF7 Bottom Left Table 2 (Secret Agent)": LocData(71324011, "Depot"),
    "Depot - KF7 Bottom Left Table 2 (Double Agent)": LocData(71334011, "Depot"),
    "Depot - KF7 Bottom Left Table 3": LocData(71304012, "Depot"),
    "Depot - KF7 Bottom Left Table 3 (Agent)": LocData(71314012, "Depot"),
    "Depot - KF7 Bottom Left Table 3 (Secret Agent)": LocData(71324012, "Depot"),
    "Depot - KF7 Bottom Left Table 3 (Double Agent)": LocData(71334012, "Depot"),
    "Depot - KF7 Bottom Left Table 4": LocData(71304013, "Depot"),
    "Depot - KF7 Bottom Left Table 4 (Agent)": LocData(71314013, "Depot"),
    "Depot - KF7 Bottom Left Table 4 (Secret Agent)": LocData(71324013, "Depot"),
    "Depot - KF7 Bottom Left Table 4 (Double Agent)": LocData(71334013, "Depot"),
    "Depot - KF7 Bottom Left Table 5": LocData(71304015, "Depot"),
    "Depot - KF7 Bottom Left Table 5 (Agent)": LocData(71314015, "Depot"),
    "Depot - KF7 Bottom Left Table 5 (Secret Agent)": LocData(71324015, "Depot"),
    "Depot - KF7 Bottom Left Table 5 (Double Agent)": LocData(71334015, "Depot"),
    "Depot - Proximity Mines": LocData(71306014, "Depot"),
    "Depot - Proximity Mines (Agent)": LocData(71316014, "Depot"),
    "Depot - Proximity Mines (Secret Agent)": LocData(71326014, "Depot"),
    "Depot - Proximity Mines (Double Agent)": LocData(71336014, "Depot"),
    "Depot - Body Armor (Outside Behind Stacked Crates Right of Start)": LocData(71305000, "Depot"),
    "Depot - Body Armor (Outside Behind Stacked Crates Right of Start) (Agent)": LocData(71315000, "Depot"),
    "Depot - Body Armor (Behind Crate In Front of Start)": LocData(71305001, "Depot"),
    "Depot - Body Armor (Behind Crate In Front of Start) (Agent)": LocData(71315001, "Depot"),
    "Depot - Body Armor (Back of Blue Hangar Near Start)": LocData(71305002, "Depot"),
    "Depot - Body Armor (Back of Blue Hangar Near Start) (Agent)": LocData(71315002, "Depot"),
    "Depot - Body Armor (Outside Behind House Left of Blue Hangar Near Start)": LocData(71305003, "Depot"),
    "Depot - Body Armor (Outside Behind House Left of Blue Hangar Near Start) (Agent)": LocData(71315003, "Depot"),
    "Depot - Body Armor (Back of Grey Hangar Near Start)": LocData(71305004, "Depot"),
    "Depot - Body Armor (Back of Grey Hangar Near Start) (Agent)": LocData(71315004, "Depot"),
    "Depot - Body Armor (Back Left Corner Three Door Hangar)": LocData(71305005, "Depot"),
    "Depot - Body Armor (Back Left Corner Three Door Hangar) (Agent)": LocData(71315005, "Depot"),
    "Depot - Body Armor (Back of Last Hangar On Middle Road)": LocData(71305006, "Depot"),
    "Depot - Body Armor (Back of Last Hangar On Middle Road) (Agent)": LocData(71315006, "Depot"),
    "Depot - Body Armor (Back of Hangar Across from Ammo Cache)": LocData(71305007, "Depot"),
    "Depot - Body Armor (Back of Hangar Across from Ammo Cache) (Agent)": LocData(71315007, "Depot"),
    "Depot - Body Armor (Outside Behind Crate Under Orange Pipe)": LocData(71305008, "Depot"),
    "Depot - Body Armor (Outside Behind Crate Under Orange Pipe) (Agent)": LocData(71315008, "Depot"),
    "Depot - Body Armor (Back Corner Behind Crates Just Before Train Station Gate)": LocData(71305009, "Depot"),
    "Depot - Body Armor (Back Corner Behind Crates Just Before Train Station Gate) (Agent)": LocData(71315009, "Depot"),
    "Depot - Body Armor (Back of Last Hangar)": LocData(71305010, "Depot"),
    "Depot - Body Armor (Back of Last Hangar) (Agent)": LocData(71315010, "Depot"),
    "Depot - Body Armor (Inside Train Station)": LocData(71305011, "Depot"),
    "Depot - Body Armor (Inside Train Station) (Agent)": LocData(71315011, "Depot"),
    "Depot - Body Armor (Back of Blue Hangar Near Start) (Secret Agent)": LocData(71325002, "Depot"),
    "Depot - Body Armor (Back of Grey Hangar Near Start) (Secret Agent)": LocData(71325004, "Depot"),
    "Depot - Body Armor (Back Left Corner Three Door Hangar) (Secret Agent)": LocData(71325005, "Depot"),
    "Depot - Body Armor (Back of Last Hangar On Middle Road) (Secret Agent)": LocData(71325006, "Depot"),
    "Depot - Body Armor (Outside Behind Crate Under Orange Pipe) (Secret Agent)": LocData(71325008, "Depot"),
    "Depot - Body Armor (Back of Last Hangar) (Secret Agent)": LocData(71325010, "Depot"),
    "Depot - Cheat - Slow Animation": LocData(71303001, "Depot"),
    "Train - Key":             LocData(71402001, "Train"),
    "Train - Key (Agent)":     LocData(71412001, "Train"),
    "Train - Key (Double Agent)": LocData(71432001, "Train"),
    "Train - Key (Secret Agent)": LocData(71422001, "Train"),
    "Train - Gun in Box":      LocData(71404001, "Train"),
    "Train - RC-P90 (Agent)":  LocData(71414001, "Train"),
    "Train - DD44 (Secret Agent)": LocData(71424001, "Train"),
    "Train - Cheat - Silver PP7": LocData(71403001, "Train"),
    "Jungle - Body Armor (First Area Back Corner)": LocData(71505001, "Jungle"),
    "Jungle - Body Armor (First Area Back Corner) (Agent)": LocData(71515001, "Jungle"),
    "Jungle - Body Armor (Behind Second Turret)": LocData(71505002, "Jungle"),
    "Jungle - Body Armor (Behind Second Turret) (Agent)": LocData(71515002, "Jungle"),
    "Jungle - Body Armor (Behind Guard Tower)": LocData(71505003, "Jungle"),
    "Jungle - Body Armor (Behind Guard Tower) (Agent)": LocData(71515003, "Jungle"),
    "Jungle - Body Armor (First Area Back Corner) (Secret Agent)": LocData(71525001, "Jungle"),
    "Jungle - Body Armor (Behind Second Turret) (Secret Agent)": LocData(71525002, "Jungle"),
    "Jungle - Body Armor (Behind Guard Tower) (Secret Agent)": LocData(71525003, "Jungle"),
    "Jungle - Body Armor (First Area Back Corner) (Double Agent)": LocData(71535001, "Jungle"),
    "Jungle - Body Armor (Behind Second Turret) (Double Agent)": LocData(71535002, "Jungle"),
    "Jungle - Cheat - 2x Hunting Knives": LocData(71503001, "Jungle"),
    "Control - Ammo Container - Remote Mines - After First Blast Door": LocData(71606001, "Control"),
    "Control - Ammo Container - Remote Mines - After First Blast Door (Agent)": LocData(71616001, "Control"),
    "Control - Ammo Container - Remote Mines - After First Blast Door (Secret Agent)": LocData(71626001, "Control"),
    "Control - Ammo Container - Remote Mines - After First Blast Door (Double Agent)": LocData(71636001, "Control"),
    "Control - Boris' PP7":    LocData(71602001, "Control"),
    "Control - Boris' PP7 (Agent)": LocData(71612001, "Control"),
    "Control - Boris' PP7 (Secret Agent)": LocData(71622001, "Control"),
    "Control - Boris' PP7 (Double Agent)": LocData(71632001, "Control"),
    "Control - Body Armor (Locker Room Corner)": LocData(71605001, "Control"),
    "Control - Body Armor (Locker Room Corner) (Agent)": LocData(71615001, "Control"),
    "Control - Body Armor (Top Floor Behind Grate)": LocData(71605002, "Control"),
    "Control - Body Armor (Top Floor Behind Grate) (Agent)": LocData(71615002, "Control"),
    "Control - Body Armor (Locker Room Corner) (Secret Agent)": LocData(71625001, "Control"),
    "Control - Body Armor (Top Floor Behind Grate) (Secret Agent)": LocData(71625002, "Control"),
    "Control - Body Armor (Locker Room Corner) (Double Agent)": LocData(71635001, "Control"),
    "Control - Body Armor (Top Floor Behind Grate) (Double Agent)": LocData(71635002, "Control"),
    "Control - Cheat - Infinite Ammo": LocData(71603001, "Control"),
    "Caverns - Code Card 1":   LocData(71702001, "Caverns"),
    "Caverns - Code Card 1 (Agent)": LocData(71712001, "Caverns"),
    "Caverns - Code Card 2":   LocData(71702002, "Caverns"),
    "Caverns - Code Card 2 (Agent)": LocData(71712002, "Caverns"),
    "Caverns - Code Card 3":   LocData(71702003, "Caverns"),
    "Caverns - Code Card 3 (Agent)": LocData(71712003, "Caverns"),
    "Caverns - Code Card 1 (Secret Agent)": LocData(71722001, "Caverns"),
    "Caverns - Code Card 2 (Secret Agent)": LocData(71722002, "Caverns"),
    "Caverns - Code Card 3 (Secret Agent)": LocData(71722003, "Caverns"),
    "Caverns - Code Card 1 (Double Agent)": LocData(71732001, "Caverns"),
    "Caverns - Code Card 2 (Double Agent)": LocData(71732002, "Caverns"),
    "Caverns - Code Card 3 (Double Agent)": LocData(71732003, "Caverns"),
    "Caverns - AR33 Assault Rifle": LocData(71704001, "Caverns"),
    "Caverns - AR33 Assault Rifle (Agent)": LocData(71714001, "Caverns"),
    "Caverns - AR33 Assault Rifle (Secret Agent)": LocData(71724001, "Caverns"),
    "Caverns - AR33 Assault Rifle (Double Agent)": LocData(71734001, "Caverns"),
    "Caverns - Body Armor (Under Walkway On Crate)": LocData(71705001, "Caverns"),
    "Caverns - Body Armor (Under Walkway On Crate) (Agent)": LocData(71715001, "Caverns"),
    "Caverns - Body Armor (Comms Room)": LocData(71705003, "Caverns"),
    "Caverns - Body Armor (Comms Room) (Agent)": LocData(71715003, "Caverns"),
    "Caverns - Body Armor (Comms Room) (Secret Agent)": LocData(71725003, "Caverns"),
    "Caverns - Cheat - 2x RC-P90s": LocData(71703001, "Caverns"),
    "Cradle - Body Armor (Start Tower)": LocData(71805001, "Cradle"),
    "Cradle - Body Armor (Start Tower) (Agent)": LocData(71815001, "Cradle"),
    "Cradle - Body Armor (Behind Antenna Control)": LocData(71805002, "Cradle"),
    "Cradle - Body Armor (Behind Antenna Control) (Agent)": LocData(71815002, "Cradle"),
    "Cradle - Body Armor (Left Tower)": LocData(71805003, "Cradle"),
    "Cradle - Body Armor (Left Tower) (Agent)": LocData(71815003, "Cradle"),
    "Cradle - Body Armor (Right Tower)": LocData(71805004, "Cradle"),
    "Cradle - Body Armor (Right Tower) (Agent)": LocData(71815004, "Cradle"),
    "Cradle - Body Armor (Start Tower) (Secret Agent)": LocData(71825001, "Cradle"),
    "Cradle - Body Armor (Behind Antenna Control) (Secret Agent)": LocData(71825002, "Cradle"),
    "Cradle - Body Armor (Left Tower) (Secret Agent)": LocData(71825003, "Cradle"),
    "Cradle - Body Armor (Right Tower) (Secret Agent)": LocData(71825004, "Cradle"),
    "Cradle - Body Armor (Start Tower) (Double Agent)": LocData(71835001, "Cradle"),
    "Cradle - Body Armor (Behind Antenna Control) (Double Agent)": LocData(71835002, "Cradle"),
    "Cradle - Body Armor (Left Tower) (Double Agent)": LocData(71835003, "Cradle"),
    "Cradle - Body Armor (Right Tower) (Double Agent)": LocData(71835004, "Cradle"),
    "Cradle - Cheat - Gold PP7": LocData(71803001, "Cradle"),
    "Stopped Goldeneye":       LocData(72110002, "Cradle"),
}

keypickup_locations = {
    "Runway - Ignition Key":   LocData(70302001, "Runway"),
    "Runway - Ignition Key (Agent)": LocData(70312001, "Runway"),
    "Runway - Ignition Key (Secret Agent)": LocData(70322001, "Runway"),
    "Runway - Ignition Key (Double Agent)": LocData(70332001, "Runway"),
    "Surface 1 - Bunker Plans": LocData(70402001, "Surface 1"),
    "Surface 1 - Hut Door Key": LocData(70402002, "Surface 1"),
    "Surface 1 - Bunker Plans (Agent)": LocData(70412001, "Surface 1"),
    "Surface 1 - Hut Door Key (Agent)": LocData(70412002, "Surface 1"),
    "Surface 1 - Bunker Plans (Double Agent)": LocData(70432001, "Surface 1"),
    "Surface 1 - Hut Door Key (Double Agent)": LocData(70432002, "Surface 1"),
    "Surface 1 - Bunker Plans (Secret Agent)": LocData(70422001, "Surface 1"),
    "Surface 1 - Hut Door Key (Secret Agent)": LocData(70422002, "Surface 1"),
    "Bunker 1 - Goldeneye Key": LocData(70502001, "Bunker 1"),
    "Bunker 1 - Goldeneye Key (Agent)": LocData(70512001, "Bunker 1"),
    "Bunker 1 - Goldeneye Key (Secret Agent)": LocData(70522001, "Bunker 1"),
    "Bunker 1 - Goldeneye Key (Double Agent)": LocData(70532001, "Bunker 1"),
    "Silo - CPU Circuit Board": LocData(70602001, "Silo"),
    "Silo - I/O Circuit Board": LocData(70602003, "Silo"),
    "Silo - RDP Circuit Board": LocData(70602004, "Silo"),
    "Silo - RSP Circuit Board": LocData(70602005, "Silo"),
    "Silo - CPU Circuit Board (Agent)": LocData(70612001, "Silo"),
    "Silo - I/O Circuit Board (Agent)": LocData(70612003, "Silo"),
    "Silo - RDP Circuit Board (Agent)": LocData(70612004, "Silo"),
    "Silo - RSP Circuit Board (Agent)": LocData(70612005, "Silo"),
    "Silo - CPU Circuit Board (Secret Agent)": LocData(70622001, "Silo"),
    "Silo - I/O Circuit Board (Secret Agent)": LocData(70622003, "Silo"),
    "Silo - RDP Circuit Board (Secret Agent)": LocData(70622004, "Silo"),
    "Silo - RSP Circuit Board (Secret Agent)": LocData(70622005, "Silo"),
    "Silo - CPU Circuit Board (Double Agent)": LocData(70632001, "Silo"),
    "Silo - I/O Circuit Board (Double Agent)": LocData(70632003, "Silo"),
    "Silo - RDP Circuit Board (Double Agent)": LocData(70632004, "Silo"),
    "Silo - RSP Circuit Board (Double Agent)": LocData(70632005, "Silo"),
    "Surface 2 - Comms Room Key": LocData(70802001, "Surface 2"),
    "Surface 2 - Comms Room Key (Agent)": LocData(70812001, "Surface 2"),
    "Surface 2 - Comms Room Key (Secret Agent)": LocData(70822001, "Surface 2"),
    "Surface 2 - Comms Room Key (Double Agent)": LocData(70832001, "Surface 2"),
    "Bunker 2 - Casualty List": LocData(70902001, "Bunker 2"),
    "Bunker 2 - CCTV Tape":    LocData(70902002, "Bunker 2"),
    "Bunker 2 - Goldeneye Operations Manual": LocData(70902003, "Bunker 2"),
    "Bunker 2 - Staff List":   LocData(70902004, "Bunker 2"),
    "Bunker 2 - Cell Key 1":   LocData(70902005, "Bunker 2"),
    "Bunker 2 - Safe Key 1":   LocData(70902009, "Bunker 2"),
    "Bunker 2 - Safe Key 2":   LocData(70902010, "Bunker 2"),
    "Bunker 2 - Casualty List (Agent)": LocData(70912001, "Bunker 2"),
    "Bunker 2 - CCTV Tape (Agent)": LocData(70912002, "Bunker 2"),
    "Bunker 2 - Goldeneye Operations Manual (Agent)": LocData(70912003, "Bunker 2"),
    "Bunker 2 - Staff List (Agent)": LocData(70912004, "Bunker 2"),
    "Bunker 2 - Cell Key 1 (Agent)": LocData(70912005, "Bunker 2"),
    "Bunker 2 - Safe Key 1 (Agent)": LocData(70912009, "Bunker 2"),
    "Bunker 2 - Safe Key 2 (Agent)": LocData(70912010, "Bunker 2"),
    "Bunker 2 - Casualty List (Secret Agent)": LocData(70922001, "Bunker 2"),
    "Bunker 2 - CCTV Tape (Secret Agent)": LocData(70922002, "Bunker 2"),
    "Bunker 2 - Goldeneye Operations Manual (Secret Agent)": LocData(70922003, "Bunker 2"),
    "Bunker 2 - Staff List (Secret Agent)": LocData(70922004, "Bunker 2"),
    "Bunker 2 - Cell Key 1 (Secret Agent)": LocData(70922005, "Bunker 2"),
    "Bunker 2 - Safe Key 1 (Secret Agent)": LocData(70922009, "Bunker 2"),
    "Bunker 2 - Safe Key 2 (Secret Agent)": LocData(70922010, "Bunker 2"),
    "Bunker 2 - Casualty List (Double Agent)": LocData(70932001, "Bunker 2"),
    "Bunker 2 - CCTV Tape (Double Agent)": LocData(70932002, "Bunker 2"),
    "Bunker 2 - Goldeneye Operations Manual (Double Agent)": LocData(70932003, "Bunker 2"),
    "Bunker 2 - Staff List (Double Agent)": LocData(70932004, "Bunker 2"),
    "Bunker 2 - Cell Key 1 (Double Agent)": LocData(70932005, "Bunker 2"),
    "Bunker 2 - Safe Key 1 (Double Agent)": LocData(70932009, "Bunker 2"),
    "Bunker 2 - Safe Key 2 (Double Agent)": LocData(70932010, "Bunker 2"),
    "Statue - Flight Recorder": LocData(71002001, "Statue"),
    "Statue - Flight Recorder (Agent)": LocData(71012001, "Statue"),
    "Statue - Flight Recorder (Secret Agent)": LocData(71022001, "Statue"),
    "Statue - Flight Recorder (Double Agent)": LocData(71032001, "Statue"),
    "Archives - Flight Recorder": LocData(71102001, "Archives"),
    "Archives - Interrogation Room Key": LocData(71102002, "Archives"),
    "Archives - Flight Recorder (Agent)": LocData(71112001, "Archives"),
    "Archives - Interrogation Room Key (Agent)": LocData(71112002, "Archives"),
    "Archives - Flight Recorder (Secret Agent)": LocData(71122001, "Archives"),
    "Archives - Interrogation Room Key (Secret Agent)": LocData(71122002, "Archives"),
    "Archives - Flight Recorder (Double Agent)": LocData(71132001, "Archives"),
    "Archives - Interrogation Room Key (Double Agent)": LocData(71132002, "Archives"),
    "Depot - Blueprints":      LocData(71302001, "Depot"),
    "Depot - Safe Key":        LocData(71302002, "Depot"),
    "Depot - Blueprints (Agent)": LocData(71312001, "Depot"),
    "Depot - Safe Key (Agent)": LocData(71312002, "Depot"),
    "Depot - Blueprints (Secret Agent)": LocData(71322001, "Depot"),
    "Depot - Safe Key (Secret Agent)": LocData(71322002, "Depot"),
    "Depot - Blueprints (Double Agent)": LocData(71332001, "Depot"),
    "Depot - Safe Key (Double Agent)": LocData(71332002, "Depot"),
}

per_difficulty_clear_locations = {
    "Dam - Agent (Clear)":     LocData(70110001, "Dam"),
    "Facility - Agent (Clear)": LocData(70210001, "Facility"),
    "Runway - Agent (Clear)":  LocData(70310001, "Runway"),
    "Surface 1 - Agent (Clear)": LocData(70410001, "Surface 1"),
    "Bunker 1 - Agent (Clear)": LocData(70510001, "Bunker 1"),
    "Silo - Agent (Clear)":    LocData(70610001, "Silo"),
    "Frigate - Agent (Clear)": LocData(70710001, "Frigate"),
    "Surface 2 - Agent (Clear)": LocData(70810001, "Surface 2"),
    "Bunker 2 - Agent (Clear)": LocData(70910001, "Bunker 2"),
    "Statue - Agent (Clear)":  LocData(71010001, "Statue"),
    "Archives - Agent (Clear)": LocData(71110001, "Archives"),
    "Streets - Agent (Clear)": LocData(71210001, "Streets"),
    "Depot - Agent (Clear)":   LocData(71310001, "Depot"),
    "Train - Agent (Clear)":   LocData(71410001, "Train"),
    "Jungle - Agent (Clear)":  LocData(71510001, "Jungle"),
    "Control - Agent (Clear)": LocData(71610001, "Control"),
    "Caverns - Agent (Clear)": LocData(71710001, "Caverns"),
    "Cradle - Agent (Clear)":  LocData(71810001, "Cradle"),
    "Aztec - Agent (Clear)":   LocData(71910001, "Aztec"),
    "Egyptian - Agent (Clear)": LocData(72010001, "Egyptian"),
    "Dam - Secret Agent (Clear)": LocData(70120001, "Dam"),
    "Facility - Secret Agent (Clear)": LocData(70220001, "Facility"),
    "Runway - Secret Agent (Clear)": LocData(70320001, "Runway"),
    "Surface 1 - Secret Agent (Clear)": LocData(70420001, "Surface 1"),
    "Bunker 1 - Secret Agent (Clear)": LocData(70520001, "Bunker 1"),
    "Silo - Secret Agent (Clear)": LocData(70620001, "Silo"),
    "Frigate - Secret Agent (Clear)": LocData(70720001, "Frigate"),
    "Surface 2 - Secret Agent (Clear)": LocData(70820001, "Surface 2"),
    "Bunker 2 - Secret Agent (Clear)": LocData(70920001, "Bunker 2"),
    "Statue - Secret Agent (Clear)": LocData(71020001, "Statue"),
    "Archives - Secret Agent (Clear)": LocData(71120001, "Archives"),
    "Streets - Secret Agent (Clear)": LocData(71220001, "Streets"),
    "Depot - Secret Agent (Clear)": LocData(71320001, "Depot"),
    "Train - Secret Agent (Clear)": LocData(71420001, "Train"),
    "Jungle - Secret Agent (Clear)": LocData(71520001, "Jungle"),
    "Control - Secret Agent (Clear)": LocData(71620001, "Control"),
    "Caverns - Secret Agent (Clear)": LocData(71720001, "Caverns"),
    "Cradle - Secret Agent (Clear)": LocData(71820001, "Cradle"),
    "Aztec - Secret Agent (Clear)": LocData(71920001, "Aztec"),
    "Egyptian - Secret Agent (Clear)": LocData(72020001, "Egyptian"),
    "Dam - Double Agent (Clear)": LocData(70130001, "Dam"),
    "Facility - Double Agent (Clear)": LocData(70230001, "Facility"),
    "Runway - Double Agent (Clear)": LocData(70330001, "Runway"),
    "Surface 1 - Double Agent (Clear)": LocData(70430001, "Surface 1"),
    "Bunker 1 - Double Agent (Clear)": LocData(70530001, "Bunker 1"),
    "Silo - Double Agent (Clear)": LocData(70630001, "Silo"),
    "Frigate - Double Agent (Clear)": LocData(70730001, "Frigate"),
    "Surface 2 - Double Agent (Clear)": LocData(70830001, "Surface 2"),
    "Bunker 2 - Double Agent (Clear)": LocData(70930001, "Bunker 2"),
    "Statue - Double Agent (Clear)": LocData(71030001, "Statue"),
    "Archives - Double Agent (Clear)": LocData(71130001, "Archives"),
    "Streets - Double Agent (Clear)": LocData(71230001, "Streets"),
    "Depot - Double Agent (Clear)": LocData(71330001, "Depot"),
    "Train - Double Agent (Clear)": LocData(71430001, "Train"),
    "Jungle - Double Agent (Clear)": LocData(71530001, "Jungle"),
    "Control - Double Agent (Clear)": LocData(71630001, "Control"),
    "Caverns - Double Agent (Clear)": LocData(71730001, "Caverns"),
    "Cradle - Double Agent (Clear)": LocData(71830001, "Cradle"),
    "Aztec - Double Agent (Clear)": LocData(71930001, "Aztec"),
    "Egyptian - Double Agent (Clear)": LocData(72030001, "Egyptian"),
}

keypickup_detection_aliases = {
    "Runway - Ignition Key": ('Ignition Key',),
    "Runway - Ignition Key (Agent)": ('Ignition Key', 'Picked up an ignition key.',),
    "Runway - Ignition Key (Secret Agent)": ('Ignition Key', 'Picked up an ignition key.',),
    "Runway - Ignition Key (Double Agent)": ('Ignition Key', 'Picked up an ignition key.',),
    "Surface 1 - Bunker Plans": ('Bunker Plans', 'Picked up Bunker plans.',),
    "Surface 1 - Hut Door Key": ('Hut Door Key', 'Picked up a large key.',),
    "Surface 1 - Bunker Plans (Agent)": ('Bunker Plans', 'Picked up Bunker plans.',),
    "Surface 1 - Hut Door Key (Agent)": ('Hut Door Key', 'Picked up a large key.',),
    "Surface 1 - Bunker Plans (Double Agent)": ('Bunker Plans', 'Picked up Bunker plans.',),
    "Surface 1 - Hut Door Key (Double Agent)": ('Hut Door Key', 'Picked up a large key.',),
    "Surface 1 - Bunker Plans (Secret Agent)": ('Bunker Plans', 'Picked up Bunker plans.',),
    "Surface 1 - Hut Door Key (Secret Agent)": ('Hut Door Key', 'Picked up a large key.',),
    "Bunker 1 - Goldeneye Key": ('Goldeneye Key',),
    "Bunker 1 - Goldeneye Key (Agent)": ('Goldeneye Key',),
    "Bunker 1 - Goldeneye Key (Secret Agent)": ('Goldeneye Key',),
    "Bunker 1 - Goldeneye Key (Double Agent)": ('Goldeneye Key',),
    "Silo - CPU Circuit Board": ('CPU Circuit Board',),
    "Silo - I/O Circuit Board": ('I/O Circuit Board',),
    "Silo - RDP Circuit Board": ('RDP Circuit Board',),
    "Silo - RSP Circuit Board": ('RSP Circuit Board',),
    "Silo - CPU Circuit Board (Agent)": ('CPU Circuit Board',),
    "Silo - I/O Circuit Board (Agent)": ('I/O Circuit Board',),
    "Silo - RDP Circuit Board (Agent)": ('RDP Circuit Board',),
    "Silo - RSP Circuit Board (Agent)": ('RSP Circuit Board',),
    "Silo - CPU Circuit Board (Secret Agent)": ('CPU Circuit Board',),
    "Silo - I/O Circuit Board (Secret Agent)": ('I/O Circuit Board',),
    "Silo - RDP Circuit Board (Secret Agent)": ('RDP Circuit Board',),
    "Silo - RSP Circuit Board (Secret Agent)": ('RSP Circuit Board',),
    "Silo - CPU Circuit Board (Double Agent)": ('CPU Circuit Board',),
    "Silo - I/O Circuit Board (Double Agent)": ('I/O Circuit Board',),
    "Silo - RDP Circuit Board (Double Agent)": ('RDP Circuit Board',),
    "Silo - RSP Circuit Board (Double Agent)": ('RSP Circuit Board',),
    "Surface 2 - Comms Room Key": ('Comms Room Key',),
    "Surface 2 - Comms Room Key (Agent)": ('Comms Room Key', 'Picked up comms room key.',),
    "Surface 2 - Comms Room Key (Secret Agent)": ('Comms Room Key', 'Picked up comms room key.',),
    "Surface 2 - Comms Room Key (Double Agent)": ('Comms Room Key', 'Picked up comms room key.',),
    "Bunker 2 - Casualty List": ('Casualty List',),
    "Bunker 2 - CCTV Tape": ('CCTV Tape',),
    "Bunker 2 - Goldeneye Operations Manual": ('Goldeneye Operations Manual',),
    "Bunker 2 - Staff List": ('Staff List',),
    "Bunker 2 - Cell Key 1": ('Cell Key 1',),
    "Bunker 2 - Safe Key 1": ('Safe Key 1',),
    "Bunker 2 - Safe Key 2": ('Safe Key 2',),
    "Bunker 2 - Casualty List (Agent)": ('Casualty List',),
    "Bunker 2 - CCTV Tape (Agent)": ('CCTV Tape',),
    "Bunker 2 - Goldeneye Operations Manual (Agent)": ('Goldeneye Operations Manual',),
    "Bunker 2 - Staff List (Agent)": ('Staff List',),
    "Bunker 2 - Cell Key 1 (Agent)": ('Cell Key 1',),
    "Bunker 2 - Safe Key 1 (Agent)": ('Safe Key 1',),
    "Bunker 2 - Safe Key 2 (Agent)": ('Safe Key 2',),
    "Bunker 2 - Casualty List (Secret Agent)": ('Casualty List',),
    "Bunker 2 - CCTV Tape (Secret Agent)": ('CCTV Tape',),
    "Bunker 2 - Goldeneye Operations Manual (Secret Agent)": ('Goldeneye Operations Manual',),
    "Bunker 2 - Staff List (Secret Agent)": ('Staff List',),
    "Bunker 2 - Cell Key 1 (Secret Agent)": ('Cell Key 1',),
    "Bunker 2 - Safe Key 1 (Secret Agent)": ('Safe Key 1',),
    "Bunker 2 - Safe Key 2 (Secret Agent)": ('Safe Key 2',),
    "Bunker 2 - Casualty List (Double Agent)": ('Casualty List',),
    "Bunker 2 - CCTV Tape (Double Agent)": ('CCTV Tape',),
    "Bunker 2 - Goldeneye Operations Manual (Double Agent)": ('Goldeneye Operations Manual',),
    "Bunker 2 - Staff List (Double Agent)": ('Staff List',),
    "Bunker 2 - Cell Key 1 (Double Agent)": ('Cell Key 1',),
    "Bunker 2 - Safe Key 1 (Double Agent)": ('Safe Key 1',),
    "Bunker 2 - Safe Key 2 (Double Agent)": ('Safe Key 2',),
    "Statue - Flight Recorder": ('Flight Recorder',),
    "Statue - Flight Recorder (Agent)": ('Flight Recorder',),
    "Statue - Flight Recorder (Secret Agent)": ('Flight Recorder',),
    "Statue - Flight Recorder (Double Agent)": ('Flight Recorder',),
    "Archives - Flight Recorder": ('Flight Recorder',),
    "Archives - Interrogation Room Key": ('Interrogation Room Key',),
    "Archives - Flight Recorder (Agent)": ('Flight Recorder',),
    "Archives - Interrogation Room Key (Agent)": ('Interrogation Room Key',),
    "Archives - Flight Recorder (Secret Agent)": ('Flight Recorder',),
    "Archives - Interrogation Room Key (Secret Agent)": ('Interrogation Room Key',),
    "Archives - Flight Recorder (Double Agent)": ('Flight Recorder',),
    "Archives - Interrogation Room Key (Double Agent)": ('Interrogation Room Key',),
    "Depot - Blueprints": ('Blueprints',),
    "Depot - Safe Key": ('Safe Key',),
    "Depot - Blueprints (Agent)": ('Blueprints',),
    "Depot - Safe Key (Agent)": ('Safe Key',),
    "Depot - Blueprints (Secret Agent)": ('Blueprints',),
    "Depot - Safe Key (Secret Agent)": ('Safe Key',),
    "Depot - Blueprints (Double Agent)": ('Blueprints',),
    "Depot - Safe Key (Double Agent)": ('Safe Key',),
}

shared_clear_locations = {
    "Dam - (Clear)":           LocData(70100001, "Dam"),
    "Facility - (Clear)":      LocData(70200001, "Facility"),
    "Runway - (Clear)":        LocData(70300001, "Runway"),
    "Surface 1 - (Clear)":     LocData(70400001, "Surface 1"),
    "Bunker 1 - (Clear)":      LocData(70500001, "Bunker 1"),
    "Silo - (Clear)":          LocData(70600001, "Silo"),
    "Frigate - (Clear)":       LocData(70700001, "Frigate"),
    "Surface 2 - (Clear)":     LocData(70800001, "Surface 2"),
    "Bunker 2 - (Clear)":      LocData(70900001, "Bunker 2"),
    "Statue - (Clear)":        LocData(71000001, "Statue"),
    "Archives - (Clear)":      LocData(71100001, "Archives"),
    "Streets - (Clear)":       LocData(71200001, "Streets"),
    "Depot - (Clear)":         LocData(71300001, "Depot"),
    "Train - (Clear)":         LocData(71400001, "Train"),
    "Jungle - (Clear)":        LocData(71500001, "Jungle"),
    "Control - (Clear)":       LocData(71600001, "Control"),
    "Caverns - (Clear)":       LocData(71700001, "Caverns"),
    "Cradle - (Clear)":        LocData(71800001, "Cradle"),
    "Aztec - (Clear)":         LocData(71900001, "Aztec"),
    "Egyptian - (Clear)":      LocData(72000001, "Egyptian"),
}

per_difficulty_objective_locations = {
    "Dam - Bungee Jump From Platform (Agent)": LocData(70111001, "Dam"),
    "Dam - Neutralize All Alarms (Secret Agent)": LocData(70121001, "Dam"),
    "Dam - Bungee Jump From Platform (Secret Agent)": LocData(70121002, "Dam"),
    "Dam - Neutralize All Alarms (Double Agent)": LocData(70131001, "Dam"),
    "Dam - Install Covert Modem (Double Agent)": LocData(70131002, "Dam"),
    "Dam - Intercept Data Backup (Double Agent)": LocData(70131003, "Dam"),
    "Dam - Bungee Jump From Platform (Double Agent)": LocData(70131004, "Dam"),
    "Facility - Gain Entry To Laboratory Area (Agent)": LocData(70211001, "Facility"),
    "Facility - Rendezvous With 006 (Agent)": LocData(70211002, "Facility"),
    "Facility - Destroy All Tanks In Bottling Room (Agent)": LocData(70211003, "Facility"),
    "Facility - Minimize Facility Scientist Casualties (Agent)": LocData(70211004, "Facility"),
    "Facility - Gain Entry To Laboratory Area (Secret Agent)": LocData(70221001, "Facility"),
    "Facility - Contact Double Agent (Secret Agent)": LocData(70221002, "Facility"),
    "Facility - Rendezvous With 006 (Secret Agent)": LocData(70221003, "Facility"),
    "Facility - Destroy All Tanks In Bottling Room (Secret Agent)": LocData(70221004, "Facility"),
    "Facility - Minimize Facility Scientist Casualties (Secret Agent)": LocData(70221005, "Facility"),
    "Facility - Gain Entry To Laboratory Area (Double Agent)": LocData(70231001, "Facility"),
    "Facility - Contact Double Agent (Double Agent)": LocData(70231002, "Facility"),
    "Facility - Rendezvous With 006 (Double Agent)": LocData(70231003, "Facility"),
    "Facility - Destroy All Tanks In Bottling Room (Double Agent)": LocData(70231004, "Facility"),
    "Facility - Minimize Facility Scientist Casualties (Double Agent)": LocData(70231005, "Facility"),
    "Runway - Find Plane Ignition Key (Agent)": LocData(70311001, "Runway"),
    "Runway - Escape In Plane (Agent)": LocData(70311002, "Runway"),
    "Runway - Find Plane Ignition Key (Secret Agent)": LocData(70321001, "Runway"),
    "Runway - Destroy Missile Battery (Secret Agent)": LocData(70321002, "Runway"),
    "Runway - Escape In Plane (Secret Agent)": LocData(70321003, "Runway"),
    "Runway - Find Plane Ignition Key (Double Agent)": LocData(70331001, "Runway"),
    "Runway - Destroy Heavy Gun Emplacements (Double Agent)": LocData(70331002, "Runway"),
    "Runway - Destroy Missile Battery (Double Agent)": LocData(70331003, "Runway"),
    "Runway - Escape In Plane (Double Agent)": LocData(70331004, "Runway"),
    "Surface 1 - Enter Base Via Ventilation Tower (Agent)": LocData(70411001, "Surface 1"),
    "Surface 1 - Power Down Communications Dish (Agent)": LocData(70411002, "Surface 1"),
    "Surface 1 - Enter Base Via Ventilation Tower (Secret Agent)": LocData(70421001, "Surface 1"),
    "Surface 1 - Obtain Surface Safe Key (Secret Agent)": LocData(70421002, "Surface 1"),
    "Surface 1 - Power Down Communications Dish (Secret Agent)": LocData(70421003, "Surface 1"),
    "Surface 1 - Steal Building Plans (Secret Agent)": LocData(70421004, "Surface 1"),
    "Surface 1 - Power Down Communications Dish (Double Agent)": LocData(70431001, "Surface 1"),
    "Surface 1 - Obtain Surface Safe Key (Double Agent)": LocData(70431002, "Surface 1"),
    "Surface 1 - Steal Building Plans (Double Agent)": LocData(70431003, "Surface 1"),
    "Surface 1 - Enter Base Via Ventilation Tower (Double Agent)": LocData(70431004, "Surface 1"),
    "Bunker 1 - Copy Goldeneye Key And Leave Original (Agent)": LocData(70511001, "Bunker 1"),
    "Bunker 1 - Photograph Main Video Screen (Agent)": LocData(70511002, "Bunker 1"),
    "Bunker 1 - Disrupt All Surveillance Equipment (Secret Agent)": LocData(70521001, "Bunker 1"),
    "Bunker 1 - Copy Goldeneye Key And Leave Original (Secret Agent)": LocData(70521002, "Bunker 1"),
    "Bunker 1 - Photograph Main Video Screen (Secret Agent)": LocData(70521003, "Bunker 1"),
    "Bunker 1 - Disrupt All Surveillance Equipment (Double Agent)": LocData(70531001, "Bunker 1"),
    "Bunker 1 - Copy Goldeneye Key And Leave Original (Double Agent)": LocData(70531002, "Bunker 1"),
    "Bunker 1 - Get Personnel To Activate Computer (Double Agent)": LocData(70531003, "Bunker 1"),
    "Bunker 1 - Download Data From Computer (Double Agent)": LocData(70531004, "Bunker 1"),
    "Bunker 1 - Photograph Main Video Screen (Double Agent)": LocData(70531005, "Bunker 1"),
    "Silo - Photograph Satellite (Agent)": LocData(70611001, "Silo"),
    "Silo - Minimize Silo Scientist Casualties (Agent)": LocData(70611002, "Silo"),
    "Silo - Photograph Satellite (Secret Agent)": LocData(70621001, "Silo"),
    "Silo - Obtain Telemetric Data (Secret Agent)": LocData(70621002, "Silo"),
    "Silo - Retrieve Satellite Circuitry (Secret Agent)": LocData(70621003, "Silo"),
    "Silo - Minimize Silo Scientist Casualties (Secret Agent)": LocData(70621004, "Silo"),
    "Silo - Plant Bombs In Fuel Rooms (Double Agent)": LocData(70631001, "Silo"),
    "Silo - Photograph Satellite (Double Agent)": LocData(70631002, "Silo"),
    "Silo - Obtain Telemetric Data (Double Agent)": LocData(70631003, "Silo"),
    "Silo - Retrieve Satellite Circuitry (Double Agent)": LocData(70631004, "Silo"),
    "Silo - Minimize Silo Scientist Casualties (Double Agent)": LocData(70631005, "Silo"),
    "Frigate - Rescue Hostages (Agent)": LocData(70711001, "Frigate"),
    "Frigate - Plant Tracking Bug On Helicopter (Agent)": LocData(70711002, "Frigate"),
    "Frigate - Rescue Hostages (Secret Agent)": LocData(70721001, "Frigate"),
    "Frigate - Disarm Bridge Bomb (Secret Agent)": LocData(70721002, "Frigate"),
    "Frigate - Disarm Engine Room Bomb (Secret Agent)": LocData(70721003, "Frigate"),
    "Frigate - Plant Tracking Bug On Helicopter (Secret Agent)": LocData(70721004, "Frigate"),
    "Frigate - Rescue Hostages (Double Agent)": LocData(70731001, "Frigate"),
    "Frigate - Disarm Bridge Bomb (Double Agent)": LocData(70731002, "Frigate"),
    "Frigate - Disarm Engine Room Bomb (Double Agent)": LocData(70731003, "Frigate"),
    "Frigate - Plant Tracking Bug On Helicopter (Double Agent)": LocData(70731004, "Frigate"),
    "Surface 2 - Break Communications Link To Bunker (Agent)": LocData(70811001, "Surface 2"),
    "Surface 2 - Gain Entry To Bunker (Agent)": LocData(70811002, "Surface 2"),
    "Surface 2 - Break Communications Link To Bunker (Secret Agent)": LocData(70821001, "Surface 2"),
    "Surface 2 - Disable Spetznaz Support Aircraft (Secret Agent)": LocData(70821002, "Surface 2"),
    "Surface 2 - Gain Entry To Bunker (Secret Agent)": LocData(70821003, "Surface 2"),
    "Surface 2 - Disrupt All Surveillance Equipment (Double Agent)": LocData(70831001, "Surface 2"),
    "Surface 2 - Break Communications Link To Bunker (Double Agent)": LocData(70831002, "Surface 2"),
    "Surface 2 - Disable Spetznaz Support Aircraft (Double Agent)": LocData(70831003, "Surface 2"),
    "Surface 2 - Gain Entry To Bunker (Double Agent)": LocData(70831004, "Surface 2"),
    "Bunker 2 - Recover CCTV Tape (Agent)": LocData(70911001, "Bunker 2"),
    "Bunker 2 - Escape With Natalya (Agent)": LocData(70911002, "Bunker 2"),
    "Bunker 2 - Recover CCTV Tape (Secret Agent)": LocData(70921001, "Bunker 2"),
    "Bunker 2 - Compare Staff/Casualty Lists (Secret Agent)": LocData(70921002, "Bunker 2"),
    "Bunker 2 - Disable All Security Cameras (Secret Agent)": LocData(70921003, "Bunker 2"),
    "Bunker 2 - Escape With Natalya (Secret Agent)": LocData(70921004, "Bunker 2"),
    "Bunker 2 - Compare Staff/Casualty Lists (Double Agent)": LocData(70931001, "Bunker 2"),
    "Bunker 2 - Recover CCTV Tape (Double Agent)": LocData(70931002, "Bunker 2"),
    "Bunker 2 - Disable All Security Cameras (Double Agent)": LocData(70931003, "Bunker 2"),
    "Bunker 2 - Recover Goldeneye Operations Manual (Double Agent)": LocData(70931004, "Bunker 2"),
    "Bunker 2 - Escape With Natalya (Double Agent)": LocData(70931005, "Bunker 2"),
    "Statue - Contact Valentin (Agent)": LocData(71011001, "Statue"),
    "Statue - Confront And Unmask Janus (Agent)": LocData(71011002, "Statue"),
    "Statue - Find Flight Recorder (Agent)": LocData(71011003, "Statue"),
    "Statue - Locate Helicopter (Agent)": LocData(71011004, "Statue"),
    "Statue - Rescue Natalya (Agent)": LocData(71011005, "Statue"),
    "Statue - Contact Valentin (Secret Agent)": LocData(71021001, "Statue"),
    "Statue - Confront And Unmask Janus (Secret Agent)": LocData(71021002, "Statue"),
    "Statue - Find Flight Recorder (Secret Agent)": LocData(71021003, "Statue"),
    "Statue - Locate Helicopter (Secret Agent)": LocData(71021004, "Statue"),
    "Statue - Rescue Natalya (Secret Agent)": LocData(71021005, "Statue"),
    "Statue - Contact Valentin (Double Agent)": LocData(71031001, "Statue"),
    "Statue - Confront And Unmask Janus (Double Agent)": LocData(71031002, "Statue"),
    "Statue - Locate Helicopter (Double Agent)": LocData(71031003, "Statue"),
    "Statue - Rescue Natalya (Double Agent)": LocData(71031004, "Statue"),
    "Statue - Find Flight Recorder (Double Agent)": LocData(71031005, "Statue"),
    "Archives - Escape From Interrogation Room (Agent)": LocData(71111001, "Archives"),
    "Archives - Find Natalya (Agent)": LocData(71111003, "Archives"),
    "Archives - Escape With Natalya Again (Agent)": LocData(71111002, "Archives"),
    "Archives - Escape From Interrogation Room (Secret Agent)": LocData(71121004, "Archives"),
    "Archives - Find Natalya (Secret Agent)": LocData(71121002, "Archives"),
    "Archives - Recover Helicopter Black Box (Secret Agent)": LocData(71121003, "Archives"),
    "Archives - Escape With Natalya Again (Secret Agent)": LocData(71121001, "Archives"),
    "Archives - Escape From Interrogation Room (Double Agent)": LocData(71131001, "Archives"),
    "Archives - Find Natalya (Double Agent)": LocData(71131002, "Archives"),
    "Archives - Recover Helicopter Black Box (Double Agent)": LocData(71131003, "Archives"),
    "Archives - Escape With Natalya Again (Double Agent)": LocData(71131004, "Archives"),
    "Streets - Pursue Ouromov And Natalya (Agent)": LocData(71211001, "Streets"),
    "Streets - Minimize Civilian Casualties (Agent)": LocData(71211002, "Streets"),
    "Streets - Contact Valentin Again (Secret Agent)": LocData(71221001, "Streets"),
    "Streets - Pursue Ouromov And Natalya (Secret Agent)": LocData(71221002, "Streets"),
    "Streets - Minimize Civilian Casualties (Secret Agent)": LocData(71221003, "Streets"),
    "Streets - Contact Valentin Again (Double Agent)": LocData(71231001, "Streets"),
    "Streets - Pursue Ouromov And Natalya (Double Agent)": LocData(71231002, "Streets"),
    "Streets - Minimize Civilian Casualties (Double Agent)": LocData(71231003, "Streets"),
    "Depot - Locate Trevelyn's Train (Agent)": LocData(71311001, "Depot"),
    "Depot - Destroy Computer Network (Secret Agent)": LocData(71321001, "Depot"),
    "Depot - Obtain Depot Safe Key (Secret Agent)": LocData(71321002, "Depot"),
    "Depot - Recover Helicopter Blueprints (Secret Agent)": LocData(71321003, "Depot"),
    "Depot - Locate Trevelyn's Train (Secret Agent)": LocData(71321004, "Depot"),
    "Depot - Destroy Illegal Arms Cache (Double Agent)": LocData(71331001, "Depot"),
    "Depot - Destroy Computer Network (Double Agent)": LocData(71331002, "Depot"),
    "Depot - Obtain Depot Safe Key (Double Agent)": LocData(71331003, "Depot"),
    "Depot - Recover Helicopter Blueprints (Double Agent)": LocData(71331004, "Depot"),
    "Depot - Locate Trevelyn's Train (Double Agent)": LocData(71331005, "Depot"),
    "Train - Destroy Brake Units (Agent)": LocData(71411001, "Train"),
    "Train - Rescue Natalya Again (Agent)": LocData(71411002, "Train"),
    "Train - Escape To Safety (Agent)": LocData(71411003, "Train"),
    "Train - Destroy Brake Units (Secret Agent)": LocData(71421001, "Train"),
    "Train - Rescue Natalya Again (Secret Agent)": LocData(71421002, "Train"),
    "Train - Locate Janus Secret Base (Secret Agent)": LocData(71421003, "Train"),
    "Train - Escape To Safety (Secret Agent)": LocData(71421004, "Train"),
    "Train - Destroy Brake Units (Double Agent)": LocData(71431001, "Train"),
    "Train - Rescue Natalya Again (Double Agent)": LocData(71431002, "Train"),
    "Train - Locate Janus Secret Base (Double Agent)": LocData(71431003, "Train"),
    "Train - Crack Boris' Password (Double Agent)": LocData(71431004, "Train"),
    "Train - Escape To Safety (Double Agent)": LocData(71431005, "Train"),
    "Jungle - Destroy Drone Guns (Agent)": LocData(71511001, "Jungle"),
    "Jungle - Eliminate Xenia (Agent)": LocData(71511002, "Jungle"),
    "Jungle - Escort Natalya To Janus Base (Agent)": LocData(71511003, "Jungle"),
    "Jungle - Destroy Drone Guns (Secret Agent)": LocData(71521001, "Jungle"),
    "Jungle - Eliminate Xenia (Secret Agent)": LocData(71521002, "Jungle"),
    "Jungle - Blow Up Ammo Dump (Secret Agent)": LocData(71521003, "Jungle"),
    "Jungle - Escort Natalya To Janus Base (Secret Agent)": LocData(71521004, "Jungle"),
    "Jungle - Destroy Drone Guns (Double Agent)": LocData(71531001, "Jungle"),
    "Jungle - Eliminate Xenia (Double Agent)": LocData(71531002, "Jungle"),
    "Jungle - Blow Up Ammo Dump (Double Agent)": LocData(71531003, "Jungle"),
    "Jungle - Escort Natalya To Janus Base (Double Agent)": LocData(71531004, "Jungle"),
    "Control - Protect Natalya (Agent)": LocData(71611001, "Control"),
    "Control - Disable Goldeneye Satellite (Agent)": LocData(71611002, "Control"),
    "Control - Destroy Armored Mainframes (Agent)": LocData(71611003, "Control"),
    "Control - Protect Natalya (Secret Agent)": LocData(71621001, "Control"),
    "Control - Disable Goldeneye Satellite (Secret Agent)": LocData(71621002, "Control"),
    "Control - Destroy Armored Mainframes (Secret Agent)": LocData(71621003, "Control"),
    "Control - Protect Natalya (Double Agent)": LocData(71631001, "Control"),
    "Control - Disable Goldeneye Satellite (Double Agent)": LocData(71631002, "Control"),
    "Control - Destroy Armored Mainframes (Double Agent)": LocData(71631003, "Control"),
    "Caverns - Minimize Caverns Scientist Casualties (Agent)": LocData(71711001, "Caverns"),
    "Caverns - Destroy Inlet Pump Controls (Secret Agent)": LocData(71721001, "Caverns"),
    "Caverns - Destroy Outlet Pump controls (Secret Agent)": LocData(71721002, "Caverns"),
    "Caverns - Destroy Master Control Console (Secret Agent)": LocData(71721003, "Caverns"),
    "Caverns - Minimize Caverns Scientist Casualties (Secret Agent)": LocData(71721004, "Caverns"),
    "Caverns - Destroy Inlet Pump Controls (Double Agent)": LocData(71731001, "Caverns"),
    "Caverns - Destroy Outlet Pump controls (Double Agent)": LocData(71731002, "Caverns"),
    "Caverns - Destroy Master Control Console (Double Agent)": LocData(71731003, "Caverns"),
    "Caverns - Use Radio To Contact Jack Wade (Double Agent)": LocData(71731004, "Caverns"),
    "Caverns - Minimize Caverns Scientist Casualties (Double Agent)": LocData(71731005, "Caverns"),
    "Cradle - Destroy Control Console (Agent)": LocData(71811001, "Cradle"),
    "Cradle - Settle The Score With Trevelyan (Agent)": LocData(71811002, "Cradle"),
    "Cradle - Destroy Control Console (Secret Agent)": LocData(71821001, "Cradle"),
    "Cradle - Settle The Score With Trevelyan (Secret Agent)": LocData(71821002, "Cradle"),
    "Cradle - Destroy Control Console (Double Agent)": LocData(71831001, "Cradle"),
    "Cradle - Settle The Score With Trevelyan (Double Agent)": LocData(71831002, "Cradle"),
    "Aztec - Reprogram Shuttle Guidance (Agent)": LocData(71911001, "Aztec"),
    "Aztec - Launch Shuttle (Agent)": LocData(71911002, "Aztec"),
    "Aztec - Reprogram Shuttle Guidance (Secret Agent)": LocData(71921001, "Aztec"),
    "Aztec - Launch Shuttle (Secret Agent)": LocData(71921002, "Aztec"),
    "Aztec - Reprogram Shuttle Guidance (Double Agent)": LocData(71931001, "Aztec"),
    "Aztec - Launch Shuttle (Double Agent)": LocData(71931002, "Aztec"),
    "Egyptian - Recover the Golden Gun (Agent)": LocData(72011001, "Egyptian"),
    "Egyptian - Defeat Baron Samedi? (Agent)": LocData(72011002, "Egyptian"),
    "Egyptian - Recover the Golden Gun (Secret Agent)": LocData(72021001, "Egyptian"),
    "Egyptian - Defeat Baron Samedi? (Secret Agent)": LocData(72021002, "Egyptian"),
    "Egyptian - Recover the Golden Gun (Double Agent)": LocData(72031001, "Egyptian"),
    "Egyptian - Defeat Baron Samedi? (Double Agent)": LocData(72031002, "Egyptian"),
}

shared_objective_locations = {
    "Dam - Neutralize All Alarms": LocData(70101001, "Dam"),
    "Dam - Install Covert Modem": LocData(70101002, "Dam"),
    "Dam - Intercept Data Backup": LocData(70101003, "Dam"),
    "Dam - Bungee Jump From Platform": LocData(70101004, "Dam"),
    "Facility - Gain Entry To Laboratory Area": LocData(70201001, "Facility"),
    "Facility - Contact Double Agent": LocData(70201002, "Facility"),
    "Facility - Rendezvous With 006": LocData(70201003, "Facility"),
    "Facility - Destroy All Tanks In Bottling Room": LocData(70201004, "Facility"),
    "Facility - Minimize Facility Scientist Casualties": LocData(70201005, "Facility"),
    "Runway - Find Plane Ignition Key": LocData(70301001, "Runway"),
    "Runway - Destroy Heavy Gun Emplacements": LocData(70301002, "Runway"),
    "Runway - Destroy Missile Battery": LocData(70301003, "Runway"),
    "Runway - Escape In Plane": LocData(70301004, "Runway"),
    "Surface 1 - Power Down Communications Dish": LocData(70401001, "Surface 1"),
    "Surface 1 - Obtain Surface Safe Key": LocData(70401002, "Surface 1"),
    "Surface 1 - Steal Building Plans": LocData(70401003, "Surface 1"),
    "Surface 1 - Enter Base Via Ventilation Tower": LocData(70401004, "Surface 1"),
    "Bunker 1 - Disrupt All Surveillance Equipment": LocData(70501001, "Bunker 1"),
    "Bunker 1 - Copy Goldeneye Key And Leave Original": LocData(70501002, "Bunker 1"),
    "Bunker 1 - Get Personnel To Activate Computer": LocData(70501003, "Bunker 1"),
    "Bunker 1 - Download Data From Computer": LocData(70501004, "Bunker 1"),
    "Bunker 1 - Photograph Main Video Screen": LocData(70501005, "Bunker 1"),
    "Silo - Plant Bombs In Fuel Rooms": LocData(70601001, "Silo"),
    "Silo - Photograph Satellite": LocData(70601002, "Silo"),
    "Silo - Obtain Telemetric Data": LocData(70601003, "Silo"),
    "Silo - Retrieve Satellite Circuitry": LocData(70601004, "Silo"),
    "Silo - Minimize Silo Scientist Casualties": LocData(70601005, "Silo"),
    "Frigate - Rescue Hostages": LocData(70701001, "Frigate"),
    "Frigate - Disarm Bridge Bomb": LocData(70701002, "Frigate"),
    "Frigate - Disarm Engine Room Bomb": LocData(70701003, "Frigate"),
    "Frigate - Plant Tracking Bug On Helicopter": LocData(70701004, "Frigate"),
    "Surface 2 - Disrupt All Surveillance Equipment": LocData(70801001, "Surface 2"),
    "Surface 2 - Break Communications Link To Bunker": LocData(70801002, "Surface 2"),
    "Surface 2 - Disable Spetznaz Support Aircraft": LocData(70801003, "Surface 2"),
    "Surface 2 - Gain Entry To Bunker": LocData(70801004, "Surface 2"),
    "Bunker 2 - Compare Staff/Casualty Lists": LocData(70901001, "Bunker 2"),
    "Bunker 2 - Recover CCTV Tape": LocData(70901002, "Bunker 2"),
    "Bunker 2 - Disable All Security Cameras": LocData(70901003, "Bunker 2"),
    "Bunker 2 - Recover Goldeneye Operations Manual": LocData(70901004, "Bunker 2"),
    "Bunker 2 - Escape With Natalya": LocData(70901005, "Bunker 2"),
    "Statue - Contact Valentin": LocData(71001001, "Statue"),
    "Statue - Confront And Unmask Janus": LocData(71001002, "Statue"),
    "Statue - Locate Helicopter": LocData(71001003, "Statue"),
    "Statue - Rescue Natalya": LocData(71001004, "Statue"),
    "Statue - Find Flight Recorder": LocData(71001005, "Statue"),
    "Archives - Escape From Interrogation Room": LocData(71101001, "Archives"),
    "Archives - Find Natalya": LocData(71101002, "Archives"),
    "Archives - Recover Helicopter Black Box": LocData(71101003, "Archives"),
    "Archives - Escape With Natalya Again": LocData(71101004, "Archives"),
    "Streets - Contact Valentin Again": LocData(71201001, "Streets"),
    "Streets - Pursue Ouromov And Natalya": LocData(71201002, "Streets"),
    "Streets - Minimize Civilian Casualties": LocData(71201003, "Streets"),
    "Depot - Destroy Illegal Arms Cache": LocData(71301001, "Depot"),
    "Depot - Destroy Computer Network": LocData(71301002, "Depot"),
    "Depot - Obtain Depot Safe Key": LocData(71301003, "Depot"),
    "Depot - Recover Helicopter Blueprints": LocData(71301004, "Depot"),
    "Depot - Locate Trevelyn's Train": LocData(71301005, "Depot"),
    "Train - Destroy Brake Units": LocData(71401001, "Train"),
    "Train - Rescue Natalya Again": LocData(71401002, "Train"),
    "Train - Locate Janus Secret Base": LocData(71401003, "Train"),
    "Train - Crack Boris' Password": LocData(71401004, "Train"),
    "Train - Escape To Safety": LocData(71401005, "Train"),
    "Jungle - Destroy Drone Guns": LocData(71501001, "Jungle"),
    "Jungle - Eliminate Xenia": LocData(71501002, "Jungle"),
    "Jungle - Blow Up Ammo Dump": LocData(71501003, "Jungle"),
    "Jungle - Escort Natalya To Janus Base": LocData(71501004, "Jungle"),
    "Control - Protect Natalya": LocData(71601001, "Control"),
    "Control - Disable Goldeneye Satellite": LocData(71601002, "Control"),
    "Control - Destroy Armored Mainframes": LocData(71601003, "Control"),
    "Caverns - Destroy Inlet Pump Controls": LocData(71701001, "Caverns"),
    "Caverns - Destroy Outlet Pump controls": LocData(71701002, "Caverns"),
    "Caverns - Destroy Master Control Console": LocData(71701003, "Caverns"),
    "Caverns - Use Radio To Contact Jack Wade": LocData(71701004, "Caverns"),
    "Caverns - Minimize Caverns Scientist Casualties": LocData(71701005, "Caverns"),
    "Cradle - Destroy Control Console": LocData(71801001, "Cradle"),
    "Cradle - Settle The Score With Trevelyan": LocData(71801002, "Cradle"),
    "Aztec - Reprogram Shuttle Guidance": LocData(71901001, "Aztec"),
    "Aztec - Launch Shuttle":  LocData(71901002, "Aztec"),
    "Egyptian - Recover the Golden Gun": LocData(72001001, "Egyptian"),
    "Egyptian - Defeat Baron Samedi?": LocData(72001002, "Egyptian"),
}

extra_locations = {
    "Aztec - Security Smart Card": LocData(71902002, "Aztec"),
    "Aztec - Launch Protocol Data": LocData(71902003, "Aztec"),
    "Aztec - Security Smart Card (Agent)": LocData(71912002, "Aztec"),
    "Aztec - Launch Protocol Data (Agent)": LocData(71912003, "Aztec"),
    "Aztec - Launch Protocol Data (Secret Agent)": LocData(71922003, "Aztec"),
    "Aztec - Security Smart Card (Secret Agent)": LocData(71922002, "Aztec"),
    "Aztec - Launch Protocol Data (Double Agent)": LocData(71932003, "Aztec"),
    "Aztec - Security Smart Card (Double Agent)": LocData(71932002, "Aztec"),
    "Aztec - Body Armor (Inside Turret Tunnels)": LocData(71905003, "Aztec"),
    "Aztec - Body Armor (Inside Turret Tunnels) (Agent)": LocData(71915003, "Aztec"),
    "Aztec - Body Armor (Inside Turret Tunnels) (Secret Agent)": LocData(71925003, "Aztec"),
    "Aztec - Body Armor (Inside Turret Tunnels) (Double Agent)": LocData(71935003, "Aztec"),
    "Aztec - Cheat - 2x Laser": LocData(71903001, "Aztec"),
    "Egyptian - Golden Gun":   LocData(72004001, "Egyptian"),
    "Egyptian - Golden Gun (Agent)": LocData(72014001, "Egyptian"),
    "Egyptian - Golden Gun (Secret Agent)": LocData(72024001, "Egyptian"),
    "Egyptian - Golden Gun (Double Agent)": LocData(72034001, "Egyptian"),
    "Egyptian - Body Armor (Corridor North West of Start)": LocData(72005001, "Egyptian"),
    "Egyptian - Body Armor (Corridor North West of Start) (Agent)": LocData(72015001, "Egyptian"),
    "Egyptian - Body Armor (After Golden Gun)": LocData(72005002, "Egyptian"),
    "Egyptian - Body Armor (After Golden Gun) (Agent)": LocData(72015002, "Egyptian"),
    "Egyptian - Body Armor (Left of Secret Corridor)": LocData(72005003, "Egyptian"),
    "Egyptian - Body Armor (Left of Secret Corridor) (Agent)": LocData(72015003, "Egyptian"),
    "Egyptian - Body Armor (Corridor North West of Start) (Secret Agent)": LocData(72025001, "Egyptian"),
    "Egyptian - Body Armor (After Golden Gun) (Secret Agent)": LocData(72025002, "Egyptian"),
    "Egyptian - Body Armor (Left of Secret Corridor) (Secret Agent)": LocData(72025003, "Egyptian"),
    "Egyptian - Body Armor (Corridor North West of Start) (Double Agent)": LocData(72035001, "Egyptian"),
    "Egyptian - Body Armor (After Golden Gun) (Double Agent)": LocData(72035002, "Egyptian"),
    "Egyptian - Body Armor (Left of Secret Corridor) (Double Agent)": LocData(72035003, "Egyptian"),
    "Egyptian - Cheat - All Guns": LocData(72003001, "Egyptian"),
    "Egyptian - Golden Gun Ammo": LocData(72006001, "Egyptian"),
    "Egyptian - Golden Gun Ammo (Agent)": LocData(72016001, "Egyptian"),
    "Egyptian - Golden Gun Ammo (Secret Agent)": LocData(72026001, "Egyptian"),
    "Egyptian - Golden Gun Ammo (Double Agent)": LocData(72036001, "Egyptian"),
}

event_locations = {
}


def _split_difficulty_suffix(name: str) -> tuple[str, int] | None:
    for difficulty_name, difficulty_code in (("Agent", 1), ("Secret Agent", 2), ("Double Agent", 3)):
        suffix = f" ({difficulty_name})"
        if name.endswith(suffix):
            return name[:-len(suffix)], difficulty_code
    return None


def _build_location_mode_tables(raw_locations: Dict[str, LocData]):
    shared_names = {data.ap_code: name for name, data in raw_locations.items()
                    if _split_difficulty_suffix(name) is None}
    grouped = {}
    for name, data in raw_locations.items():
        parsed = _split_difficulty_suffix(name)
        if parsed is None:
            entry = grouped.setdefault(name, {"shared": None, "per_difficulty": {}})
            entry["shared"] = (name, data)
            continue
        base_name, difficulty_code = parsed
        base_name = shared_names.get(data.ap_code - difficulty_code * 10000, base_name)
        entry = grouped.setdefault(base_name, {"shared": None, "per_difficulty": {}})
        entry["per_difficulty"][difficulty_code] = (name, data)

    always_on = {}
    shared = {}
    per_difficulty = {}
    shared_groups = {}
    for base_name, entry in grouped.items():
        if not entry["per_difficulty"]:
            if entry["shared"] is not None:
                shared_name, shared_data = entry["shared"]
                always_on[shared_name] = shared_data
            continue

        for difficulty_code in sorted(entry["per_difficulty"]):
            per_name, per_data = entry["per_difficulty"][difficulty_code]
            per_difficulty[per_name] = per_data

        if entry["shared"] is not None:
            shared_name, shared_data = entry["shared"]
        else:
            first_difficulty = min(entry["per_difficulty"])
            _, first_data = entry["per_difficulty"][first_difficulty]
            shared_name = base_name
            shared_data = LocData(first_data.ap_code - (first_difficulty * 10000), first_data.region)

        shared[shared_name] = shared_data
        shared_groups[shared_name] = [
            entry["per_difficulty"][difficulty_code][0]
            for difficulty_code in sorted(entry["per_difficulty"])
        ]

    return always_on, shared, per_difficulty, shared_groups


def _build_keypickup_alias_tables(raw_aliases, shared_groups):
    shared_aliases = {}
    per_difficulty_aliases = dict(raw_aliases)
    for shared_name, per_names in shared_groups.items():
        aliases = []
        seen = set()
        base_alias = shared_name.split(" - ", 1)[1] if " - " in shared_name else shared_name
        for alias in (base_alias,):
            lowered = alias.lower()
            if lowered not in seen:
                seen.add(lowered)
                aliases.append(alias)
        for source_name in [shared_name, *per_names]:
            for alias in raw_aliases.get(source_name, ()):
                lowered = alias.lower()
                if lowered in seen:
                    continue
                seen.add(lowered)
                aliases.append(alias)
        if aliases:
            shared_aliases[shared_name] = tuple(aliases)
    return shared_aliases, per_difficulty_aliases


raw_goldeneye_locations = {**goldeneye_locations, **extra_locations}
raw_keypickup_locations = keypickup_locations
raw_keypickup_detection_aliases = keypickup_detection_aliases

(
    always_on_item_locations,
    shared_item_locations,
    per_difficulty_item_locations,
    ITEM_SHARED_LOCATION_GROUPS,
) = _build_location_mode_tables(raw_goldeneye_locations)
(
    always_on_keypickup_locations,
    shared_keypickup_locations,
    per_difficulty_keypickup_locations,
    KEYPICKUP_SHARED_LOCATION_GROUPS,
) = _build_location_mode_tables(raw_keypickup_locations)
(
    shared_keypickup_detection_aliases,
    per_difficulty_keypickup_detection_aliases,
) = _build_keypickup_alias_tables(raw_keypickup_detection_aliases, KEYPICKUP_SHARED_LOCATION_GROUPS)

goldeneye_locations = {
    **always_on_item_locations,
    **shared_item_locations,
    **per_difficulty_item_locations,
}
keypickup_locations = {
    **always_on_keypickup_locations,
    **shared_keypickup_locations,
    **per_difficulty_keypickup_locations,
}
keypickup_detection_aliases = {
    **shared_keypickup_detection_aliases,
    **per_difficulty_keypickup_detection_aliases,
}

location_table = {
    **goldeneye_locations,
    **keypickup_locations,
    **per_difficulty_clear_locations,
    **shared_clear_locations,
    **per_difficulty_objective_locations,
    **shared_objective_locations,
    **extra_locations,
    **event_locations,
}
