# Auto-generated by codegen.py — do not edit manually
# Generated: 2026-04-22 20:46:20
# Generated file exception:
# This file is machine-written from sheet data, so it may use compact Python.
# We keep the sheet-driven structure here because codegen.py rebuilds it.
# This is safe because codegen.py rebuilds this file from the same source data.

from typing import Dict, TYPE_CHECKING
from .Types import LocData

if TYPE_CHECKING:
    from . import GoldeneyeWorld

MISSION_CLEAR_MODE_PER_MAP = 2
MISSION_CLEAR_MODE_PER_DIFFICULTY = 1
OBJECTIVE_MODE_PER_DIFFICULTY = 1
OBJECTIVE_MODE_SHARED = 2
ITEM_SHUFFLE_MODE_SHARED = 2
ITEM_SHUFFLE_MODE_PER_DIFFICULTY = 1
EXTRA_MISSION_NAMES = ('Aztec', 'Egyptian')
EXTRA_MISSION_REGIONS = EXTRA_MISSION_NAMES
EXTRA_MISSION_SELECTIONS = {
    1: {"Aztec"},
    2: {"Egyptian"},
    3: {"Aztec", "Egyptian"},
    4: {},
}


def get_enabled_extra_missions(world: "GoldeneyeWorld") -> set[str]:
    return EXTRA_MISSION_SELECTIONS[world.options.extra_locations.value]


def is_enabled_extra_region(world: "GoldeneyeWorld", region_name: str) -> bool:
    return (
        region_name not in EXTRA_MISSION_REGIONS
        or region_name in get_enabled_extra_missions(world)
    )


def get_item_shuffle_mode(world: "GoldeneyeWorld") -> int:
    item_shuffle = getattr(world.options, "item_shuffle", None)
    if item_shuffle is None:
        return ITEM_SHUFFLE_MODE_SHARED
    return item_shuffle.value


def get_total_locations(world: "GoldeneyeWorld") -> int:
    return sum(
        1
        for name, data in location_table.items()
        if name not in event_locations
        and is_enabled_extra_region(world, data.region)
        and is_valid_location(world, name)
    )


def get_location_names() -> Dict[str, int]:
    return {name: data.ap_code for name, data in location_table.items() if data.ap_code is not None}


def is_valid_location(world: "GoldeneyeWorld", name: str) -> bool:
    if not is_enabled_extra_region(world, location_table[name].region):
        return False
    if name in per_difficulty_item_locations:
        return get_item_shuffle_mode(world) == ITEM_SHUFFLE_MODE_PER_DIFFICULTY
    if name in shared_item_locations:
        return get_item_shuffle_mode(world) == ITEM_SHUFFLE_MODE_SHARED
    if name in per_difficulty_keypickup_locations:
        return get_item_shuffle_mode(world) == ITEM_SHUFFLE_MODE_PER_DIFFICULTY
    if name in shared_keypickup_locations:
        return get_item_shuffle_mode(world) == ITEM_SHUFFLE_MODE_SHARED
    if name in per_difficulty_clear_locations:
        return world.options.mission_clear_mode.value == MISSION_CLEAR_MODE_PER_DIFFICULTY
    if name in shared_clear_locations:
        return world.options.mission_clear_mode.value == MISSION_CLEAR_MODE_PER_MAP
    if name in per_difficulty_objective_locations:
        return world.options.objective_mode.value == OBJECTIVE_MODE_PER_DIFFICULTY
    if name in shared_objective_locations:
        return world.options.objective_mode.value == OBJECTIVE_MODE_SHARED
    return True


goldeneye_locations = {
    "Dam - Sniper Rifle":      LocData(70104001, "Dam"),
    "Dam - Sniper Rifle (Agent)": LocData(70114001, "Dam"),
    "Dam - Sniper Rifle (Secret Agent)": LocData(70124001, "Dam"),
    "Dam - Sniper Rifle (Double Agent)": LocData(70134001, "Dam"),
    "Facility - Keycard A":    LocData(70202001, "Facility"),
    "Facility - Keycard B":    LocData(70202002, "Facility"),
    "Facility - Door Decoder": LocData(70202003, "Facility"),
    "Facility - Keycard A (Agent)": LocData(70212001, "Facility"),
    "Facility - Keycard B (Agent)": LocData(70212002, "Facility"),
    "Facility - Door Decoder (Agent)": LocData(70212003, "Facility"),
    "Facility - Keycard A (Secret Agent)": LocData(70222001, "Facility"),
    "Facility - Keycard B (Secret Agent)": LocData(70222002, "Facility"),
    "Facility - Door Decoder (Secret Agent)": LocData(70222003, "Facility"),
    "Facility - Keycard A (Double Agent)": LocData(70232001, "Facility"),
    "Facility - Keycard B (Double Agent)": LocData(70232002, "Facility"),
    "Facility - Door Decoder (Double Agent)": LocData(70232003, "Facility"),
    "Surface 1 - Safe Key (Agent)": LocData(70412003, "Surface 1"),
    "Surface 1 - Safe Key (Double Agent)": LocData(70432003, "Surface 1"),
    "Surface 1 - Safe Key (Secret Agent)": LocData(70422003, "Surface 1"),
    "Surface 1 - Grenade Launcher": LocData(70404001, "Surface 1"),
    "Surface 1 - Grenade Launcher (Agent)": LocData(70414001, "Surface 1"),
    "Surface 1 - Grenade Launcher (Secret Agent)": LocData(70424001, "Surface 1"),
    "Surface 1 - Grenade Launcher (Double Agent)": LocData(70434001, "Surface 1"),
    "Bunker 1 - Computer Room Keycard (Agent)": LocData(70512002, "Bunker 1"),
    "Bunker 1 - Security Keycard (Agent)": LocData(70512003, "Bunker 1"),
    "Bunker 1 - Computer Room Keycard (Secret Agent)": LocData(70522002, "Bunker 1"),
    "Bunker 1 - Security Keycard (Secret Agent)": LocData(70522003, "Bunker 1"),
    "Bunker 1 - Computer Room Keycard (Double Agent)": LocData(70532002, "Bunker 1"),
    "Bunker 1 - Security Keycard (Double Agent)": LocData(70532003, "Bunker 1"),
    "Silo - DAT (Agent)":      LocData(70612002, "Silo"),
    "Silo - Keycard Silo Level 1 (Agent)": LocData(70612006, "Silo"),
    "Silo - Keycard Silo Level 2 (Agent)": LocData(70612007, "Silo"),
    "Silo - Keycard Silo Level 3 (Agent)": LocData(70612008, "Silo"),
    "Silo - DAT (Secret Agent)": LocData(70622002, "Silo"),
    "Silo - Keycard Silo Level 1 (Secret Agent)": LocData(70622006, "Silo"),
    "Silo - Keycard Silo Level 2 (Secret Agent)": LocData(70622007, "Silo"),
    "Silo - Keycard Silo Level 3 (Secret Agent)": LocData(70622008, "Silo"),
    "Silo - DAT (Double Agent)": LocData(70632002, "Silo"),
    "Silo - Keycard Silo Level 1 (Double Agent)": LocData(70632006, "Silo"),
    "Silo - Keycard Silo Level 2 (Double Agent)": LocData(70632007, "Silo"),
    "Silo - Keycard Silo Level 3 (Double Agent)": LocData(70632008, "Silo"),
    "Bunker 2 - Cell Key 2 (Agent)": LocData(70912006, "Bunker 2"),
    "Bunker 2 - Keycard A (Agent)": LocData(70912007, "Bunker 2"),
    "Bunker 2 - Keycard B (Agent)": LocData(70912008, "Bunker 2"),
    "Bunker 2 - Cell Key 2 (Secret Agent)": LocData(70922006, "Bunker 2"),
    "Bunker 2 - Keycard A (Secret Agent)": LocData(70922007, "Bunker 2"),
    "Bunker 2 - Keycard B (Secret Agent)": LocData(70922008, "Bunker 2"),
    "Bunker 2 - Cell Key 2 (Double Agent)": LocData(70932006, "Bunker 2"),
    "Bunker 2 - Keycard A (Double Agent)": LocData(70932007, "Bunker 2"),
    "Bunker 2 - Keycard B (Double Agent)": LocData(70932008, "Bunker 2"),
    "Bunker 2 - Throwing Knives": LocData(70904001, "Bunker 2"),
    "Bunker 2 - Throwing Knives (Agent)": LocData(70914001, "Bunker 2"),
    "Bunker 2 - Throwing Knives (Secret Agent)": LocData(70924001, "Bunker 2"),
    "Bunker 2 - Throwing Knives (Double Agent)": LocData(70934001, "Bunker 2"),
    "Archives - Safe Key":     LocData(71102003, "Archives"),
    "Archives - Safe Key (Agent)": LocData(71112003, "Archives"),
    "Archives - Safe Key (Secret Agent)": LocData(71122003, "Archives"),
    "Archives - Safe Key (Double Agent)": LocData(71132002, "Archives"),
    "Archives - PP7":          LocData(71104001, "Archives"),
    "Archives - PP7 (Agent)":  LocData(71114001, "Archives"),
    "Archives - PP7 (Secret Agent)": LocData(71124001, "Archives"),
    "Archives - PP7 (Double Agent)": LocData(71134001, "Archives"),
    "Depot - Rocket Launcher": LocData(71304009, "Depot"),
    "Depot - Rocket Launcher (Agent)": LocData(71314009, "Depot"),
    "Depot - Rocket Launcher (Secret Agent)": LocData(71324009, "Depot"),
    "Depot - Rocket Launcher (Double Agent)": LocData(71334009, "Depot"),
    "Train - Key (Agent)":     LocData(71412001, "Train"),
    "Train - Key (Double Agent)": LocData(71432001, "Train"),
    "Train - Key (Secret Agent)": LocData(71422001, "Train"),
    "Train - RC-P90":          LocData(71404001, "Train"),
    "Train - RC-P90 (Agent)":  LocData(71414001, "Train"),
    "Train - RC-P90 (Secret Agent)": LocData(71424001, "Train"),
    "Train - RC-P90 (Double Agent)": LocData(71434001, "Train"),
    "Caverns - Code Card 1 (Agent)": LocData(71712001, "Caverns"),
    "Caverns - Code Card 2 (Agent)": LocData(71712002, "Caverns"),
    "Caverns - Code Card 3 (Agent)": LocData(71712003, "Caverns"),
    "Caverns - Code Card 1 (Secret Agent)": LocData(71722001, "Caverns"),
    "Caverns - Code Card 2 (Secret Agent)": LocData(71722002, "Caverns"),
    "Caverns - Code Card 3 (Secret Agent)": LocData(71722003, "Caverns"),
    "Caverns - Code Card 1 (Double Agent)": LocData(71732001, "Caverns"),
    "Caverns - Code Card 2 (Double Agent)": LocData(71732002, "Caverns"),
    "Caverns - Code Card 3 (Double Agent)": LocData(71732003, "Caverns"),
    "Caverns - AR33 Assault Rifle": LocData(71704001, "Caverns"),
    "Caverns - AR33 Assault Rifle (Agent)": LocData(71714001, "Caverns"),
    "Caverns - AR33 Assault Rifle (Secret Agent)": LocData(71724001, "Caverns"),
    "Caverns - AR33 Assault Rifle (Double Agent)": LocData(71734001, "Caverns"),
    "Stopped Goldeneye":       LocData(72110002, "Cradle"),
}

keypickup_locations = {
    "Runway - Ignition Key":   LocData(70302001, "Runway"),
    "Runway - Ignition Key (Agent)": LocData(70312001, "Runway"),
    "Runway - Ignition Key (Secret Agent)": LocData(70322001, "Runway"),
    "Runway - Ignition Key (Double Agent)": LocData(70332001, "Runway"),
    "Surface 1 - Bunker Plans (Agent)": LocData(70412001, "Surface 1"),
    "Surface 1 - Hut Door Key (Agent)": LocData(70412002, "Surface 1"),
    "Surface 1 - Bunker Plans (Double Agent)": LocData(70432001, "Surface 1"),
    "Surface 1 - Hut Door Key (Double Agent)": LocData(70432002, "Surface 1"),
    "Surface 1 - Bunker Plans (Secret Agent)": LocData(70422001, "Surface 1"),
    "Surface 1 - Hut Door Key (Secret Agent)": LocData(70422002, "Surface 1"),
    "Bunker 1 - Goldeneye Key (Agent)": LocData(70512001, "Bunker 1"),
    "Bunker 1 - Goldeneye Key (Secret Agent)": LocData(70522001, "Bunker 1"),
    "Bunker 1 - Goldeneye Key (Double Agent)": LocData(70532001, "Bunker 1"),
    "Silo - CPU Circuit Board (Agent)": LocData(70612001, "Silo"),
    "Silo - I/O Circuit Board (Agent)": LocData(70612003, "Silo"),
    "Silo - RDP Circuit Board (Agent)": LocData(70612004, "Silo"),
    "Silo - RSP Circuit Board (Agent)": LocData(70612005, "Silo"),
    "Silo - CPU Circuit Board (Secret Agent)": LocData(70622001, "Silo"),
    "Silo - I/O Circuit Board (Secret Agent)": LocData(70622003, "Silo"),
    "Silo - RDP Circuit Board (Secret Agent)": LocData(70622004, "Silo"),
    "Silo - RSP Circuit Board (Secret Agent)": LocData(70622005, "Silo"),
    "Silo - CPU Circuit Board (Double Agent)": LocData(70632001, "Silo"),
    "Silo - I/O Circuit Board (Double Agent)": LocData(70632003, "Silo"),
    "Silo - RDP Circuit Board (Double Agent)": LocData(70632004, "Silo"),
    "Silo - RSP Circuit Board (Double Agent)": LocData(70632005, "Silo"),
    "Surface 2 - Comms Room Key (Agent)": LocData(70812001, "Surface 2"),
    "Surface 2 - Comms Room Key (Secret Agent)": LocData(70822001, "Surface 2"),
    "Surface 2 - Comms Room Key (Double Agent)": LocData(70832001, "Surface 2"),
    "Bunker 2 - Casualty List (Agent)": LocData(70912001, "Bunker 2"),
    "Bunker 2 - CCTV Tape (Agent)": LocData(70912002, "Bunker 2"),
    "Bunker 2 - Goldeneye Operations Manual (Agent)": LocData(70912003, "Bunker 2"),
    "Bunker 2 - Staff List (Agent)": LocData(70912004, "Bunker 2"),
    "Bunker 2 - Cell Key 1 (Agent)": LocData(70912005, "Bunker 2"),
    "Bunker 2 - Safe Key 1 (Agent)": LocData(70912009, "Bunker 2"),
    "Bunker 2 - Safe Key 2 (Agent)": LocData(70912010, "Bunker 2"),
    "Bunker 2 - Casualty List (Secret Agent)": LocData(70922001, "Bunker 2"),
    "Bunker 2 - CCTV Tape (Secret Agent)": LocData(70922002, "Bunker 2"),
    "Bunker 2 - Goldeneye Operations Manual (Secret Agent)": LocData(70922003, "Bunker 2"),
    "Bunker 2 - Staff List (Secret Agent)": LocData(70922004, "Bunker 2"),
    "Bunker 2 - Cell Key 1 (Secret Agent)": LocData(70922005, "Bunker 2"),
    "Bunker 2 - Safe Key 1 (Secret Agent)": LocData(70922009, "Bunker 2"),
    "Bunker 2 - Safe Key 2 (Secret Agent)": LocData(70922010, "Bunker 2"),
    "Bunker 2 - Casualty List (Double Agent)": LocData(70932001, "Bunker 2"),
    "Bunker 2 - CCTV Tape (Double Agent)": LocData(70932002, "Bunker 2"),
    "Bunker 2 - Goldeneye Operations Manual (Double Agent)": LocData(70932003, "Bunker 2"),
    "Bunker 2 - Staff List (Double Agent)": LocData(70932004, "Bunker 2"),
    "Bunker 2 - Cell Key 1 (Double Agent)": LocData(70932005, "Bunker 2"),
    "Bunker 2 - Safe Key 1 (Double Agent)": LocData(70932009, "Bunker 2"),
    "Bunker 2 - Safe Key 2 (Double Agent)": LocData(70932010, "Bunker 2"),
    "Statue - Flight Recorder (Agent)": LocData(71012001, "Statue"),
    "Statue - Flight Recorder (Secret Agent)": LocData(71022001, "Statue"),
    "Statue - Flight Recorder (Double Agent)": LocData(71032001, "Statue"),
    "Archives - Flight Recorder": LocData(71102001, "Archives"),
    "Archives - Interrogation Room Key": LocData(71102002, "Archives"),
    "Archives - Flight Recorder (Agent)": LocData(71112001, "Archives"),
    "Archives - Interrogation Room Key (Agent)": LocData(71112002, "Archives"),
    "Archives - Flight Recorder (Secret Agent)": LocData(71122001, "Archives"),
    "Archives - Interrogation Room Key (Secret Agent)": LocData(71122002, "Archives"),
    "Archives - Flight Recorder (Double Agent)": LocData(71132001, "Archives"),
    "Archives - Interrogation Room Key (Double Agent)": LocData(71132003, "Archives"),
    "Depot - Blueprints (Agent)": LocData(71312001, "Depot"),
    "Depot - Safe Key (Agent)": LocData(71312002, "Depot"),
    "Depot - Blueprints (Secret Agent)": LocData(71322001, "Depot"),
    "Depot - Safe Key (Secret Agent)": LocData(71322002, "Depot"),
    "Depot - Blueprints (Double Agent)": LocData(71332001, "Depot"),
    "Depot - Safe Key (Double Agent)": LocData(71332002, "Depot"),
}

per_difficulty_clear_locations = {
    "Dam - Agent (Clear)":     LocData(70110001, "Dam"),
    "Facility - Agent (Clear)": LocData(70210001, "Facility"),
    "Runway - Agent (Clear)":  LocData(70310001, "Runway"),
    "Surface 1 - Agent (Clear)": LocData(70410001, "Surface 1"),
    "Bunker 1 - Agent (Clear)": LocData(70510001, "Bunker 1"),
    "Silo - Agent (Clear)":    LocData(70610001, "Silo"),
    "Frigate - Agent (Clear)": LocData(70710001, "Frigate"),
    "Surface 2 - Agent (Clear)": LocData(70810001, "Surface 2"),
    "Bunker 2 - Agent (Clear)": LocData(70910001, "Bunker 2"),
    "Statue - Agent (Clear)":  LocData(71010001, "Statue"),
    "Archives - Agent (Clear)": LocData(71110001, "Archives"),
    "Streets - Agent (Clear)": LocData(71210001, "Streets"),
    "Depot - Agent (Clear)":   LocData(71310001, "Depot"),
    "Train - Agent (Clear)":   LocData(71410001, "Train"),
    "Jungle - Agent (Clear)":  LocData(71510001, "Jungle"),
    "Control - Agent (Clear)": LocData(71610001, "Control"),
    "Caverns - Agent (Clear)": LocData(71710001, "Caverns"),
    "Cradle - Agent (Clear)":  LocData(71810001, "Cradle"),
    "Aztec - Agent (Clear)":   LocData(71910001, "Aztec"),
    "Egyptian - Agent (Clear)": LocData(72010001, "Egyptian"),
    "Dam - Secret Agent (Clear)": LocData(70120001, "Dam"),
    "Facility - Secret Agent (Clear)": LocData(70220001, "Facility"),
    "Runway - Secret Agent (Clear)": LocData(70320001, "Runway"),
    "Surface 1 - Secret Agent (Clear)": LocData(70420001, "Surface 1"),
    "Bunker 1 - Secret Agent (Clear)": LocData(70520001, "Bunker 1"),
    "Silo - Secret Agent (Clear)": LocData(70620001, "Silo"),
    "Frigate - Secret Agent (Clear)": LocData(70720001, "Frigate"),
    "Surface 2 - Secret Agent (Clear)": LocData(70820001, "Surface 2"),
    "Bunker 2 - Secret Agent (Clear)": LocData(70920001, "Bunker 2"),
    "Statue - Secret Agent (Clear)": LocData(71020001, "Statue"),
    "Archives - Secret Agent (Clear)": LocData(71120001, "Archives"),
    "Streets - Secret Agent (Clear)": LocData(71220001, "Streets"),
    "Depot - Secret Agent (Clear)": LocData(71320001, "Depot"),
    "Train - Secret Agent (Clear)": LocData(71420001, "Train"),
    "Jungle - Secret Agent (Clear)": LocData(71520001, "Jungle"),
    "Control - Secret Agent (Clear)": LocData(71620001, "Control"),
    "Caverns - Secret Agent (Clear)": LocData(71720001, "Caverns"),
    "Cradle - Secret Agent (Clear)": LocData(71820001, "Cradle"),
    "Aztec - Secret Agent (Clear)": LocData(71920001, "Aztec"),
    "Egyptian - Secret Agent (Clear)": LocData(72020001, "Egyptian"),
    "Dam - Double Agent (Clear)": LocData(70130001, "Dam"),
    "Facility - Double Agent (Clear)": LocData(70230001, "Facility"),
    "Runway - Double Agent (Clear)": LocData(70330001, "Runway"),
    "Surface 1 - Double Agent (Clear)": LocData(70430001, "Surface 1"),
    "Bunker 1 - Double Agent (Clear)": LocData(70530001, "Bunker 1"),
    "Silo - Double Agent (Clear)": LocData(70630001, "Silo"),
    "Frigate - Double Agent (Clear)": LocData(70730001, "Frigate"),
    "Surface 2 - Double Agent (Clear)": LocData(70830001, "Surface 2"),
    "Bunker 2 - Double Agent (Clear)": LocData(70930001, "Bunker 2"),
    "Statue - Double Agent (Clear)": LocData(71030001, "Statue"),
    "Archives - Double Agent (Clear)": LocData(71130001, "Archives"),
    "Streets - Double Agent (Clear)": LocData(71230001, "Streets"),
    "Depot - Double Agent (Clear)": LocData(71330001, "Depot"),
    "Train - Double Agent (Clear)": LocData(71430001, "Train"),
    "Jungle - Double Agent (Clear)": LocData(71530001, "Jungle"),
    "Control - Double Agent (Clear)": LocData(71630001, "Control"),
    "Caverns - Double Agent (Clear)": LocData(71730001, "Caverns"),
    "Cradle - Double Agent (Clear)": LocData(71830001, "Cradle"),
    "Aztec - Double Agent (Clear)": LocData(71930001, "Aztec"),
    "Egyptian - Double Agent (Clear)": LocData(72030001, "Egyptian"),
}

keypickup_detection_aliases = {
    "Runway - Ignition Key": ('Ignition Key',),
    "Runway - Ignition Key (Agent)": ('Ignition Key', 'Picked up an ignition key.',),
    "Runway - Ignition Key (Secret Agent)": ('Ignition Key', 'Picked up an ignition key.',),
    "Runway - Ignition Key (Double Agent)": ('Ignition Key', 'Picked up an ignition key.',),
    "Surface 1 - Bunker Plans (Agent)": ('Bunker Plans', 'Picked up Bunker plans.',),
    "Surface 1 - Hut Door Key (Agent)": ('Hut Door Key', 'Picked up a large key.',),
    "Surface 1 - Bunker Plans (Double Agent)": ('Bunker Plans', 'Picked up Bunker plans.',),
    "Surface 1 - Hut Door Key (Double Agent)": ('Hut Door Key', 'Picked up a large key.',),
    "Surface 1 - Bunker Plans (Secret Agent)": ('Bunker Plans', 'Picked up Bunker plans.',),
    "Surface 1 - Hut Door Key (Secret Agent)": ('Hut Door Key', 'Picked up a large key.',),
    "Bunker 1 - Goldeneye Key (Agent)": ('Goldeneye Key',),
    "Bunker 1 - Goldeneye Key (Secret Agent)": ('Goldeneye Key',),
    "Bunker 1 - Goldeneye Key (Double Agent)": ('Goldeneye Key',),
    "Silo - CPU Circuit Board (Agent)": ('CPU Circuit Board',),
    "Silo - I/O Circuit Board (Agent)": ('I/O Circuit Board',),
    "Silo - RDP Circuit Board (Agent)": ('RDP Circuit Board',),
    "Silo - RSP Circuit Board (Agent)": ('RSP Circuit Board',),
    "Silo - CPU Circuit Board (Secret Agent)": ('CPU Circuit Board',),
    "Silo - I/O Circuit Board (Secret Agent)": ('I/O Circuit Board',),
    "Silo - RDP Circuit Board (Secret Agent)": ('RDP Circuit Board',),
    "Silo - RSP Circuit Board (Secret Agent)": ('RSP Circuit Board',),
    "Silo - CPU Circuit Board (Double Agent)": ('CPU Circuit Board',),
    "Silo - I/O Circuit Board (Double Agent)": ('I/O Circuit Board',),
    "Silo - RDP Circuit Board (Double Agent)": ('RDP Circuit Board',),
    "Silo - RSP Circuit Board (Double Agent)": ('RSP Circuit Board',),
    "Surface 2 - Comms Room Key (Agent)": ('Comms Room Key', 'Picked up comms room key.',),
    "Surface 2 - Comms Room Key (Secret Agent)": ('Comms Room Key', 'Picked up comms room key.',),
    "Surface 2 - Comms Room Key (Double Agent)": ('Comms Room Key', 'Picked up comms room key.',),
    "Bunker 2 - Casualty List (Agent)": ('Casualty List',),
    "Bunker 2 - CCTV Tape (Agent)": ('CCTV Tape',),
    "Bunker 2 - Goldeneye Operations Manual (Agent)": ('Goldeneye Operations Manual',),
    "Bunker 2 - Staff List (Agent)": ('Staff List',),
    "Bunker 2 - Cell Key 1 (Agent)": ('Cell Key 1',),
    "Bunker 2 - Safe Key 1 (Agent)": ('Safe Key 1',),
    "Bunker 2 - Safe Key 2 (Agent)": ('Safe Key 2',),
    "Bunker 2 - Casualty List (Secret Agent)": ('Casualty List',),
    "Bunker 2 - CCTV Tape (Secret Agent)": ('CCTV Tape',),
    "Bunker 2 - Goldeneye Operations Manual (Secret Agent)": ('Goldeneye Operations Manual',),
    "Bunker 2 - Staff List (Secret Agent)": ('Staff List',),
    "Bunker 2 - Cell Key 1 (Secret Agent)": ('Cell Key 1',),
    "Bunker 2 - Safe Key 1 (Secret Agent)": ('Safe Key 1',),
    "Bunker 2 - Safe Key 2 (Secret Agent)": ('Safe Key 2',),
    "Bunker 2 - Casualty List (Double Agent)": ('Casualty List',),
    "Bunker 2 - CCTV Tape (Double Agent)": ('CCTV Tape',),
    "Bunker 2 - Goldeneye Operations Manual (Double Agent)": ('Goldeneye Operations Manual',),
    "Bunker 2 - Staff List (Double Agent)": ('Staff List',),
    "Bunker 2 - Cell Key 1 (Double Agent)": ('Cell Key 1',),
    "Bunker 2 - Safe Key 1 (Double Agent)": ('Safe Key 1',),
    "Bunker 2 - Safe Key 2 (Double Agent)": ('Safe Key 2',),
    "Statue - Flight Recorder (Agent)": ('Flight Recorder',),
    "Statue - Flight Recorder (Secret Agent)": ('Flight Recorder',),
    "Statue - Flight Recorder (Double Agent)": ('Flight Recorder',),
    "Archives - Flight Recorder": ('Flight Recorder',),
    "Archives - Interrogation Room Key": ('Interrogation Room Key',),
    "Archives - Flight Recorder (Agent)": ('Flight Recorder',),
    "Archives - Interrogation Room Key (Agent)": ('Interrogation Room Key',),
    "Archives - Flight Recorder (Secret Agent)": ('Flight Recorder',),
    "Archives - Interrogation Room Key (Secret Agent)": ('Interrogation Room Key',),
    "Archives - Flight Recorder (Double Agent)": ('Flight Recorder',),
    "Archives - Interrogation Room Key (Double Agent)": ('Interrogation Room Key',),
    "Depot - Blueprints (Agent)": ('Blueprints',),
    "Depot - Safe Key (Agent)": ('Safe Key',),
    "Depot - Blueprints (Secret Agent)": ('Blueprints',),
    "Depot - Safe Key (Secret Agent)": ('Safe Key',),
    "Depot - Blueprints (Double Agent)": ('Blueprints',),
    "Depot - Safe Key (Double Agent)": ('Safe Key',),
}

shared_clear_locations = {
    "Dam - (Clear)":           LocData(70100001, "Dam"),
    "Facility - (Clear)":      LocData(70200001, "Facility"),
    "Runway - (Clear)":        LocData(70300001, "Runway"),
    "Surface 1 - (Clear)":     LocData(70400001, "Surface 1"),
    "Bunker 1 - (Clear)":      LocData(70500001, "Bunker 1"),
    "Silo - (Clear)":          LocData(70600001, "Silo"),
    "Frigate - (Clear)":       LocData(70700001, "Frigate"),
    "Surface 2 - (Clear)":     LocData(70800001, "Surface 2"),
    "Bunker 2 - (Clear)":      LocData(70900001, "Bunker 2"),
    "Statue - (Clear)":        LocData(71000001, "Statue"),
    "Archives - (Clear)":      LocData(71100001, "Archives"),
    "Streets - (Clear)":       LocData(71200001, "Streets"),
    "Depot - (Clear)":         LocData(71300001, "Depot"),
    "Train - (Clear)":         LocData(71400001, "Train"),
    "Jungle - (Clear)":        LocData(71500001, "Jungle"),
    "Control - (Clear)":       LocData(71600001, "Control"),
    "Caverns - (Clear)":       LocData(71700001, "Caverns"),
    "Cradle - (Clear)":        LocData(71800001, "Cradle"),
    "Aztec - (Clear)":         LocData(71900001, "Aztec"),
    "Egyptian - (Clear)":      LocData(72000001, "Egyptian"),
}

per_difficulty_objective_locations = {
    "Dam - Bungee Jump From Platform (Agent)": LocData(70111001, "Dam"),
    "Dam - Neutralize All Alarms (Secret Agent)": LocData(70121001, "Dam"),
    "Dam - Bungee Jump From Platform (Secret Agent)": LocData(70121002, "Dam"),
    "Dam - Neutralize All Alarms (Double Agent)": LocData(70131001, "Dam"),
    "Dam - Install Covert Modem (Double Agent)": LocData(70131002, "Dam"),
    "Dam - Intercept Data Backup (Double Agent)": LocData(70131003, "Dam"),
    "Dam - Bungee Jump From Platform (Double Agent)": LocData(70131004, "Dam"),
    "Facility - Gain Entry To Laboratory Area (Agent)": LocData(70211001, "Facility"),
    "Facility - Rendezvous With 006 (Agent)": LocData(70211002, "Facility"),
    "Facility - Destroy All Tanks In Bottling Room (Agent)": LocData(70211003, "Facility"),
    "Facility - Minimize Facility Scientist Casualties (Agent)": LocData(70211004, "Facility"),
    "Facility - Gain Entry To Laboratory Area (Secret Agent)": LocData(70221001, "Facility"),
    "Facility - Contact Double Agent (Secret Agent)": LocData(70221002, "Facility"),
    "Facility - Rendezvous With 006 (Secret Agent)": LocData(70221003, "Facility"),
    "Facility - Destroy All Tanks In Bottling Room (Secret Agent)": LocData(70221004, "Facility"),
    "Facility - Minimize Facility Scientist Casualties (Secret Agent)": LocData(70221005, "Facility"),
    "Facility - Gain Entry To Laboratory Area (Double Agent)": LocData(70231001, "Facility"),
    "Facility - Contact Double Agent (Double Agent)": LocData(70231002, "Facility"),
    "Facility - Rendezvous With 006 (Double Agent)": LocData(70231003, "Facility"),
    "Facility - Destroy All Tanks In Bottling Room (Double Agent)": LocData(70231004, "Facility"),
    "Facility - Minimize Facility Scientist Casualties (Double Agent)": LocData(70231005, "Facility"),
    "Runway - Find Plane Ignition Key (Agent)": LocData(70311001, "Runway"),
    "Runway - Escape In Plane (Agent)": LocData(70311002, "Runway"),
    "Runway - Find Plane Ignition Key (Secret Agent)": LocData(70321001, "Runway"),
    "Runway - Destroy Missile Battery (Secret Agent)": LocData(70321002, "Runway"),
    "Runway - Escape In Plane (Secret Agent)": LocData(70321003, "Runway"),
    "Runway - Find Plane Ignition Key (Double Agent)": LocData(70331001, "Runway"),
    "Runway - Destroy Heavy Gun Emplacements (Double Agent)": LocData(70331002, "Runway"),
    "Runway - Destroy Missile Battery (Double Agent)": LocData(70331003, "Runway"),
    "Runway - Escape In Plane (Double Agent)": LocData(70331004, "Runway"),
    "Surface 1 - Enter Base Via Ventilation Tower (Agent)": LocData(70411001, "Surface 1"),
    "Surface 1 - Power Down Communications Dish (Agent)": LocData(70411002, "Surface 1"),
    "Surface 1 - Enter Base Via Ventilation Tower (Secret Agent)": LocData(70421001, "Surface 1"),
    "Surface 1 - Obtain Surface Safe Key (Secret Agent)": LocData(70421002, "Surface 1"),
    "Surface 1 - Power Down Communications Dish (Secret Agent)": LocData(70421003, "Surface 1"),
    "Surface 1 - Steal Building Plans (Secret Agent)": LocData(70421004, "Surface 1"),
    "Surface 1 - Power Down Communications Dish (Double Agent)": LocData(70431001, "Surface 1"),
    "Surface 1 - Obtain Surface Safe Key (Double Agent)": LocData(70431002, "Surface 1"),
    "Surface 1 - Steal Building Plans (Double Agent)": LocData(70431003, "Surface 1"),
    "Surface 1 - Enter Base Via Ventilation Tower (Double Agent)": LocData(70431004, "Surface 1"),
    "Bunker 1 - Copy Goldeneye Key And Leave Original (Agent)": LocData(70511001, "Bunker 1"),
    "Bunker 1 - Photograph Main Video Screen (Agent)": LocData(70511002, "Bunker 1"),
    "Bunker 1 - Disrupt All Surveillance Equipment (Secret Agent)": LocData(70521001, "Bunker 1"),
    "Bunker 1 - Copy Goldeneye Key And Leave Original (Secret Agent)": LocData(70521002, "Bunker 1"),
    "Bunker 1 - Photograph Main Video Screen (Secret Agent)": LocData(70521003, "Bunker 1"),
    "Bunker 1 - Disrupt All Surveillance Equipment (Double Agent)": LocData(70531001, "Bunker 1"),
    "Bunker 1 - Copy Goldeneye Key And Leave Original (Double Agent)": LocData(70531002, "Bunker 1"),
    "Bunker 1 - Get Personnel To Activate Computer (Double Agent)": LocData(70531003, "Bunker 1"),
    "Bunker 1 - Download Data From Computer (Double Agent)": LocData(70531004, "Bunker 1"),
    "Bunker 1 - Photograph Main Video Screen (Double Agent)": LocData(70531005, "Bunker 1"),
    "Silo - Photograph Satellite (Agent)": LocData(70611001, "Silo"),
    "Silo - Minimize Silo Scientist Casualties (Agent)": LocData(70611002, "Silo"),
    "Silo - Photograph Satellite (Secret Agent)": LocData(70621001, "Silo"),
    "Silo - Obtain Telemetric Data (Secret Agent)": LocData(70621002, "Silo"),
    "Silo - Retrieve Satellite Circuitry (Secret Agent)": LocData(70621003, "Silo"),
    "Silo - Minimize Silo Scientist Casualties (Secret Agent)": LocData(70621004, "Silo"),
    "Silo - Plant Bombs In Fuel Rooms (Double Agent)": LocData(70631001, "Silo"),
    "Silo - Photograph Satellite (Double Agent)": LocData(70631002, "Silo"),
    "Silo - Obtain Telemetric Data (Double Agent)": LocData(70631003, "Silo"),
    "Silo - Retrieve Satellite Circuitry (Double Agent)": LocData(70631004, "Silo"),
    "Silo - Minimize Silo Scientist Casualties (Double Agent)": LocData(70631005, "Silo"),
    "Frigate - Rescue Hostages (Agent)": LocData(70711001, "Frigate"),
    "Frigate - Plant Tracking Bug On Helicopter (Agent)": LocData(70711002, "Frigate"),
    "Frigate - Rescue Hostages (Secret Agent)": LocData(70721001, "Frigate"),
    "Frigate - Disarm Bridge Bomb (Secret Agent)": LocData(70721002, "Frigate"),
    "Frigate - Disarm Engine Room Bomb (Secret Agent)": LocData(70721003, "Frigate"),
    "Frigate - Plant Tracking Bug On Helicopter (Secret Agent)": LocData(70721004, "Frigate"),
    "Frigate - Rescue Hostages (Double Agent)": LocData(70731001, "Frigate"),
    "Frigate - Disarm Bridge Bomb (Double Agent)": LocData(70731002, "Frigate"),
    "Frigate - Disarm Engine Room Bomb (Double Agent)": LocData(70731003, "Frigate"),
    "Frigate - Plant Tracking Bug On Helicopter (Double Agent)": LocData(70731004, "Frigate"),
    "Surface 2 - Break Communications Link To Bunker (Agent)": LocData(70811001, "Surface 2"),
    "Surface 2 - Gain Entry To Bunker (Agent)": LocData(70811002, "Surface 2"),
    "Surface 2 - Break Communications Link To Bunker (Secret Agent)": LocData(70821001, "Surface 2"),
    "Surface 2 - Disable Spetznaz Support Aircraft (Secret Agent)": LocData(70821002, "Surface 2"),
    "Surface 2 - Gain Entry To Bunker (Secret Agent)": LocData(70821003, "Surface 2"),
    "Surface 2 - Disrupt All surveillance Equipment (Double Agent)": LocData(70831001, "Surface 2"),
    "Surface 2 - Break Communications Link To Bunker (Double Agent)": LocData(70831002, "Surface 2"),
    "Surface 2 - Disable Spetznaz Support Aircraft (Double Agent)": LocData(70831003, "Surface 2"),
    "Surface 2 - Gain Entry To Bunker (Double Agent)": LocData(70831004, "Surface 2"),
    "Bunker 2 - Recover CCTV Tape (Agent)": LocData(70911001, "Bunker 2"),
    "Bunker 2 - Escape With Natalya (Agent)": LocData(70911002, "Bunker 2"),
    "Bunker 2 - Recover CCTV Tape (Secret Agent)": LocData(70921001, "Bunker 2"),
    "Bunker 2 - Compare Staff/Casualty Lists (Secret Agent)": LocData(70921002, "Bunker 2"),
    "Bunker 2 - Disable All Security Cameras (Secret Agent)": LocData(70921003, "Bunker 2"),
    "Bunker 2 - Escape With Natalya (Secret Agent)": LocData(70921004, "Bunker 2"),
    "Bunker 2 - Compare Staff/Casualty Lists (Double Agent)": LocData(70931001, "Bunker 2"),
    "Bunker 2 - Recover CCTV Tape (Double Agent)": LocData(70931002, "Bunker 2"),
    "Bunker 2 - Disable All Security Cameras (Double Agent)": LocData(70931003, "Bunker 2"),
    "Bunker 2 - Recover Goldeneye Operations Manual (Double Agent)": LocData(70931004, "Bunker 2"),
    "Bunker 2 - Escape With Natalya (Double Agent)": LocData(70931005, "Bunker 2"),
    "Statue - Contact Valentin (Agent)": LocData(71011001, "Statue"),
    "Statue - Confront And Unmask Janus (Agent)": LocData(71011002, "Statue"),
    "Statue - Find Flight Recorder (Agent)": LocData(71011003, "Statue"),
    "Statue - Locate Helicopter (Agent)": LocData(71011004, "Statue"),
    "Statue - Rescue Natalya (Agent)": LocData(71011005, "Statue"),
    "Statue - Contact Valentin (Secret Agent)": LocData(71021001, "Statue"),
    "Statue - Confront And Unmask Janus (Secret Agent)": LocData(71021002, "Statue"),
    "Statue - Find Flight Recorder (Secret Agent)": LocData(71021003, "Statue"),
    "Statue - Locate Helicopter (Secret Agent)": LocData(71021004, "Statue"),
    "Statue - Rescue Natalya (Secret Agent)": LocData(71021005, "Statue"),
    "Statue - Contact Valentin (Double Agent)": LocData(71031001, "Statue"),
    "Statue - Confront And Unmask Janus (Double Agent)": LocData(71031002, "Statue"),
    "Statue - Locate Helicopter (Double Agent)": LocData(71031003, "Statue"),
    "Statue - Rescue Natalya (Double Agent)": LocData(71031004, "Statue"),
    "Statue - Find Flight Recorder (Double Agent)": LocData(71031005, "Statue"),
    "Archives - Escape From Interrogation Room (Agent)": LocData(71111001, "Archives"),
    "Archives - Find Natalya (Agent)": LocData(71111003, "Archives"),
    "Archives - Escape With Natalya Again (Agent)": LocData(71111002, "Archives"),
    "Archives - Escape From Interrogation Room (Secret Agent)": LocData(71121004, "Archives"),
    "Archives - Find Natalya (Secret Agent)": LocData(71121002, "Archives"),
    "Archives - Recover Helicopter Black Box (Secret Agent)": LocData(71121003, "Archives"),
    "Archives - Escape With Natalya Again (Secret Agent)": LocData(71121001, "Archives"),
    "Archives - Escape From Interrogation Room (Double Agent)": LocData(71131001, "Archives"),
    "Archives - Find Natalya (Double Agent)": LocData(71131002, "Archives"),
    "Archives - Recover Helicopter Black Box (Double Agent)": LocData(71131003, "Archives"),
    "Archives - Escape With Natalya Again (Double Agent)": LocData(71131004, "Archives"),
    "Streets - Pursue Ouromov And Natalya (Agent)": LocData(71211001, "Streets"),
    "Streets - Minimize Civilian Casualties (Agent)": LocData(71211002, "Streets"),
    "Streets - Contact Valentin Again (Secret Agent)": LocData(71221001, "Streets"),
    "Streets - Pursue Ouromov And Natalya (Secret Agent)": LocData(71221002, "Streets"),
    "Streets - Minimize Civilian Casualties (Secret Agent)": LocData(71221003, "Streets"),
    "Streets - Contact Valentin Again (Double Agent)": LocData(71231001, "Streets"),
    "Streets - Pursue Ouromov And Natalya (Double Agent)": LocData(71231002, "Streets"),
    "Streets - Minimize Civilian Casualties (Double Agent)": LocData(71231003, "Streets"),
    "Depot - Locate Trevelyn's Train (Agent)": LocData(71311001, "Depot"),
    "Depot - Destroy Computer Network (Secret Agent)": LocData(71321001, "Depot"),
    "Depot - Obtain Depot Safe Key (Secret Agent)": LocData(71321002, "Depot"),
    "Depot - Recover Helicopter Blueprints (Secret Agent)": LocData(71321003, "Depot"),
    "Depot - Locate Trevelyn's Train (Secret Agent)": LocData(71321004, "Depot"),
    "Depot - Destroy Illegal Arms Cache (Double Agent)": LocData(71331001, "Depot"),
    "Depot - Destroy Computer Network (Double Agent)": LocData(71331002, "Depot"),
    "Depot - Obtain Depot Safe Key (Double Agent)": LocData(71331003, "Depot"),
    "Depot - Recover Helicopter Blueprints (Double Agent)": LocData(71331004, "Depot"),
    "Depot - Locate Trevelyn's Train (Double Agent)": LocData(71331005, "Depot"),
    "Train - Destroy Brake Units (Agent)": LocData(71411001, "Train"),
    "Train - Rescue Natalya Again (Agent)": LocData(71411002, "Train"),
    "Train - Escape To Safety (Agent)": LocData(71411003, "Train"),
    "Train - Destroy Brake Units (Secret Agent)": LocData(71421001, "Train"),
    "Train - Rescue Natalya Again (Secret Agent)": LocData(71421002, "Train"),
    "Train - Locate Janus Secret Base (Secret Agent)": LocData(71421003, "Train"),
    "Train - Escape To Safety (Secret Agent)": LocData(71421004, "Train"),
    "Train - Destroy Brake Units (Double Agent)": LocData(71431001, "Train"),
    "Train - Rescue Natalya Again (Double Agent)": LocData(71431002, "Train"),
    "Train - Locate Janus Secret Base (Double Agent)": LocData(71431003, "Train"),
    "Train - Crack Boris' Password (Double Agent)": LocData(71431004, "Train"),
    "Train - Escape To Safety (Double Agent)": LocData(71431005, "Train"),
    "Jungle - Destroy Drone Guns (Agent)": LocData(71511001, "Jungle"),
    "Jungle - Eliminate Xenia (Agent)": LocData(71511002, "Jungle"),
    "Jungle - Escort Natalya To Janus Base (Agent)": LocData(71511003, "Jungle"),
    "Jungle - Destroy Drone Guns (Secret Agent)": LocData(71521001, "Jungle"),
    "Jungle - Eliminate Xenia (Secret Agent)": LocData(71521002, "Jungle"),
    "Jungle - Blow Up Ammo Dump (Secret Agent)": LocData(71521003, "Jungle"),
    "Jungle - Escort Natalya To Janus Base (Secret Agent)": LocData(71521004, "Jungle"),
    "Jungle - Destroy Drone Guns (Double Agent)": LocData(71531001, "Jungle"),
    "Jungle - Eliminate Xenia (Double Agent)": LocData(71531002, "Jungle"),
    "Jungle - Blow Up Ammo Dump (Double Agent)": LocData(71531003, "Jungle"),
    "Jungle - Escort Natalya To Janus Base (Double Agent)": LocData(71531004, "Jungle"),
    "Control - Protect Natalya (Agent)": LocData(71611001, "Control"),
    "Control - Disable Goldeneye Satellite (Agent)": LocData(71611002, "Control"),
    "Control - Destroy Armored Mainframes (Agent)": LocData(71611003, "Control"),
    "Control - Protect Natalya (Secret Agent)": LocData(71621001, "Control"),
    "Control - Disable Goldeneye Satellite (Secret Agent)": LocData(71621002, "Control"),
    "Control - Destroy Armored Mainframes (Secret Agent)": LocData(71621003, "Control"),
    "Control - Protect Natalya (Double Agent)": LocData(71631001, "Control"),
    "Control - Disable Goldeneye Satellite (Double Agent)": LocData(71631002, "Control"),
    "Control - Destroy Armored Mainframes (Double Agent)": LocData(71631003, "Control"),
    "Caverns - Minimize Caverns Scientist Casualties (Agent)": LocData(71711001, "Caverns"),
    "Caverns - Destroy Inlet Pump Controls (Secret Agent)": LocData(71721001, "Caverns"),
    "Caverns - Destroy Outlet Pump controls (Secret Agent)": LocData(71721002, "Caverns"),
    "Caverns - Destroy Master Control Console (Secret Agent)": LocData(71721003, "Caverns"),
    "Caverns - Minimize Caverns Scientist Casualties (Secret Agent)": LocData(71721004, "Caverns"),
    "Caverns - Destroy Inlet Pump Controls (Double Agent)": LocData(71731001, "Caverns"),
    "Caverns - Destroy Outlet Pump controls (Double Agent)": LocData(71731002, "Caverns"),
    "Caverns - Destroy Master Control Console (Double Agent)": LocData(71731003, "Caverns"),
    "Caverns - Use Radio To Contact Jack Wade (Double Agent)": LocData(71731004, "Caverns"),
    "Caverns - Minimize Caverns Scientist Casualties (Double Agent)": LocData(71731005, "Caverns"),
    "Cradle - Destroy Control Console (Agent)": LocData(71811001, "Cradle"),
    "Cradle - Settle The Score With Trevelyan (Agent)": LocData(71811002, "Cradle"),
    "Cradle - Destroy Control Console (Secret Agent)": LocData(71821001, "Cradle"),
    "Cradle - Settle The Score With Trevelyan (Secret Agent)": LocData(71821002, "Cradle"),
    "Cradle - Destroy Control Console (Double Agent)": LocData(71831001, "Cradle"),
    "Cradle - Settle The Score With Trevelyan (Double Agent)": LocData(71831002, "Cradle"),
    "Aztec - Reprogram Shuttle Guidance (Agent)": LocData(71911001, "Aztec"),
    "Aztec - Launch Shuttle (Agent)": LocData(71911002, "Aztec"),
    "Aztec - Reprogram Shuttle Guidance (Secret Agent)": LocData(71921001, "Aztec"),
    "Aztec - Launch Shuttle (Secret Agent)": LocData(71921002, "Aztec"),
    "Aztec - Reprogram Shuttle Guidance (Double Agent)": LocData(71931001, "Aztec"),
    "Aztec - Launch Shuttle (Double Agent)": LocData(71931002, "Aztec"),
    "Egyptian - Recover the Golden Gun (Agent)": LocData(72011001, "Egyptian"),
    "Egyptian - Defeat Baron Samedi? (Agent)": LocData(72011002, "Egyptian"),
    "Egyptian - Recover the Golden Gun (Secret Agent)": LocData(72021001, "Egyptian"),
    "Egyptian - Defeat Baron Samedi? (Secret Agent)": LocData(72021002, "Egyptian"),
    "Egyptian - Recover the Golden Gun (Double Agent)": LocData(72031001, "Egyptian"),
    "Egyptian - Defeat Baron Samedi? (Double Agent)": LocData(72031002, "Egyptian"),
}

shared_objective_locations = {
    "Dam - Neutralize All Alarms": LocData(70101001, "Dam"),
    "Dam - Install Covert Modem": LocData(70101002, "Dam"),
    "Dam - Intercept Data Backup": LocData(70101003, "Dam"),
    "Dam - Bungee Jump From Platform": LocData(70101004, "Dam"),
    "Facility - Gain Entry To Laboratory Area": LocData(70201001, "Facility"),
    "Facility - Contact Double Agent": LocData(70201002, "Facility"),
    "Facility - Rendezvous With 006": LocData(70201003, "Facility"),
    "Facility - Destroy All Tanks In Bottling Room": LocData(70201004, "Facility"),
    "Facility - Minimize Facility Scientist Casualties": LocData(70201005, "Facility"),
    "Runway - Find Plane Ignition Key": LocData(70301001, "Runway"),
    "Runway - Destroy Heavy Gun Emplacements": LocData(70301002, "Runway"),
    "Runway - Destroy Missile Battery": LocData(70301003, "Runway"),
    "Runway - Escape In Plane": LocData(70301004, "Runway"),
    "Surface 1 - Power Down Communications Dish": LocData(70401001, "Surface 1"),
    "Surface 1 - Obtain Surface Safe Key": LocData(70401002, "Surface 1"),
    "Surface 1 - Steal Building Plans": LocData(70401003, "Surface 1"),
    "Surface 1 - Enter Base Via Ventilation Tower": LocData(70401004, "Surface 1"),
    "Bunker 1 - Disrupt All Surveillance Equipment": LocData(70501001, "Bunker 1"),
    "Bunker 1 - Copy Goldeneye Key And Leave Original": LocData(70501002, "Bunker 1"),
    "Bunker 1 - Get Personnel To Activate Computer": LocData(70501003, "Bunker 1"),
    "Bunker 1 - Download Data From Computer": LocData(70501004, "Bunker 1"),
    "Bunker 1 - Photograph Main Video Screen": LocData(70501005, "Bunker 1"),
    "Silo - Plant Bombs In Fuel Rooms": LocData(70601001, "Silo"),
    "Silo - Photograph Satellite": LocData(70601002, "Silo"),
    "Silo - Obtain Telemetric Data": LocData(70601003, "Silo"),
    "Silo - Retrieve Satellite Circuitry": LocData(70601004, "Silo"),
    "Silo - Minimize Silo Scientist Casualties": LocData(70601005, "Silo"),
    "Frigate - Rescue Hostages": LocData(70701001, "Frigate"),
    "Frigate - Disarm Bridge Bomb": LocData(70701002, "Frigate"),
    "Frigate - Disarm Engine Room Bomb": LocData(70701003, "Frigate"),
    "Frigate - Plant Tracking Bug On Helicopter": LocData(70701004, "Frigate"),
    "Surface 2 - Disrupt All surveillance Equipment": LocData(70801001, "Surface 2"),
    "Surface 2 - Break Communications Link To Bunker": LocData(70801002, "Surface 2"),
    "Surface 2 - Disable Spetznaz Support Aircraft": LocData(70801003, "Surface 2"),
    "Surface 2 - Gain Entry To Bunker": LocData(70801004, "Surface 2"),
    "Bunker 2 - Compare Staff/Casualty Lists": LocData(70901001, "Bunker 2"),
    "Bunker 2 - Recover CCTV Tape": LocData(70901002, "Bunker 2"),
    "Bunker 2 - Disable All Security Cameras": LocData(70901003, "Bunker 2"),
    "Bunker 2 - Recover Goldeneye Operations Manual": LocData(70901004, "Bunker 2"),
    "Bunker 2 - Escape With Natalya": LocData(70901005, "Bunker 2"),
    "Statue - Contact Valentin": LocData(71001001, "Statue"),
    "Statue - Confront And Unmask Janus": LocData(71001002, "Statue"),
    "Statue - Locate Helicopter": LocData(71001003, "Statue"),
    "Statue - Rescue Natalya": LocData(71001004, "Statue"),
    "Statue - Find Flight Recorder": LocData(71001005, "Statue"),
    "Archives - Escape From Interrogation Room": LocData(71101001, "Archives"),
    "Archives - Find Natalya": LocData(71101002, "Archives"),
    "Archives - Recover Helicopter Black Box": LocData(71101003, "Archives"),
    "Archives - Escape With Natalya Again": LocData(71101004, "Archives"),
    "Streets - Contact Valentin Again": LocData(71201001, "Streets"),
    "Streets - Pursue Ouromov And Natalya": LocData(71201002, "Streets"),
    "Streets - Minimize Civilian Casualties": LocData(71201003, "Streets"),
    "Depot - Destroy Illegal Arms Cache": LocData(71301001, "Depot"),
    "Depot - Destroy Computer Network": LocData(71301002, "Depot"),
    "Depot - Obtain Depot Safe Key": LocData(71301003, "Depot"),
    "Depot - Recover Helicopter Blueprints": LocData(71301004, "Depot"),
    "Depot - Locate Trevelyn's Train": LocData(71301005, "Depot"),
    "Train - Destroy Brake Units": LocData(71401001, "Train"),
    "Train - Rescue Natalya Again": LocData(71401002, "Train"),
    "Train - Locate Janus Secret Base": LocData(71401003, "Train"),
    "Train - Crack Boris' Password": LocData(71401004, "Train"),
    "Train - Escape To Safety": LocData(71401005, "Train"),
    "Jungle - Destroy Drone Guns": LocData(71501001, "Jungle"),
    "Jungle - Eliminate Xenia": LocData(71501002, "Jungle"),
    "Jungle - Blow Up Ammo Dump": LocData(71501003, "Jungle"),
    "Jungle - Escort Natalya To Janus Base": LocData(71501004, "Jungle"),
    "Control - Protect Natalya": LocData(71601001, "Control"),
    "Control - Disable Goldeneye Satellite": LocData(71601002, "Control"),
    "Control - Destroy Armored Mainframes": LocData(71601003, "Control"),
    "Caverns - Destroy Inlet Pump Controls": LocData(71701001, "Caverns"),
    "Caverns - Destroy Outlet Pump controls": LocData(71701002, "Caverns"),
    "Caverns - Destroy Master Control Console": LocData(71701003, "Caverns"),
    "Caverns - Use Radio To Contact Jack Wade": LocData(71701004, "Caverns"),
    "Caverns - Minimize Caverns Scientist Casualties": LocData(71701005, "Caverns"),
    "Cradle - Destroy Control Console": LocData(71801001, "Cradle"),
    "Cradle - Settle The Score With Trevelyan": LocData(71801002, "Cradle"),
    "Aztec - Reprogram Shuttle Guidance": LocData(71901001, "Aztec"),
    "Aztec - Launch Shuttle":  LocData(71901002, "Aztec"),
    "Egyptian - Recover the Golden Gun": LocData(72001001, "Egyptian"),
    "Egyptian - Defeat Baron Samedi?": LocData(72001002, "Egyptian"),
}

extra_locations = {
    "Aztec - Guidance Data (Agent)": LocData(71912001, "Aztec"),
    "Aztec - Security Smart Card (Agent)": LocData(71912002, "Aztec"),
    "Aztec - Launch Protocol Data (Agent)": LocData(71912003, "Aztec"),
    "Aztec - Guidance Data (Double Agent)": LocData(71932001, "Aztec"),
    "Aztec - Launch Protocol Data (Secret Agent)": LocData(71922001, "Aztec"),
    "Aztec - Guidance Data (Secret Agent)": LocData(71922002, "Aztec"),
    "Aztec - Security Smart Card (Secret Agent)": LocData(71922003, "Aztec"),
    "Aztec - Launch Protocol Data (Double Agent)": LocData(71932002, "Aztec"),
    "Aztec - Security Smart Card (Double Agent)": LocData(71932003, "Aztec"),
    "Egyptian - Golden Gun":   LocData(72002001, "Egyptian"),
    "Egyptian - Golden Gun (Agent)": LocData(72014001, "Egyptian"),
    "Egyptian - Golden Gun (Secret Agent)": LocData(72024001, "Egyptian"),
    "Egyptian - Golden Gun (Double Agent)": LocData(72034001, "Egyptian"),
}

event_locations = {
}


def _split_difficulty_suffix(name: str) -> tuple[str, int] | None:
    for difficulty_name, difficulty_code in (("Agent", 1), ("Secret Agent", 2), ("Double Agent", 3)):
        suffix = f" ({difficulty_name})"
        if name.endswith(suffix):
            return name[:-len(suffix)], difficulty_code
    return None


def _build_location_mode_tables(raw_locations: Dict[str, LocData]):
    grouped = {}
    for name, data in raw_locations.items():
        parsed = _split_difficulty_suffix(name)
        if parsed is None:
            entry = grouped.setdefault(name, {"shared": None, "per_difficulty": {}})
            entry["shared"] = (name, data)
            continue
        base_name, difficulty_code = parsed
        entry = grouped.setdefault(base_name, {"shared": None, "per_difficulty": {}})
        entry["per_difficulty"][difficulty_code] = (name, data)

    always_on = {}
    shared = {}
    per_difficulty = {}
    shared_groups = {}
    for base_name, entry in grouped.items():
        if not entry["per_difficulty"]:
            if entry["shared"] is not None:
                shared_name, shared_data = entry["shared"]
                always_on[shared_name] = shared_data
            continue

        for difficulty_code in sorted(entry["per_difficulty"]):
            per_name, per_data = entry["per_difficulty"][difficulty_code]
            per_difficulty[per_name] = per_data

        if entry["shared"] is not None:
            shared_name, shared_data = entry["shared"]
        else:
            first_difficulty = min(entry["per_difficulty"])
            _, first_data = entry["per_difficulty"][first_difficulty]
            shared_name = base_name
            shared_data = LocData(first_data.ap_code - (first_difficulty * 10000), first_data.region)

        shared[shared_name] = shared_data
        shared_groups[shared_name] = [
            entry["per_difficulty"][difficulty_code][0]
            for difficulty_code in sorted(entry["per_difficulty"])
        ]

    return always_on, shared, per_difficulty, shared_groups


def _build_keypickup_alias_tables(raw_aliases, shared_groups):
    shared_aliases = {}
    per_difficulty_aliases = dict(raw_aliases)
    for shared_name, per_names in shared_groups.items():
        aliases = []
        seen = set()
        base_alias = shared_name.split(" - ", 1)[1] if " - " in shared_name else shared_name
        for alias in (base_alias,):
            lowered = alias.lower()
            if lowered not in seen:
                seen.add(lowered)
                aliases.append(alias)
        for source_name in [shared_name, *per_names]:
            for alias in raw_aliases.get(source_name, ()):
                lowered = alias.lower()
                if lowered in seen:
                    continue
                seen.add(lowered)
                aliases.append(alias)
        if aliases:
            shared_aliases[shared_name] = tuple(aliases)
    return shared_aliases, per_difficulty_aliases


raw_goldeneye_locations = goldeneye_locations
raw_keypickup_locations = keypickup_locations
raw_keypickup_detection_aliases = keypickup_detection_aliases

(
    always_on_item_locations,
    shared_item_locations,
    per_difficulty_item_locations,
    ITEM_SHARED_LOCATION_GROUPS,
) = _build_location_mode_tables(raw_goldeneye_locations)
(
    always_on_keypickup_locations,
    shared_keypickup_locations,
    per_difficulty_keypickup_locations,
    KEYPICKUP_SHARED_LOCATION_GROUPS,
) = _build_location_mode_tables(raw_keypickup_locations)
(
    shared_keypickup_detection_aliases,
    per_difficulty_keypickup_detection_aliases,
) = _build_keypickup_alias_tables(raw_keypickup_detection_aliases, KEYPICKUP_SHARED_LOCATION_GROUPS)

goldeneye_locations = {
    **always_on_item_locations,
    **shared_item_locations,
    **per_difficulty_item_locations,
}
keypickup_locations = {
    **always_on_keypickup_locations,
    **shared_keypickup_locations,
    **per_difficulty_keypickup_locations,
}
keypickup_detection_aliases = {
    **shared_keypickup_detection_aliases,
    **per_difficulty_keypickup_detection_aliases,
}

location_table = {
    **goldeneye_locations,
    **keypickup_locations,
    **per_difficulty_clear_locations,
    **shared_clear_locations,
    **per_difficulty_objective_locations,
    **shared_objective_locations,
    **extra_locations,
    **event_locations,
}
