# Auto-generated by codegen.py — do not edit manually
# Generated: 2026-04-22 20:46:20
# Generated file exception:
# This file is machine-written from sheet data, so it may use compact Python.
# We keep the sheet-driven structure here because codegen.py rebuilds it.
# This is safe because codegen.py rebuilds this file from the same source data.

from dataclasses import dataclass
from typing import Dict, List
from Options import Choice, DeathLink, OptionGroup, Range, Toggle
from worlds.AutoWorld import PerGameCommonOptions


def create_option_groups() -> List[OptionGroup]:
    return [
        OptionGroup(name=name, options=options)
        for name, options in GOLDENEYE_OPTION_GROUPS.items()
    ]


class Goal(Choice):
    """
    Cradle: Beat Cradle. All Missions: Beat all 20.
    """
    display_name = "Goal"
    option_cradle = 0
    option_all_missions = 1
    default = 0


class StartingMission(Choice):
    """
    Which mission starts unlocked
    """
    display_name = "Starting Mission"
    option_dam = 1
    option_facility = 2
    option_runway = 3
    option_surface_1 = 4
    option_bunker_1 = 5
    option_silo = 6
    option_frigate = 7
    option_surface_2 = 8
    option_bunker_2 = 9
    option_statue = 10
    option_archives = 11
    option_streets = 12
    option_depot = 13
    option_train = 14
    option_jungle = 15
    option_control = 16
    option_caverns = 17
    option_cradle = 18
    option_aztec = 19
    option_egyptian = 20
    default = 1


class ExtraLocations(Choice):
    """
    Enable Aztec, Egyptian, or both
    """
    display_name = "Add Extra Levels"
    option_aztec = 1
    option_egyptian = 2
    option_both = 3
    option_false = 4
    default = 4


class ObjectiveMode(Choice):
    """
    Choose whether objectives are tracked separately per difficulty or shared across all
    difficulties.
    """
    display_name = "Objective Mode"
    option_per_difficulty = 1
    option_shared = 2
    default = 2


class ItemShuffle(Choice):
    """
    Choose for items to be shuffled. While freestanding guns will be checks, freestanding objective
    objects will be unattainable, NPC dropped items, and NPC handoff items will not be attainable
    until unlocked. Loadout items will be available at the start of the mission only if unlocked.
    """
    display_name = "Shuffle Items"
    option_per_difficulty = 1
    option_shared = 2
    option_off = 3
    default = 2


class GunPickup(Choice):
    """
    Choose if guns will be allowed to be picked up from guards, just the ammo, or not at all.
    Intended option for this randomizer is just ammo as you unlock guns through progressive weapon
    option.
    """
    display_name = "Gun Pickups"
    option_on = 1
    option_just_ammo = 2
    option_off = 3
    default = 2


class MissionClearMode(Choice):
    """
    Each map is one check or one check per difficulty per stage (20 locations vs 60)
    """
    display_name = "Mission Clear Mode"
    option_per_difficulty = 1
    option_per_map = 2
    default = 2


class ProgressiveWeapons(Toggle):
    """
    Makes the progression more interesting. It's like gun game, but you unlock them in order up to
    Golden Gun, but starting with Klobb lol
    """
    display_name = "Progressive Weapons"
    default = 1


class DeathLinkOption(DeathLink):
    """
    When Bond dies you die in real life
    """
    display_name = "DeathLink"
    default = 0


class TrapChance(Range):
    """
    Chance for junk to become trap (0=none 100=fuck you)
    """
    display_name = "Trap Chance"
    range_start = 0
    range_end = 100
    default = 0


class GoldeneyeTrap(Toggle):
    """
    Pretty self explainatory honestly...
    """
    display_name = "Goldeneye Trap"
    default = 0


class EnemyRocketsTrap(Range):
    """
    Weight of enemy rockets trap
    """
    display_name = "Enemy Rockets Trap"
    range_start = 0
    range_end = 100
    default = 100


class HolsterGunTrap(Range):
    """
    Weight of holster gun trap
    """
    display_name = "Holster Gun Trap"
    range_start = 0
    range_end = 100
    default = 25


@dataclass
class GoldeneyeOptions(PerGameCommonOptions):
    goal:                        Goal
    starting_mission:            StartingMission
    extra_locations:             ExtraLocations
    objective_mode:              ObjectiveMode
    item_shuffle:                ItemShuffle
    gun_pickup:                  GunPickup
    mission_clear_mode:          MissionClearMode
    progressive_weapons:         ProgressiveWeapons
    death_link:                  DeathLinkOption
    trap_chance:                 TrapChance
    goldeneye_trap:              GoldeneyeTrap
    enemy_rockets_trap:          EnemyRocketsTrap
    holster_gun_trap:            HolsterGunTrap


GOLDENEYE_OPTION_GROUPS: Dict[str, List[type]] = {
    "General": [
        Goal,
        StartingMission,
        ExtraLocations,
        ObjectiveMode,
        ItemShuffle,
        GunPickup,
        MissionClearMode,
        ProgressiveWeapons,
        DeathLinkOption,
    ],
    "Traps": [
        TrapChance,
        GoldeneyeTrap,
        EnemyRocketsTrap,
        HolsterGunTrap,
    ],
}
