# Auto-generated by codegen.py — do not edit manually
# Generated: 2026-10-07 01:32:06
# Generated file exception:
# This file is machine-written from sheet data, so it may use compact Python.
# We keep the sheet-driven structure here because codegen.py rebuilds it.
# This is safe because codegen.py rebuilds this file from the same source data.

from dataclasses import dataclass
from typing import Dict, List
from Options import Choice, DeathLink, OptionGroup, Range, Toggle
from worlds.AutoWorld import PerGameCommonOptions


def create_option_groups() -> List[OptionGroup]:
    return [
        OptionGroup(name=name, options=options)
        for name, options in GOLDENEYE_OPTION_GROUPS.items()
    ]


class Goal(Choice):
    """
    Cradle: Beat Cradle. All Missions: Beat all 20. All Missions All Difficulties: Why do you hate
    yourself?
    """
    display_name = "Goal"
    option_cradle = 0
    option_all_missions = 1
    option_all_missions_all_difficulties = 2
    default = 0


class StartingMission(Choice):
    """
    Which mission starts unlocked
    """
    display_name = "Starting Mission"
    # Random uses Archipelago's reserved keyword, not a named mission ID.
    random_value = 0
    option_dam = 1
    option_facility = 2
    option_runway = 3
    option_surface_1 = 4
    option_bunker_1 = 5
    option_silo = 6
    option_frigate = 7
    option_surface_2 = 8
    option_bunker_2 = 9
    option_statue = 10
    option_archives = 11
    option_streets = 12
    option_depot = 13
    option_train = 14
    option_jungle = 15
    option_control = 16
    option_caverns = 17
    option_cradle = 18
    option_aztec = 19
    option_egyptian = 20
    default = 'random'

    @classmethod
    def from_text(cls, text: str):
        # Defer Archipelago's random choice until extra missions are known.
        if text.lower() == "random":
            return cls(cls.random_value)
        return super().from_text(text)


class MissionClearMode(Choice):
    """
    Each map is one check or one check per difficulty per stage (20 locations vs 60)
    """
    display_name = "Mission Clear Mode"
    option_per_difficulty = 1
    option_per_map = 2
    default = 2


class ObjectiveMode(Choice):
    """
    Choose whether objectives are tracked separately per difficulty or shared across all
    difficulties.
    """
    display_name = "Objective Mode"
    option_per_difficulty = 1
    option_shared = 2
    default = 2


class ProgressiveWeapons(Toggle):
    """
    Makes the progression more interesting. It's like gun game, but you unlock them in order up to
    Golden Gun, but starting with Klobb lol
    """
    display_name = "Progressive Weapons"
    default = 1


class ExtraLocations(Choice):
    """
    Enable Aztec, Egyptian, or both
    """
    display_name = "Add Extra Levels"
    option_aztec = 1
    option_egyptian = 2
    option_both = 3
    option_false = 4
    default = 4


class ItemShuffle(Choice):
    """
    Choose for freestanding, NPC Drops and Handoffs, and Key items to be shuffled.
    """
    display_name = "Shuffle Items"
    option_per_difficulty = 1
    option_shared = 2
    option_off = 3
    default = 2


class GunPickup(Choice):
    """
    Choose if guns will be allowed to be picked up from guards, just the ammo, or not at all.
    Intended option for this randomizer is just ammo as you unlock guns through progressive weapon
    option.
    """
    display_name = "Gun Pickups"
    option_on = 1
    option_just_ammo = 2
    option_off = 3
    default = 2


class BodyArmorSanity(Choice):
    """
    Body armor locations send checks
    """
    display_name = "Body Armor Sanity"
    option_per_difficulty = 1
    option_shared = 2
    option_off = 3
    default = 3


class AmmoCrateSanity(Choice):
    """
    Ammo Crate locations send checks
    """
    display_name = "Ammo Crate Sanity"
    option_per_difficulty = 1
    option_shared = 2
    option_off = 3
    default = 3


class CheatShuffler(Toggle):
    """
    Cheat Unlock level speedruns are now locations for checks, and cheats are now items in the pool
    that will automatically enable.
    """
    display_name = "Cheats Shuffler"
    default = 0


class SkipCutscenes(Toggle):
    """
    Set to true if you've seen enough of that fucking green truck and want to just play
    """
    display_name = "Skip Cutscenes"
    default = 0


class RandomizeMusic(Toggle):
    """
    Level, intro and menu music will be randomized.
    """
    display_name = "Randomize Music"
    default = 0


class RandomizeEnemies(Toggle):
    """
    Enemy and Bond models will be randomized. Enemy positions and behaviors stay the same.
    """
    display_name = "Randomize Enemies"
    default = 0


class RandomizeEnemyLoadouts(Toggle):
    """
    Enemy weapons can be anything for every enemy in either or both hands
    """
    display_name = "randomize_enemy_loadouts"
    default = 0


class SfxRandomization(Choice):
    """
    Weapons Only shuffles attacks, slappers, throws, reloads, clicks and switches. Categories
    combines attacks, explosions and impacts; ricochets/flybys and casings each stay separate.
    Equip, reload and click sounds join electronics/interface. True Random shuffles all sound
    effects. Continuous sounds retain their stop behavior. Off keeps native sounds.
    """
    display_name = "SFX Randomization"
    option_weapons_only = 1
    option_catagories = 2
    option_true_random = 3
    option_off = 4
    default = 4


class GoldeneyeTrap(Toggle):
    """
    Pretty self explainatory honestly...
    """
    display_name = "Goldeneye Trap"
    default = 0


class HolsterGunTrap(Toggle):
    """
    Oh, whoops, ooh! I dropped my magnum
    """
    display_name = "Holster Gun Trap"
    default = 0


class AutoFailTrap(Toggle):
    """
    Suddenly fail all objectives in current level
    """
    display_name = "Auto Fail Trap"
    default = 0


class TrapChance(Range):
    """
    Chance for junk to become trap (0=none 100=fuck you)
    """
    display_name = "Trap Chance"
    range_start = 0
    range_end = 100
    default = 0


class DeathLinkOption(DeathLink):
    """
    When Bond dies you die in real life
    """
    display_name = "DeathLink"
    default = 0


@dataclass
class GoldeneyeOptions(PerGameCommonOptions):
    goal:                        Goal
    starting_mission:            StartingMission
    mission_clear_mode:          MissionClearMode
    objective_mode:              ObjectiveMode
    progressive_weapons:         ProgressiveWeapons
    extra_locations:             ExtraLocations
    item_shuffle:                ItemShuffle
    gun_pickup:                  GunPickup
    body_armor_sanity:           BodyArmorSanity
    ammo_crate_sanity:           AmmoCrateSanity
    cheat_shuffler:              CheatShuffler
    skip_cutscenes:              SkipCutscenes
    randomize_music:             RandomizeMusic
    randomize_enemies:           RandomizeEnemies
    randomize_enemy_loadouts:    RandomizeEnemyLoadouts
    sfx_randomization:           SfxRandomization
    goldeneye_trap:              GoldeneyeTrap
    holster_gun_trap:            HolsterGunTrap
    auto_fail_trap:              AutoFailTrap
    trap_chance:                 TrapChance
    death_link:                  DeathLinkOption


GOLDENEYE_OPTION_GROUPS: Dict[str, List[type]] = {
    "General": [
        Goal,
        StartingMission,
        MissionClearMode,
        ObjectiveMode,
        ProgressiveWeapons,
        ExtraLocations,
        ItemShuffle,
        GunPickup,
        BodyArmorSanity,
        AmmoCrateSanity,
        CheatShuffler,
        SkipCutscenes,
        RandomizeMusic,
        RandomizeEnemies,
        RandomizeEnemyLoadouts,
        SfxRandomization,
        DeathLinkOption,
    ],
    "Traps": [
        GoldeneyeTrap,
        HolsterGunTrap,
        AutoFailTrap,
        TrapChance,
    ],
}
