# Auto-generated by codegen.py — do not edit manually
# Generated: 2026-10-07 01:32:06
# Generated file exception:
# This file is machine-written from sheet data, so it may use compact Python.
# We keep the sheet-driven structure here because codegen.py rebuilds it.
# This is safe because codegen.py rebuilds this file from the same source data.

from typing import TYPE_CHECKING
from BaseClasses import Region
from .Locations import is_valid_location, location_table
from .Types import GoldeneyeLocation
MISSION_START_LOCATION_NAMES = ('Aztec - Guidance Data', 'Aztec - Guidance Data (Agent)', 'Aztec - Guidance Data (Secret Agent)', 'Aztec - Guidance Data (Double Agent)')

if TYPE_CHECKING:
    from . import GoldeneyeWorld


REGION_CONNECTIONS = [
    ("Dam", "Menu -> Dam"),
    ("Facility", "Menu -> Facility"),
    ("Runway", "Menu -> Runway"),
    ("Surface 1", "Menu -> Surface 1"),
    ("Bunker 1", "Menu -> Bunker 1"),
    ("Silo", "Menu -> Silo"),
    ("Frigate", "Menu -> Frigate"),
    ("Surface 2", "Menu -> Surface 2"),
    ("Bunker 2", "Menu -> Bunker 2"),
    ("Statue", "Menu -> Statue"),
    ("Archives", "Menu -> Archives"),
    ("Streets", "Menu -> Streets"),
    ("Depot", "Menu -> Depot"),
    ("Train", "Menu -> Train"),
    ("Jungle", "Menu -> Jungle"),
    ("Control", "Menu -> Control"),
    ("Caverns", "Menu -> Caverns"),
    ("Cradle", "Menu -> Cradle"),
    ("Aztec", "Menu -> Aztec"),
    ("Egyptian", "Menu -> Egyptian"),
]


def create_regions(world: "GoldeneyeWorld") -> None:
    menu = create_region(world, "Menu")
    for name, entrance_name in REGION_CONNECTIONS:
        menu.connect(create_region(world, name), entrance_name)


def create_region(world: "GoldeneyeWorld", name: str) -> Region:
    reg = Region(name, world.player, world.multiworld)

    # 1. Native starting grants occur before the mission's equipment-gated route.
    for location_name, data in location_table.items():
        region_name = "Menu" if location_name in MISSION_START_LOCATION_NAMES else data.region
        if region_name == name and is_valid_location(world, location_name):
            reg.locations.append(GoldeneyeLocation(world.player, location_name, data.ap_code, reg))

    world.multiworld.regions.append(reg)
    return reg
