# Auto-generated by codegen.py — do not edit manually
# Generated: 2026-04-24 21:28:32
# Generated file exception:
# This file is machine-written from sheet data, so it may use compact Python.
# We keep the sheet-driven structure here because codegen.py rebuilds it.
# This is safe because codegen.py rebuilds this file from the same source data.

from typing import TYPE_CHECKING
from BaseClasses import Region
from .Locations import is_valid_location, location_table
from .Types import GoldeneyeLocation

if TYPE_CHECKING:
    from . import GoldeneyeWorld


REGION_CONNECTIONS = [
    ("Dam", "Menu -> Dam"),
    ("Facility", "Menu -> Facility"),
    ("Runway", "Menu -> Runway"),
    ("Surface 1", "Menu -> Surface 1"),
    ("Bunker 1", "Menu -> Bunker 1"),
    ("Silo", "Menu -> Silo"),
    ("Frigate", "Menu -> Frigate"),
    ("Surface 2", "Menu -> Surface 2"),
    ("Bunker 2", "Menu -> Bunker 2"),
    ("Statue", "Menu -> Statue"),
    ("Archives", "Menu -> Archives"),
    ("Streets", "Menu -> Streets"),
    ("Depot", "Menu -> Depot"),
    ("Train", "Menu -> Train"),
    ("Jungle", "Menu -> Jungle"),
    ("Control", "Menu -> Control"),
    ("Caverns", "Menu -> Caverns"),
    ("Cradle", "Menu -> Cradle"),
    ("Aztec", "Menu -> Aztec"),
    ("Egyptian", "Menu -> Egyptian"),
]


def create_regions(world: "GoldeneyeWorld") -> None:
    menu = create_region(world, "Menu")
    for name, entrance_name in REGION_CONNECTIONS:
        menu.connect(create_region(world, name), entrance_name)


def create_region(world: "GoldeneyeWorld", name: str) -> Region:
    reg = Region(name, world.player, world.multiworld)

    reg.locations.extend(
        GoldeneyeLocation(world.player, key, data.ap_code, reg)
        for key, data in location_table.items()
        if data.region == name and is_valid_location(world, key)
    )

    world.multiworld.regions.append(reg)
    return reg
