# Auto-generated by codegen.py — do not edit manually
# Generated: 2026-03-27 14:41:52

from typing import TYPE_CHECKING
from worlds.generic.Rules import add_rule
from .Items import MISSION_UNLOCK_NAMES
from .Locations import EXTRA_MISSION_NAMES, get_enabled_extra_missions

if TYPE_CHECKING:
    from . import GoldeneyeWorld


MISSION_RULES = [
    ("Menu -> Dam", "Dam"),
    ("Menu -> Facility", "Facility"),
    ("Menu -> Runway", "Runway"),
    ("Menu -> Surface 1", "Surface 1"),
    ("Menu -> Bunker 1", "Bunker 1"),
    ("Menu -> Silo", "Silo"),
    ("Menu -> Frigate", "Frigate"),
    ("Menu -> Surface 2", "Surface 2"),
    ("Menu -> Bunker 2", "Bunker 2"),
    ("Menu -> Statue", "Statue"),
    ("Menu -> Archives", "Archives"),
    ("Menu -> Streets", "Streets"),
    ("Menu -> Depot", "Depot"),
    ("Menu -> Train", "Train"),
    ("Menu -> Jungle", "Jungle"),
    ("Menu -> Control", "Control"),
    ("Menu -> Caverns", "Caverns"),
    ("Menu -> Cradle", "Cradle"),
    ("Menu -> Aztec", "Aztec"),
    ("Menu -> Egyptian", "Egyptian"),
]


def set_rules(world: "GoldeneyeWorld") -> None:
    player = world.player
    starting_unlock = MISSION_UNLOCK_NAMES[world.options.starting_mission.value - 1]

    enabled_extra_missions = get_enabled_extra_missions(world)
    for entrance_name, unlock_name in MISSION_RULES:
        entrance = world.multiworld.get_entrance(entrance_name, player)
        if unlock_name in EXTRA_MISSION_NAMES and unlock_name not in enabled_extra_missions:
            add_rule(entrance, lambda state: False)
        elif unlock_name == starting_unlock:
            add_rule(entrance, lambda state: True)
        else:
            add_rule(entrance, lambda state, item=unlock_name: state.has(item, player))

    world.multiworld.completion_condition[player] = lambda state: state.has("Victory", player)
